#include "unity.h"
#include "file.h"

void
test___file_extname(void)
{
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("foo"), "Path: 'foo'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname("foo.ext"), "Path: 'foo.ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("foo "), "Path: 'foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname("foo .ext"), "Path: 'foo .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("foo."), "Path: 'foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname("foo..ext"), "Path: 'foo..ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("foo.ext "), "Path: 'foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname("foo.ext .ext"), "Path: 'foo.ext .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("foo "), "Path: 'foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("foo.ext "), "Path: 'foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("foo  "), "Path: 'foo  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("foo .ext "), "Path: 'foo .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(". ", file_extname("foo. "), "Path: 'foo. '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("foo..ext "), "Path: 'foo..ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext  ", file_extname("foo.ext  "), "Path: 'foo.ext  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("foo.ext .ext "), "Path: 'foo.ext .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("foo."), "Path: 'foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("foo.ext."), "Path: 'foo.ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("foo ."), "Path: 'foo .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("foo .ext."), "Path: 'foo .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("foo.."), "Path: 'foo..'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("foo..ext."), "Path: 'foo..ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("foo.ext ."), "Path: 'foo.ext .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("foo.ext .ext."), "Path: 'foo.ext .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("foo.bar"), "Path: 'foo.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("foo.ext.bar"), "Path: 'foo.ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("foo .bar"), "Path: 'foo .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("foo .ext.bar"), "Path: 'foo .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("foo..bar"), "Path: 'foo..bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("foo..ext.bar"), "Path: 'foo..ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("foo.ext .bar"), "Path: 'foo.ext .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("foo.ext .ext.bar"), "Path: 'foo.ext .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("foo::$DATA"), "Path: 'foo::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname("foo.ext::$DATA"), "Path: 'foo.ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("foo ::$DATA"), "Path: 'foo ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname("foo .ext::$DATA"), "Path: 'foo .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".::$DATA", file_extname("foo.::$DATA"), "Path: 'foo.::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname("foo..ext::$DATA"), "Path: 'foo..ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ::$DATA", file_extname("foo.ext ::$DATA"), "Path: 'foo.ext ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname("foo.ext .ext::$DATA"), "Path: 'foo.ext .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("foo::$DATA.bar"), "Path: 'foo::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("foo.ext::$DATA.bar"), "Path: 'foo.ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("foo ::$DATA.bar"), "Path: 'foo ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("foo .ext::$DATA.bar"), "Path: 'foo .ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("foo.::$DATA.bar"), "Path: 'foo.::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("foo..ext::$DATA.bar"), "Path: 'foo..ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("foo.ext ::$DATA.bar"), "Path: 'foo.ext ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("foo.ext .ext::$DATA.bar"), "Path: 'foo.ext .ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("//foo"), "Path: '//foo'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname("//foo.ext"), "Path: '//foo.ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("//foo "), "Path: '//foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname("//foo .ext"), "Path: '//foo .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("//foo."), "Path: '//foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname("//foo..ext"), "Path: '//foo..ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("//foo.ext "), "Path: '//foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname("//foo.ext .ext"), "Path: '//foo.ext .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("//foo "), "Path: '//foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("//foo.ext "), "Path: '//foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("//foo  "), "Path: '//foo  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("//foo .ext "), "Path: '//foo .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(". ", file_extname("//foo. "), "Path: '//foo. '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("//foo..ext "), "Path: '//foo..ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext  ", file_extname("//foo.ext  "), "Path: '//foo.ext  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("//foo.ext .ext "), "Path: '//foo.ext .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("//foo."), "Path: '//foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("//foo.ext."), "Path: '//foo.ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("//foo ."), "Path: '//foo .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("//foo .ext."), "Path: '//foo .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("//foo.."), "Path: '//foo..'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("//foo..ext."), "Path: '//foo..ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("//foo.ext ."), "Path: '//foo.ext .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("//foo.ext .ext."), "Path: '//foo.ext .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("//foo.bar"), "Path: '//foo.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("//foo.ext.bar"), "Path: '//foo.ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("//foo .bar"), "Path: '//foo .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("//foo .ext.bar"), "Path: '//foo .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("//foo..bar"), "Path: '//foo..bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("//foo..ext.bar"), "Path: '//foo..ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("//foo.ext .bar"), "Path: '//foo.ext .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("//foo.ext .ext.bar"), "Path: '//foo.ext .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("//foo::$DATA"), "Path: '//foo::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname("//foo.ext::$DATA"), "Path: '//foo.ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("//foo ::$DATA"), "Path: '//foo ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname("//foo .ext::$DATA"), "Path: '//foo .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".::$DATA", file_extname("//foo.::$DATA"), "Path: '//foo.::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname("//foo..ext::$DATA"), "Path: '//foo..ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ::$DATA", file_extname("//foo.ext ::$DATA"), "Path: '//foo.ext ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname("//foo.ext .ext::$DATA"), "Path: '//foo.ext .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("//foo::$DATA.bar"), "Path: '//foo::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("//foo.ext::$DATA.bar"), "Path: '//foo.ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("//foo ::$DATA.bar"), "Path: '//foo ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("//foo .ext::$DATA.bar"), "Path: '//foo .ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("//foo.::$DATA.bar"), "Path: '//foo.::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("//foo..ext::$DATA.bar"), "Path: '//foo..ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("//foo.ext ::$DATA.bar"), "Path: '//foo.ext ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("//foo.ext .ext::$DATA.bar"), "Path: '//foo.ext .ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/foo"), "Path: '/foo'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname("/foo.ext"), "Path: '/foo.ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/foo "), "Path: '/foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname("/foo .ext"), "Path: '/foo .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/foo."), "Path: '/foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname("/foo..ext"), "Path: '/foo..ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("/foo.ext "), "Path: '/foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname("/foo.ext .ext"), "Path: '/foo.ext .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/foo "), "Path: '/foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("/foo.ext "), "Path: '/foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/foo  "), "Path: '/foo  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("/foo .ext "), "Path: '/foo .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(". ", file_extname("/foo. "), "Path: '/foo. '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("/foo..ext "), "Path: '/foo..ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext  ", file_extname("/foo.ext  "), "Path: '/foo.ext  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("/foo.ext .ext "), "Path: '/foo.ext .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/foo."), "Path: '/foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/foo.ext."), "Path: '/foo.ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/foo ."), "Path: '/foo .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/foo .ext."), "Path: '/foo .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/foo.."), "Path: '/foo..'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/foo..ext."), "Path: '/foo..ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/foo.ext ."), "Path: '/foo.ext .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/foo.ext .ext."), "Path: '/foo.ext .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/foo.bar"), "Path: '/foo.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/foo.ext.bar"), "Path: '/foo.ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/foo .bar"), "Path: '/foo .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/foo .ext.bar"), "Path: '/foo .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/foo..bar"), "Path: '/foo..bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/foo..ext.bar"), "Path: '/foo..ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/foo.ext .bar"), "Path: '/foo.ext .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/foo.ext .ext.bar"), "Path: '/foo.ext .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/foo::$DATA"), "Path: '/foo::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname("/foo.ext::$DATA"), "Path: '/foo.ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/foo ::$DATA"), "Path: '/foo ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname("/foo .ext::$DATA"), "Path: '/foo .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".::$DATA", file_extname("/foo.::$DATA"), "Path: '/foo.::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname("/foo..ext::$DATA"), "Path: '/foo..ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ::$DATA", file_extname("/foo.ext ::$DATA"), "Path: '/foo.ext ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname("/foo.ext .ext::$DATA"), "Path: '/foo.ext .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/foo::$DATA.bar"), "Path: '/foo::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/foo.ext::$DATA.bar"), "Path: '/foo.ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/foo ::$DATA.bar"), "Path: '/foo ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/foo .ext::$DATA.bar"), "Path: '/foo .ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/foo.::$DATA.bar"), "Path: '/foo.::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/foo..ext::$DATA.bar"), "Path: '/foo..ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/foo.ext ::$DATA.bar"), "Path: '/foo.ext ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/foo.ext .ext::$DATA.bar"), "Path: '/foo.ext .ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname(".foo"), "Path: '.foo'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname(".foo.ext"), "Path: '.foo.ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname(".foo "), "Path: '.foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname(".foo .ext"), "Path: '.foo .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname(".foo."), "Path: '.foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname(".foo..ext"), "Path: '.foo..ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname(".foo.ext "), "Path: '.foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname(".foo.ext .ext"), "Path: '.foo.ext .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname(".foo "), "Path: '.foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname(".foo.ext "), "Path: '.foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname(".foo  "), "Path: '.foo  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname(".foo .ext "), "Path: '.foo .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(". ", file_extname(".foo. "), "Path: '.foo. '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname(".foo..ext "), "Path: '.foo..ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext  ", file_extname(".foo.ext  "), "Path: '.foo.ext  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname(".foo.ext .ext "), "Path: '.foo.ext .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname(".foo."), "Path: '.foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname(".foo.ext."), "Path: '.foo.ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname(".foo ."), "Path: '.foo .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname(".foo .ext."), "Path: '.foo .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname(".foo.."), "Path: '.foo..'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname(".foo..ext."), "Path: '.foo..ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname(".foo.ext ."), "Path: '.foo.ext .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname(".foo.ext .ext."), "Path: '.foo.ext .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname(".foo.bar"), "Path: '.foo.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname(".foo.ext.bar"), "Path: '.foo.ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname(".foo .bar"), "Path: '.foo .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname(".foo .ext.bar"), "Path: '.foo .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname(".foo..bar"), "Path: '.foo..bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname(".foo..ext.bar"), "Path: '.foo..ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname(".foo.ext .bar"), "Path: '.foo.ext .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname(".foo.ext .ext.bar"), "Path: '.foo.ext .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname(".foo::$DATA"), "Path: '.foo::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname(".foo.ext::$DATA"), "Path: '.foo.ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname(".foo ::$DATA"), "Path: '.foo ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname(".foo .ext::$DATA"), "Path: '.foo .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".::$DATA", file_extname(".foo.::$DATA"), "Path: '.foo.::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname(".foo..ext::$DATA"), "Path: '.foo..ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ::$DATA", file_extname(".foo.ext ::$DATA"), "Path: '.foo.ext ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname(".foo.ext .ext::$DATA"), "Path: '.foo.ext .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname(".foo::$DATA.bar"), "Path: '.foo::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname(".foo.ext::$DATA.bar"), "Path: '.foo.ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname(".foo ::$DATA.bar"), "Path: '.foo ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname(".foo .ext::$DATA.bar"), "Path: '.foo .ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname(".foo.::$DATA.bar"), "Path: '.foo.::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname(".foo..ext::$DATA.bar"), "Path: '.foo..ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname(".foo.ext ::$DATA.bar"), "Path: '.foo.ext ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname(".foo.ext .ext::$DATA.bar"), "Path: '.foo.ext .ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/.foo"), "Path: '/.foo'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname("/.foo.ext"), "Path: '/.foo.ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/.foo "), "Path: '/.foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname("/.foo .ext"), "Path: '/.foo .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/.foo."), "Path: '/.foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname("/.foo..ext"), "Path: '/.foo..ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("/.foo.ext "), "Path: '/.foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname("/.foo.ext .ext"), "Path: '/.foo.ext .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/.foo "), "Path: '/.foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("/.foo.ext "), "Path: '/.foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/.foo  "), "Path: '/.foo  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("/.foo .ext "), "Path: '/.foo .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(". ", file_extname("/.foo. "), "Path: '/.foo. '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("/.foo..ext "), "Path: '/.foo..ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext  ", file_extname("/.foo.ext  "), "Path: '/.foo.ext  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("/.foo.ext .ext "), "Path: '/.foo.ext .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/.foo."), "Path: '/.foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/.foo.ext."), "Path: '/.foo.ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/.foo ."), "Path: '/.foo .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/.foo .ext."), "Path: '/.foo .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/.foo.."), "Path: '/.foo..'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/.foo..ext."), "Path: '/.foo..ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/.foo.ext ."), "Path: '/.foo.ext .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/.foo.ext .ext."), "Path: '/.foo.ext .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/.foo.bar"), "Path: '/.foo.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/.foo.ext.bar"), "Path: '/.foo.ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/.foo .bar"), "Path: '/.foo .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/.foo .ext.bar"), "Path: '/.foo .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/.foo..bar"), "Path: '/.foo..bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/.foo..ext.bar"), "Path: '/.foo..ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/.foo.ext .bar"), "Path: '/.foo.ext .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/.foo.ext .ext.bar"), "Path: '/.foo.ext .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/.foo::$DATA"), "Path: '/.foo::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname("/.foo.ext::$DATA"), "Path: '/.foo.ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/.foo ::$DATA"), "Path: '/.foo ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname("/.foo .ext::$DATA"), "Path: '/.foo .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".::$DATA", file_extname("/.foo.::$DATA"), "Path: '/.foo.::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname("/.foo..ext::$DATA"), "Path: '/.foo..ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ::$DATA", file_extname("/.foo.ext ::$DATA"), "Path: '/.foo.ext ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname("/.foo.ext .ext::$DATA"), "Path: '/.foo.ext .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/.foo::$DATA.bar"), "Path: '/.foo::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/.foo.ext::$DATA.bar"), "Path: '/.foo.ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/.foo ::$DATA.bar"), "Path: '/.foo ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/.foo .ext::$DATA.bar"), "Path: '/.foo .ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/.foo.::$DATA.bar"), "Path: '/.foo.::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/.foo..ext::$DATA.bar"), "Path: '/.foo..ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/.foo.ext ::$DATA.bar"), "Path: '/.foo.ext ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/.foo.ext .ext::$DATA.bar"), "Path: '/.foo.ext .ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("bar/.foo"), "Path: 'bar/.foo'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname("bar/.foo.ext"), "Path: 'bar/.foo.ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("bar/.foo "), "Path: 'bar/.foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname("bar/.foo .ext"), "Path: 'bar/.foo .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("bar/.foo."), "Path: 'bar/.foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname("bar/.foo..ext"), "Path: 'bar/.foo..ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("bar/.foo.ext "), "Path: 'bar/.foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname("bar/.foo.ext .ext"), "Path: 'bar/.foo.ext .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("bar/.foo "), "Path: 'bar/.foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("bar/.foo.ext "), "Path: 'bar/.foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("bar/.foo  "), "Path: 'bar/.foo  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("bar/.foo .ext "), "Path: 'bar/.foo .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(". ", file_extname("bar/.foo. "), "Path: 'bar/.foo. '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("bar/.foo..ext "), "Path: 'bar/.foo..ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext  ", file_extname("bar/.foo.ext  "), "Path: 'bar/.foo.ext  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("bar/.foo.ext .ext "), "Path: 'bar/.foo.ext .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("bar/.foo."), "Path: 'bar/.foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("bar/.foo.ext."), "Path: 'bar/.foo.ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("bar/.foo ."), "Path: 'bar/.foo .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("bar/.foo .ext."), "Path: 'bar/.foo .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("bar/.foo.."), "Path: 'bar/.foo..'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("bar/.foo..ext."), "Path: 'bar/.foo..ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("bar/.foo.ext ."), "Path: 'bar/.foo.ext .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("bar/.foo.ext .ext."), "Path: 'bar/.foo.ext .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("bar/.foo.bar"), "Path: 'bar/.foo.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("bar/.foo.ext.bar"), "Path: 'bar/.foo.ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("bar/.foo .bar"), "Path: 'bar/.foo .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("bar/.foo .ext.bar"), "Path: 'bar/.foo .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("bar/.foo..bar"), "Path: 'bar/.foo..bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("bar/.foo..ext.bar"), "Path: 'bar/.foo..ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("bar/.foo.ext .bar"), "Path: 'bar/.foo.ext .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("bar/.foo.ext .ext.bar"), "Path: 'bar/.foo.ext .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("bar/.foo::$DATA"), "Path: 'bar/.foo::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname("bar/.foo.ext::$DATA"), "Path: 'bar/.foo.ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("bar/.foo ::$DATA"), "Path: 'bar/.foo ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname("bar/.foo .ext::$DATA"), "Path: 'bar/.foo .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".::$DATA", file_extname("bar/.foo.::$DATA"), "Path: 'bar/.foo.::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname("bar/.foo..ext::$DATA"), "Path: 'bar/.foo..ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ::$DATA", file_extname("bar/.foo.ext ::$DATA"), "Path: 'bar/.foo.ext ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname("bar/.foo.ext .ext::$DATA"), "Path: 'bar/.foo.ext .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("bar/.foo::$DATA.bar"), "Path: 'bar/.foo::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("bar/.foo.ext::$DATA.bar"), "Path: 'bar/.foo.ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("bar/.foo ::$DATA.bar"), "Path: 'bar/.foo ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("bar/.foo .ext::$DATA.bar"), "Path: 'bar/.foo .ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("bar/.foo.::$DATA.bar"), "Path: 'bar/.foo.::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("bar/.foo..ext::$DATA.bar"), "Path: 'bar/.foo..ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("bar/.foo.ext ::$DATA.bar"), "Path: 'bar/.foo.ext ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("bar/.foo.ext .ext::$DATA.bar"), "Path: 'bar/.foo.ext .ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/bar/.foo"), "Path: '/bar/.foo'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname("/bar/.foo.ext"), "Path: '/bar/.foo.ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/bar/.foo "), "Path: '/bar/.foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname("/bar/.foo .ext"), "Path: '/bar/.foo .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/bar/.foo."), "Path: '/bar/.foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname("/bar/.foo..ext"), "Path: '/bar/.foo..ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("/bar/.foo.ext "), "Path: '/bar/.foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", file_extname("/bar/.foo.ext .ext"), "Path: '/bar/.foo.ext .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/bar/.foo "), "Path: '/bar/.foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("/bar/.foo.ext "), "Path: '/bar/.foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/bar/.foo  "), "Path: '/bar/.foo  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("/bar/.foo .ext "), "Path: '/bar/.foo .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(". ", file_extname("/bar/.foo. "), "Path: '/bar/.foo. '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("/bar/.foo..ext "), "Path: '/bar/.foo..ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext  ", file_extname("/bar/.foo.ext  "), "Path: '/bar/.foo.ext  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", file_extname("/bar/.foo.ext .ext "), "Path: '/bar/.foo.ext .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/bar/.foo."), "Path: '/bar/.foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/bar/.foo.ext."), "Path: '/bar/.foo.ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/bar/.foo ."), "Path: '/bar/.foo .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/bar/.foo .ext."), "Path: '/bar/.foo .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/bar/.foo.."), "Path: '/bar/.foo..'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/bar/.foo..ext."), "Path: '/bar/.foo..ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/bar/.foo.ext ."), "Path: '/bar/.foo.ext .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/bar/.foo.ext .ext."), "Path: '/bar/.foo.ext .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/bar/.foo.bar"), "Path: '/bar/.foo.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/bar/.foo.ext.bar"), "Path: '/bar/.foo.ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/bar/.foo .bar"), "Path: '/bar/.foo .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/bar/.foo .ext.bar"), "Path: '/bar/.foo .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/bar/.foo..bar"), "Path: '/bar/.foo..bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/bar/.foo..ext.bar"), "Path: '/bar/.foo..ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/bar/.foo.ext .bar"), "Path: '/bar/.foo.ext .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/bar/.foo.ext .ext.bar"), "Path: '/bar/.foo.ext .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/bar/.foo::$DATA"), "Path: '/bar/.foo::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname("/bar/.foo.ext::$DATA"), "Path: '/bar/.foo.ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", file_extname("/bar/.foo ::$DATA"), "Path: '/bar/.foo ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname("/bar/.foo .ext::$DATA"), "Path: '/bar/.foo .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".::$DATA", file_extname("/bar/.foo.::$DATA"), "Path: '/bar/.foo.::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname("/bar/.foo..ext::$DATA"), "Path: '/bar/.foo..ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ::$DATA", file_extname("/bar/.foo.ext ::$DATA"), "Path: '/bar/.foo.ext ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", file_extname("/bar/.foo.ext .ext::$DATA"), "Path: '/bar/.foo.ext .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/bar/.foo::$DATA.bar"), "Path: '/bar/.foo::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/bar/.foo.ext::$DATA.bar"), "Path: '/bar/.foo.ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/bar/.foo ::$DATA.bar"), "Path: '/bar/.foo ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/bar/.foo .ext::$DATA.bar"), "Path: '/bar/.foo .ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/bar/.foo.::$DATA.bar"), "Path: '/bar/.foo.::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/bar/.foo..ext::$DATA.bar"), "Path: '/bar/.foo..ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/bar/.foo.ext ::$DATA.bar"), "Path: '/bar/.foo.ext ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", file_extname("/bar/.foo.ext .ext::$DATA.bar"), "Path: '/bar/.foo.ext .ext::$DATA.bar'");
}

void
test___file_basename(void)
{
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo", file_basename("foo"), "Path: 'foo'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext", file_basename("foo.ext"), "Path: 'foo.ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo ", file_basename("foo "), "Path: 'foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext", file_basename("foo .ext"), "Path: 'foo .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.", file_basename("foo."), "Path: 'foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext", file_basename("foo..ext"), "Path: 'foo..ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext ", file_basename("foo.ext "), "Path: 'foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext", file_basename("foo.ext .ext"), "Path: 'foo.ext .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo ", file_basename("foo "), "Path: 'foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext ", file_basename("foo.ext "), "Path: 'foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo  ", file_basename("foo  "), "Path: 'foo  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext ", file_basename("foo .ext "), "Path: 'foo .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo. ", file_basename("foo. "), "Path: 'foo. '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext ", file_basename("foo..ext "), "Path: 'foo..ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext  ", file_basename("foo.ext  "), "Path: 'foo.ext  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext ", file_basename("foo.ext .ext "), "Path: 'foo.ext .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.", file_basename("foo."), "Path: 'foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext.", file_basename("foo.ext."), "Path: 'foo.ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .", file_basename("foo ."), "Path: 'foo .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext.", file_basename("foo .ext."), "Path: 'foo .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..", file_basename("foo.."), "Path: 'foo..'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext.", file_basename("foo..ext."), "Path: 'foo..ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .", file_basename("foo.ext ."), "Path: 'foo.ext .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext.", file_basename("foo.ext .ext."), "Path: 'foo.ext .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.bar", file_basename("foo.bar"), "Path: 'foo.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext.bar", file_basename("foo.ext.bar"), "Path: 'foo.ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .bar", file_basename("foo .bar"), "Path: 'foo .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext.bar", file_basename("foo .ext.bar"), "Path: 'foo .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..bar", file_basename("foo..bar"), "Path: 'foo..bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext.bar", file_basename("foo..ext.bar"), "Path: 'foo..ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .bar", file_basename("foo.ext .bar"), "Path: 'foo.ext .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext.bar", file_basename("foo.ext .ext.bar"), "Path: 'foo.ext .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo::$DATA", file_basename("foo::$DATA"), "Path: 'foo::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext::$DATA", file_basename("foo.ext::$DATA"), "Path: 'foo.ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo ::$DATA", file_basename("foo ::$DATA"), "Path: 'foo ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext::$DATA", file_basename("foo .ext::$DATA"), "Path: 'foo .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.::$DATA", file_basename("foo.::$DATA"), "Path: 'foo.::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext::$DATA", file_basename("foo..ext::$DATA"), "Path: 'foo..ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext ::$DATA", file_basename("foo.ext ::$DATA"), "Path: 'foo.ext ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext::$DATA", file_basename("foo.ext .ext::$DATA"), "Path: 'foo.ext .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo::$DATA.bar", file_basename("foo::$DATA.bar"), "Path: 'foo::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext::$DATA.bar", file_basename("foo.ext::$DATA.bar"), "Path: 'foo.ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo ::$DATA.bar", file_basename("foo ::$DATA.bar"), "Path: 'foo ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext::$DATA.bar", file_basename("foo .ext::$DATA.bar"), "Path: 'foo .ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.::$DATA.bar", file_basename("foo.::$DATA.bar"), "Path: 'foo.::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext::$DATA.bar", file_basename("foo..ext::$DATA.bar"), "Path: 'foo..ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext ::$DATA.bar", file_basename("foo.ext ::$DATA.bar"), "Path: 'foo.ext ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext::$DATA.bar", file_basename("foo.ext .ext::$DATA.bar"), "Path: 'foo.ext .ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo", file_basename("//foo"), "Path: '//foo'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext", file_basename("//foo.ext"), "Path: '//foo.ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo ", file_basename("//foo "), "Path: '//foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext", file_basename("//foo .ext"), "Path: '//foo .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.", file_basename("//foo."), "Path: '//foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext", file_basename("//foo..ext"), "Path: '//foo..ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext ", file_basename("//foo.ext "), "Path: '//foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext", file_basename("//foo.ext .ext"), "Path: '//foo.ext .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo ", file_basename("//foo "), "Path: '//foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext ", file_basename("//foo.ext "), "Path: '//foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo  ", file_basename("//foo  "), "Path: '//foo  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext ", file_basename("//foo .ext "), "Path: '//foo .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo. ", file_basename("//foo. "), "Path: '//foo. '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext ", file_basename("//foo..ext "), "Path: '//foo..ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext  ", file_basename("//foo.ext  "), "Path: '//foo.ext  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext ", file_basename("//foo.ext .ext "), "Path: '//foo.ext .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.", file_basename("//foo."), "Path: '//foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext.", file_basename("//foo.ext."), "Path: '//foo.ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .", file_basename("//foo ."), "Path: '//foo .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext.", file_basename("//foo .ext."), "Path: '//foo .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..", file_basename("//foo.."), "Path: '//foo..'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext.", file_basename("//foo..ext."), "Path: '//foo..ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .", file_basename("//foo.ext ."), "Path: '//foo.ext .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext.", file_basename("//foo.ext .ext."), "Path: '//foo.ext .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.bar", file_basename("//foo.bar"), "Path: '//foo.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext.bar", file_basename("//foo.ext.bar"), "Path: '//foo.ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .bar", file_basename("//foo .bar"), "Path: '//foo .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext.bar", file_basename("//foo .ext.bar"), "Path: '//foo .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..bar", file_basename("//foo..bar"), "Path: '//foo..bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext.bar", file_basename("//foo..ext.bar"), "Path: '//foo..ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .bar", file_basename("//foo.ext .bar"), "Path: '//foo.ext .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext.bar", file_basename("//foo.ext .ext.bar"), "Path: '//foo.ext .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo::$DATA", file_basename("//foo::$DATA"), "Path: '//foo::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext::$DATA", file_basename("//foo.ext::$DATA"), "Path: '//foo.ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo ::$DATA", file_basename("//foo ::$DATA"), "Path: '//foo ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext::$DATA", file_basename("//foo .ext::$DATA"), "Path: '//foo .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.::$DATA", file_basename("//foo.::$DATA"), "Path: '//foo.::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext::$DATA", file_basename("//foo..ext::$DATA"), "Path: '//foo..ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext ::$DATA", file_basename("//foo.ext ::$DATA"), "Path: '//foo.ext ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext::$DATA", file_basename("//foo.ext .ext::$DATA"), "Path: '//foo.ext .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo::$DATA.bar", file_basename("//foo::$DATA.bar"), "Path: '//foo::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext::$DATA.bar", file_basename("//foo.ext::$DATA.bar"), "Path: '//foo.ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo ::$DATA.bar", file_basename("//foo ::$DATA.bar"), "Path: '//foo ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext::$DATA.bar", file_basename("//foo .ext::$DATA.bar"), "Path: '//foo .ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.::$DATA.bar", file_basename("//foo.::$DATA.bar"), "Path: '//foo.::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext::$DATA.bar", file_basename("//foo..ext::$DATA.bar"), "Path: '//foo..ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext ::$DATA.bar", file_basename("//foo.ext ::$DATA.bar"), "Path: '//foo.ext ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext::$DATA.bar", file_basename("//foo.ext .ext::$DATA.bar"), "Path: '//foo.ext .ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo", file_basename("/foo"), "Path: '/foo'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext", file_basename("/foo.ext"), "Path: '/foo.ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo ", file_basename("/foo "), "Path: '/foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext", file_basename("/foo .ext"), "Path: '/foo .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.", file_basename("/foo."), "Path: '/foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext", file_basename("/foo..ext"), "Path: '/foo..ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext ", file_basename("/foo.ext "), "Path: '/foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext", file_basename("/foo.ext .ext"), "Path: '/foo.ext .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo ", file_basename("/foo "), "Path: '/foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext ", file_basename("/foo.ext "), "Path: '/foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo  ", file_basename("/foo  "), "Path: '/foo  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext ", file_basename("/foo .ext "), "Path: '/foo .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo. ", file_basename("/foo. "), "Path: '/foo. '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext ", file_basename("/foo..ext "), "Path: '/foo..ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext  ", file_basename("/foo.ext  "), "Path: '/foo.ext  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext ", file_basename("/foo.ext .ext "), "Path: '/foo.ext .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.", file_basename("/foo."), "Path: '/foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext.", file_basename("/foo.ext."), "Path: '/foo.ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .", file_basename("/foo ."), "Path: '/foo .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext.", file_basename("/foo .ext."), "Path: '/foo .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..", file_basename("/foo.."), "Path: '/foo..'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext.", file_basename("/foo..ext."), "Path: '/foo..ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .", file_basename("/foo.ext ."), "Path: '/foo.ext .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext.", file_basename("/foo.ext .ext."), "Path: '/foo.ext .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.bar", file_basename("/foo.bar"), "Path: '/foo.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext.bar", file_basename("/foo.ext.bar"), "Path: '/foo.ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .bar", file_basename("/foo .bar"), "Path: '/foo .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext.bar", file_basename("/foo .ext.bar"), "Path: '/foo .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..bar", file_basename("/foo..bar"), "Path: '/foo..bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext.bar", file_basename("/foo..ext.bar"), "Path: '/foo..ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .bar", file_basename("/foo.ext .bar"), "Path: '/foo.ext .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext.bar", file_basename("/foo.ext .ext.bar"), "Path: '/foo.ext .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo::$DATA", file_basename("/foo::$DATA"), "Path: '/foo::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext::$DATA", file_basename("/foo.ext::$DATA"), "Path: '/foo.ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo ::$DATA", file_basename("/foo ::$DATA"), "Path: '/foo ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext::$DATA", file_basename("/foo .ext::$DATA"), "Path: '/foo .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.::$DATA", file_basename("/foo.::$DATA"), "Path: '/foo.::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext::$DATA", file_basename("/foo..ext::$DATA"), "Path: '/foo..ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext ::$DATA", file_basename("/foo.ext ::$DATA"), "Path: '/foo.ext ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext::$DATA", file_basename("/foo.ext .ext::$DATA"), "Path: '/foo.ext .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo::$DATA.bar", file_basename("/foo::$DATA.bar"), "Path: '/foo::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext::$DATA.bar", file_basename("/foo.ext::$DATA.bar"), "Path: '/foo.ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo ::$DATA.bar", file_basename("/foo ::$DATA.bar"), "Path: '/foo ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext::$DATA.bar", file_basename("/foo .ext::$DATA.bar"), "Path: '/foo .ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.::$DATA.bar", file_basename("/foo.::$DATA.bar"), "Path: '/foo.::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext::$DATA.bar", file_basename("/foo..ext::$DATA.bar"), "Path: '/foo..ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext ::$DATA.bar", file_basename("/foo.ext ::$DATA.bar"), "Path: '/foo.ext ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext::$DATA.bar", file_basename("/foo.ext .ext::$DATA.bar"), "Path: '/foo.ext .ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo", file_basename(".foo"), "Path: '.foo'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext", file_basename(".foo.ext"), "Path: '.foo.ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ", file_basename(".foo "), "Path: '.foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext", file_basename(".foo .ext"), "Path: '.foo .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.", file_basename(".foo."), "Path: '.foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext", file_basename(".foo..ext"), "Path: '.foo..ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ", file_basename(".foo.ext "), "Path: '.foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext", file_basename(".foo.ext .ext"), "Path: '.foo.ext .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ", file_basename(".foo "), "Path: '.foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ", file_basename(".foo.ext "), "Path: '.foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo  ", file_basename(".foo  "), "Path: '.foo  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext ", file_basename(".foo .ext "), "Path: '.foo .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo. ", file_basename(".foo. "), "Path: '.foo. '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext ", file_basename(".foo..ext "), "Path: '.foo..ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext  ", file_basename(".foo.ext  "), "Path: '.foo.ext  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext ", file_basename(".foo.ext .ext "), "Path: '.foo.ext .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.", file_basename(".foo."), "Path: '.foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext.", file_basename(".foo.ext."), "Path: '.foo.ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .", file_basename(".foo ."), "Path: '.foo .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext.", file_basename(".foo .ext."), "Path: '.foo .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..", file_basename(".foo.."), "Path: '.foo..'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext.", file_basename(".foo..ext."), "Path: '.foo..ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .", file_basename(".foo.ext ."), "Path: '.foo.ext .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext.", file_basename(".foo.ext .ext."), "Path: '.foo.ext .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.bar", file_basename(".foo.bar"), "Path: '.foo.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext.bar", file_basename(".foo.ext.bar"), "Path: '.foo.ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .bar", file_basename(".foo .bar"), "Path: '.foo .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext.bar", file_basename(".foo .ext.bar"), "Path: '.foo .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..bar", file_basename(".foo..bar"), "Path: '.foo..bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext.bar", file_basename(".foo..ext.bar"), "Path: '.foo..ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .bar", file_basename(".foo.ext .bar"), "Path: '.foo.ext .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext.bar", file_basename(".foo.ext .ext.bar"), "Path: '.foo.ext .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo::$DATA", file_basename(".foo::$DATA"), "Path: '.foo::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext::$DATA", file_basename(".foo.ext::$DATA"), "Path: '.foo.ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ::$DATA", file_basename(".foo ::$DATA"), "Path: '.foo ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext::$DATA", file_basename(".foo .ext::$DATA"), "Path: '.foo .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.::$DATA", file_basename(".foo.::$DATA"), "Path: '.foo.::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext::$DATA", file_basename(".foo..ext::$DATA"), "Path: '.foo..ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ::$DATA", file_basename(".foo.ext ::$DATA"), "Path: '.foo.ext ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext::$DATA", file_basename(".foo.ext .ext::$DATA"), "Path: '.foo.ext .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo::$DATA.bar", file_basename(".foo::$DATA.bar"), "Path: '.foo::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext::$DATA.bar", file_basename(".foo.ext::$DATA.bar"), "Path: '.foo.ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ::$DATA.bar", file_basename(".foo ::$DATA.bar"), "Path: '.foo ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext::$DATA.bar", file_basename(".foo .ext::$DATA.bar"), "Path: '.foo .ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.::$DATA.bar", file_basename(".foo.::$DATA.bar"), "Path: '.foo.::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext::$DATA.bar", file_basename(".foo..ext::$DATA.bar"), "Path: '.foo..ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ::$DATA.bar", file_basename(".foo.ext ::$DATA.bar"), "Path: '.foo.ext ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext::$DATA.bar", file_basename(".foo.ext .ext::$DATA.bar"), "Path: '.foo.ext .ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo", file_basename("/.foo"), "Path: '/.foo'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext", file_basename("/.foo.ext"), "Path: '/.foo.ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ", file_basename("/.foo "), "Path: '/.foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext", file_basename("/.foo .ext"), "Path: '/.foo .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.", file_basename("/.foo."), "Path: '/.foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext", file_basename("/.foo..ext"), "Path: '/.foo..ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ", file_basename("/.foo.ext "), "Path: '/.foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext", file_basename("/.foo.ext .ext"), "Path: '/.foo.ext .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ", file_basename("/.foo "), "Path: '/.foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ", file_basename("/.foo.ext "), "Path: '/.foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo  ", file_basename("/.foo  "), "Path: '/.foo  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext ", file_basename("/.foo .ext "), "Path: '/.foo .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo. ", file_basename("/.foo. "), "Path: '/.foo. '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext ", file_basename("/.foo..ext "), "Path: '/.foo..ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext  ", file_basename("/.foo.ext  "), "Path: '/.foo.ext  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext ", file_basename("/.foo.ext .ext "), "Path: '/.foo.ext .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.", file_basename("/.foo."), "Path: '/.foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext.", file_basename("/.foo.ext."), "Path: '/.foo.ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .", file_basename("/.foo ."), "Path: '/.foo .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext.", file_basename("/.foo .ext."), "Path: '/.foo .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..", file_basename("/.foo.."), "Path: '/.foo..'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext.", file_basename("/.foo..ext."), "Path: '/.foo..ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .", file_basename("/.foo.ext ."), "Path: '/.foo.ext .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext.", file_basename("/.foo.ext .ext."), "Path: '/.foo.ext .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.bar", file_basename("/.foo.bar"), "Path: '/.foo.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext.bar", file_basename("/.foo.ext.bar"), "Path: '/.foo.ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .bar", file_basename("/.foo .bar"), "Path: '/.foo .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext.bar", file_basename("/.foo .ext.bar"), "Path: '/.foo .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..bar", file_basename("/.foo..bar"), "Path: '/.foo..bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext.bar", file_basename("/.foo..ext.bar"), "Path: '/.foo..ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .bar", file_basename("/.foo.ext .bar"), "Path: '/.foo.ext .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext.bar", file_basename("/.foo.ext .ext.bar"), "Path: '/.foo.ext .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo::$DATA", file_basename("/.foo::$DATA"), "Path: '/.foo::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext::$DATA", file_basename("/.foo.ext::$DATA"), "Path: '/.foo.ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ::$DATA", file_basename("/.foo ::$DATA"), "Path: '/.foo ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext::$DATA", file_basename("/.foo .ext::$DATA"), "Path: '/.foo .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.::$DATA", file_basename("/.foo.::$DATA"), "Path: '/.foo.::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext::$DATA", file_basename("/.foo..ext::$DATA"), "Path: '/.foo..ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ::$DATA", file_basename("/.foo.ext ::$DATA"), "Path: '/.foo.ext ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext::$DATA", file_basename("/.foo.ext .ext::$DATA"), "Path: '/.foo.ext .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo::$DATA.bar", file_basename("/.foo::$DATA.bar"), "Path: '/.foo::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext::$DATA.bar", file_basename("/.foo.ext::$DATA.bar"), "Path: '/.foo.ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ::$DATA.bar", file_basename("/.foo ::$DATA.bar"), "Path: '/.foo ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext::$DATA.bar", file_basename("/.foo .ext::$DATA.bar"), "Path: '/.foo .ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.::$DATA.bar", file_basename("/.foo.::$DATA.bar"), "Path: '/.foo.::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext::$DATA.bar", file_basename("/.foo..ext::$DATA.bar"), "Path: '/.foo..ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ::$DATA.bar", file_basename("/.foo.ext ::$DATA.bar"), "Path: '/.foo.ext ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext::$DATA.bar", file_basename("/.foo.ext .ext::$DATA.bar"), "Path: '/.foo.ext .ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo", file_basename("bar/.foo"), "Path: 'bar/.foo'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext", file_basename("bar/.foo.ext"), "Path: 'bar/.foo.ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ", file_basename("bar/.foo "), "Path: 'bar/.foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext", file_basename("bar/.foo .ext"), "Path: 'bar/.foo .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.", file_basename("bar/.foo."), "Path: 'bar/.foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext", file_basename("bar/.foo..ext"), "Path: 'bar/.foo..ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ", file_basename("bar/.foo.ext "), "Path: 'bar/.foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext", file_basename("bar/.foo.ext .ext"), "Path: 'bar/.foo.ext .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ", file_basename("bar/.foo "), "Path: 'bar/.foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ", file_basename("bar/.foo.ext "), "Path: 'bar/.foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo  ", file_basename("bar/.foo  "), "Path: 'bar/.foo  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext ", file_basename("bar/.foo .ext "), "Path: 'bar/.foo .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo. ", file_basename("bar/.foo. "), "Path: 'bar/.foo. '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext ", file_basename("bar/.foo..ext "), "Path: 'bar/.foo..ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext  ", file_basename("bar/.foo.ext  "), "Path: 'bar/.foo.ext  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext ", file_basename("bar/.foo.ext .ext "), "Path: 'bar/.foo.ext .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.", file_basename("bar/.foo."), "Path: 'bar/.foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext.", file_basename("bar/.foo.ext."), "Path: 'bar/.foo.ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .", file_basename("bar/.foo ."), "Path: 'bar/.foo .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext.", file_basename("bar/.foo .ext."), "Path: 'bar/.foo .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..", file_basename("bar/.foo.."), "Path: 'bar/.foo..'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext.", file_basename("bar/.foo..ext."), "Path: 'bar/.foo..ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .", file_basename("bar/.foo.ext ."), "Path: 'bar/.foo.ext .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext.", file_basename("bar/.foo.ext .ext."), "Path: 'bar/.foo.ext .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.bar", file_basename("bar/.foo.bar"), "Path: 'bar/.foo.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext.bar", file_basename("bar/.foo.ext.bar"), "Path: 'bar/.foo.ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .bar", file_basename("bar/.foo .bar"), "Path: 'bar/.foo .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext.bar", file_basename("bar/.foo .ext.bar"), "Path: 'bar/.foo .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..bar", file_basename("bar/.foo..bar"), "Path: 'bar/.foo..bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext.bar", file_basename("bar/.foo..ext.bar"), "Path: 'bar/.foo..ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .bar", file_basename("bar/.foo.ext .bar"), "Path: 'bar/.foo.ext .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext.bar", file_basename("bar/.foo.ext .ext.bar"), "Path: 'bar/.foo.ext .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo::$DATA", file_basename("bar/.foo::$DATA"), "Path: 'bar/.foo::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext::$DATA", file_basename("bar/.foo.ext::$DATA"), "Path: 'bar/.foo.ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ::$DATA", file_basename("bar/.foo ::$DATA"), "Path: 'bar/.foo ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext::$DATA", file_basename("bar/.foo .ext::$DATA"), "Path: 'bar/.foo .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.::$DATA", file_basename("bar/.foo.::$DATA"), "Path: 'bar/.foo.::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext::$DATA", file_basename("bar/.foo..ext::$DATA"), "Path: 'bar/.foo..ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ::$DATA", file_basename("bar/.foo.ext ::$DATA"), "Path: 'bar/.foo.ext ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext::$DATA", file_basename("bar/.foo.ext .ext::$DATA"), "Path: 'bar/.foo.ext .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo::$DATA.bar", file_basename("bar/.foo::$DATA.bar"), "Path: 'bar/.foo::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext::$DATA.bar", file_basename("bar/.foo.ext::$DATA.bar"), "Path: 'bar/.foo.ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ::$DATA.bar", file_basename("bar/.foo ::$DATA.bar"), "Path: 'bar/.foo ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext::$DATA.bar", file_basename("bar/.foo .ext::$DATA.bar"), "Path: 'bar/.foo .ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.::$DATA.bar", file_basename("bar/.foo.::$DATA.bar"), "Path: 'bar/.foo.::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext::$DATA.bar", file_basename("bar/.foo..ext::$DATA.bar"), "Path: 'bar/.foo..ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ::$DATA.bar", file_basename("bar/.foo.ext ::$DATA.bar"), "Path: 'bar/.foo.ext ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext::$DATA.bar", file_basename("bar/.foo.ext .ext::$DATA.bar"), "Path: 'bar/.foo.ext .ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo", file_basename("/bar/.foo"), "Path: '/bar/.foo'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext", file_basename("/bar/.foo.ext"), "Path: '/bar/.foo.ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ", file_basename("/bar/.foo "), "Path: '/bar/.foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext", file_basename("/bar/.foo .ext"), "Path: '/bar/.foo .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.", file_basename("/bar/.foo."), "Path: '/bar/.foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext", file_basename("/bar/.foo..ext"), "Path: '/bar/.foo..ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ", file_basename("/bar/.foo.ext "), "Path: '/bar/.foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext", file_basename("/bar/.foo.ext .ext"), "Path: '/bar/.foo.ext .ext'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ", file_basename("/bar/.foo "), "Path: '/bar/.foo '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ", file_basename("/bar/.foo.ext "), "Path: '/bar/.foo.ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo  ", file_basename("/bar/.foo  "), "Path: '/bar/.foo  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext ", file_basename("/bar/.foo .ext "), "Path: '/bar/.foo .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo. ", file_basename("/bar/.foo. "), "Path: '/bar/.foo. '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext ", file_basename("/bar/.foo..ext "), "Path: '/bar/.foo..ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext  ", file_basename("/bar/.foo.ext  "), "Path: '/bar/.foo.ext  '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext ", file_basename("/bar/.foo.ext .ext "), "Path: '/bar/.foo.ext .ext '");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.", file_basename("/bar/.foo."), "Path: '/bar/.foo.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext.", file_basename("/bar/.foo.ext."), "Path: '/bar/.foo.ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .", file_basename("/bar/.foo ."), "Path: '/bar/.foo .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext.", file_basename("/bar/.foo .ext."), "Path: '/bar/.foo .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..", file_basename("/bar/.foo.."), "Path: '/bar/.foo..'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext.", file_basename("/bar/.foo..ext."), "Path: '/bar/.foo..ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .", file_basename("/bar/.foo.ext ."), "Path: '/bar/.foo.ext .'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext.", file_basename("/bar/.foo.ext .ext."), "Path: '/bar/.foo.ext .ext.'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.bar", file_basename("/bar/.foo.bar"), "Path: '/bar/.foo.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext.bar", file_basename("/bar/.foo.ext.bar"), "Path: '/bar/.foo.ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .bar", file_basename("/bar/.foo .bar"), "Path: '/bar/.foo .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext.bar", file_basename("/bar/.foo .ext.bar"), "Path: '/bar/.foo .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..bar", file_basename("/bar/.foo..bar"), "Path: '/bar/.foo..bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext.bar", file_basename("/bar/.foo..ext.bar"), "Path: '/bar/.foo..ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .bar", file_basename("/bar/.foo.ext .bar"), "Path: '/bar/.foo.ext .bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext.bar", file_basename("/bar/.foo.ext .ext.bar"), "Path: '/bar/.foo.ext .ext.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo::$DATA", file_basename("/bar/.foo::$DATA"), "Path: '/bar/.foo::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext::$DATA", file_basename("/bar/.foo.ext::$DATA"), "Path: '/bar/.foo.ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ::$DATA", file_basename("/bar/.foo ::$DATA"), "Path: '/bar/.foo ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext::$DATA", file_basename("/bar/.foo .ext::$DATA"), "Path: '/bar/.foo .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.::$DATA", file_basename("/bar/.foo.::$DATA"), "Path: '/bar/.foo.::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext::$DATA", file_basename("/bar/.foo..ext::$DATA"), "Path: '/bar/.foo..ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ::$DATA", file_basename("/bar/.foo.ext ::$DATA"), "Path: '/bar/.foo.ext ::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext::$DATA", file_basename("/bar/.foo.ext .ext::$DATA"), "Path: '/bar/.foo.ext .ext::$DATA'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo::$DATA.bar", file_basename("/bar/.foo::$DATA.bar"), "Path: '/bar/.foo::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext::$DATA.bar", file_basename("/bar/.foo.ext::$DATA.bar"), "Path: '/bar/.foo.ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ::$DATA.bar", file_basename("/bar/.foo ::$DATA.bar"), "Path: '/bar/.foo ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext::$DATA.bar", file_basename("/bar/.foo .ext::$DATA.bar"), "Path: '/bar/.foo .ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.::$DATA.bar", file_basename("/bar/.foo.::$DATA.bar"), "Path: '/bar/.foo.::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext::$DATA.bar", file_basename("/bar/.foo..ext::$DATA.bar"), "Path: '/bar/.foo..ext::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ::$DATA.bar", file_basename("/bar/.foo.ext ::$DATA.bar"), "Path: '/bar/.foo.ext ::$DATA.bar'");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext::$DATA.bar", file_basename("/bar/.foo.ext .ext::$DATA.bar"), "Path: '/bar/.foo.ext .ext::$DATA.bar'");
}

