#include <stdlib.h>
#include "unity.h"
#include "file.h"

void
test___file_extname(void)
{
char* actual = NULL;

actual = file_extname("foo");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'foo'");
free(actual);
actual = file_extname("foo.ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: 'foo.ext'");
free(actual);
actual = file_extname("foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'foo '");
free(actual);
actual = file_extname("foo .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: 'foo .ext'");
free(actual);
actual = file_extname("foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'foo.'");
free(actual);
actual = file_extname("foo..ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: 'foo..ext'");
free(actual);
actual = file_extname("foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: 'foo.ext '");
free(actual);
actual = file_extname("foo.ext .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: 'foo.ext .ext'");
free(actual);
actual = file_extname("foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'foo '");
free(actual);
actual = file_extname("foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: 'foo.ext '");
free(actual);
actual = file_extname("foo  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'foo  '");
free(actual);
actual = file_extname("foo .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: 'foo .ext '");
free(actual);
actual = file_extname("foo. ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(". ", actual, "Path: 'foo. '");
free(actual);
actual = file_extname("foo..ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: 'foo..ext '");
free(actual);
actual = file_extname("foo.ext  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext  ", actual, "Path: 'foo.ext  '");
free(actual);
actual = file_extname("foo.ext .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: 'foo.ext .ext '");
free(actual);
actual = file_extname("foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'foo.'");
free(actual);
actual = file_extname("foo.ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'foo.ext.'");
free(actual);
actual = file_extname("foo .");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'foo .'");
free(actual);
actual = file_extname("foo .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'foo .ext.'");
free(actual);
actual = file_extname("foo..");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'foo..'");
free(actual);
actual = file_extname("foo..ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'foo..ext.'");
free(actual);
actual = file_extname("foo.ext .");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'foo.ext .'");
free(actual);
actual = file_extname("foo.ext .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'foo.ext .ext.'");
free(actual);
actual = file_extname("foo.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'foo.bar'");
free(actual);
actual = file_extname("foo.ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'foo.ext.bar'");
free(actual);
actual = file_extname("foo .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'foo .bar'");
free(actual);
actual = file_extname("foo .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'foo .ext.bar'");
free(actual);
actual = file_extname("foo..bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'foo..bar'");
free(actual);
actual = file_extname("foo..ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'foo..ext.bar'");
free(actual);
actual = file_extname("foo.ext .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'foo.ext .bar'");
free(actual);
actual = file_extname("foo.ext .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'foo.ext .ext.bar'");
free(actual);
actual = file_extname("foo::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'foo::$DATA'");
free(actual);
actual = file_extname("foo.ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: 'foo.ext::$DATA'");
free(actual);
actual = file_extname("foo ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'foo ::$DATA'");
free(actual);
actual = file_extname("foo .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: 'foo .ext::$DATA'");
free(actual);
actual = file_extname("foo.::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".::$DATA", actual, "Path: 'foo.::$DATA'");
free(actual);
actual = file_extname("foo..ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: 'foo..ext::$DATA'");
free(actual);
actual = file_extname("foo.ext ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ::$DATA", actual, "Path: 'foo.ext ::$DATA'");
free(actual);
actual = file_extname("foo.ext .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: 'foo.ext .ext::$DATA'");
free(actual);
actual = file_extname("foo::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'foo::$DATA.bar'");
free(actual);
actual = file_extname("foo.ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'foo.ext::$DATA.bar'");
free(actual);
actual = file_extname("foo ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'foo ::$DATA.bar'");
free(actual);
actual = file_extname("foo .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'foo .ext::$DATA.bar'");
free(actual);
actual = file_extname("foo.::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'foo.::$DATA.bar'");
free(actual);
actual = file_extname("foo..ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'foo..ext::$DATA.bar'");
free(actual);
actual = file_extname("foo.ext ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'foo.ext ::$DATA.bar'");
free(actual);
actual = file_extname("foo.ext .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'foo.ext .ext::$DATA.bar'");
free(actual);
actual = file_extname("//foo");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '//foo'");
free(actual);
actual = file_extname("//foo.ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: '//foo.ext'");
free(actual);
actual = file_extname("//foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '//foo '");
free(actual);
actual = file_extname("//foo .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: '//foo .ext'");
free(actual);
actual = file_extname("//foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '//foo.'");
free(actual);
actual = file_extname("//foo..ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: '//foo..ext'");
free(actual);
actual = file_extname("//foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: '//foo.ext '");
free(actual);
actual = file_extname("//foo.ext .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: '//foo.ext .ext'");
free(actual);
actual = file_extname("//foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '//foo '");
free(actual);
actual = file_extname("//foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: '//foo.ext '");
free(actual);
actual = file_extname("//foo  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '//foo  '");
free(actual);
actual = file_extname("//foo .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: '//foo .ext '");
free(actual);
actual = file_extname("//foo. ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(". ", actual, "Path: '//foo. '");
free(actual);
actual = file_extname("//foo..ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: '//foo..ext '");
free(actual);
actual = file_extname("//foo.ext  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext  ", actual, "Path: '//foo.ext  '");
free(actual);
actual = file_extname("//foo.ext .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: '//foo.ext .ext '");
free(actual);
actual = file_extname("//foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '//foo.'");
free(actual);
actual = file_extname("//foo.ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '//foo.ext.'");
free(actual);
actual = file_extname("//foo .");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '//foo .'");
free(actual);
actual = file_extname("//foo .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '//foo .ext.'");
free(actual);
actual = file_extname("//foo..");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '//foo..'");
free(actual);
actual = file_extname("//foo..ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '//foo..ext.'");
free(actual);
actual = file_extname("//foo.ext .");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '//foo.ext .'");
free(actual);
actual = file_extname("//foo.ext .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '//foo.ext .ext.'");
free(actual);
actual = file_extname("//foo.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '//foo.bar'");
free(actual);
actual = file_extname("//foo.ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '//foo.ext.bar'");
free(actual);
actual = file_extname("//foo .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '//foo .bar'");
free(actual);
actual = file_extname("//foo .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '//foo .ext.bar'");
free(actual);
actual = file_extname("//foo..bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '//foo..bar'");
free(actual);
actual = file_extname("//foo..ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '//foo..ext.bar'");
free(actual);
actual = file_extname("//foo.ext .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '//foo.ext .bar'");
free(actual);
actual = file_extname("//foo.ext .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '//foo.ext .ext.bar'");
free(actual);
actual = file_extname("//foo::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '//foo::$DATA'");
free(actual);
actual = file_extname("//foo.ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: '//foo.ext::$DATA'");
free(actual);
actual = file_extname("//foo ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '//foo ::$DATA'");
free(actual);
actual = file_extname("//foo .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: '//foo .ext::$DATA'");
free(actual);
actual = file_extname("//foo.::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".::$DATA", actual, "Path: '//foo.::$DATA'");
free(actual);
actual = file_extname("//foo..ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: '//foo..ext::$DATA'");
free(actual);
actual = file_extname("//foo.ext ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ::$DATA", actual, "Path: '//foo.ext ::$DATA'");
free(actual);
actual = file_extname("//foo.ext .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: '//foo.ext .ext::$DATA'");
free(actual);
actual = file_extname("//foo::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '//foo::$DATA.bar'");
free(actual);
actual = file_extname("//foo.ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '//foo.ext::$DATA.bar'");
free(actual);
actual = file_extname("//foo ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '//foo ::$DATA.bar'");
free(actual);
actual = file_extname("//foo .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '//foo .ext::$DATA.bar'");
free(actual);
actual = file_extname("//foo.::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '//foo.::$DATA.bar'");
free(actual);
actual = file_extname("//foo..ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '//foo..ext::$DATA.bar'");
free(actual);
actual = file_extname("//foo.ext ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '//foo.ext ::$DATA.bar'");
free(actual);
actual = file_extname("//foo.ext .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '//foo.ext .ext::$DATA.bar'");
free(actual);
actual = file_extname("/foo");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/foo'");
free(actual);
actual = file_extname("/foo.ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: '/foo.ext'");
free(actual);
actual = file_extname("/foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/foo '");
free(actual);
actual = file_extname("/foo .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: '/foo .ext'");
free(actual);
actual = file_extname("/foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/foo.'");
free(actual);
actual = file_extname("/foo..ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: '/foo..ext'");
free(actual);
actual = file_extname("/foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: '/foo.ext '");
free(actual);
actual = file_extname("/foo.ext .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: '/foo.ext .ext'");
free(actual);
actual = file_extname("/foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/foo '");
free(actual);
actual = file_extname("/foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: '/foo.ext '");
free(actual);
actual = file_extname("/foo  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/foo  '");
free(actual);
actual = file_extname("/foo .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: '/foo .ext '");
free(actual);
actual = file_extname("/foo. ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(". ", actual, "Path: '/foo. '");
free(actual);
actual = file_extname("/foo..ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: '/foo..ext '");
free(actual);
actual = file_extname("/foo.ext  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext  ", actual, "Path: '/foo.ext  '");
free(actual);
actual = file_extname("/foo.ext .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: '/foo.ext .ext '");
free(actual);
actual = file_extname("/foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/foo.'");
free(actual);
actual = file_extname("/foo.ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/foo.ext.'");
free(actual);
actual = file_extname("/foo .");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/foo .'");
free(actual);
actual = file_extname("/foo .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/foo .ext.'");
free(actual);
actual = file_extname("/foo..");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/foo..'");
free(actual);
actual = file_extname("/foo..ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/foo..ext.'");
free(actual);
actual = file_extname("/foo.ext .");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/foo.ext .'");
free(actual);
actual = file_extname("/foo.ext .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/foo.ext .ext.'");
free(actual);
actual = file_extname("/foo.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/foo.bar'");
free(actual);
actual = file_extname("/foo.ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/foo.ext.bar'");
free(actual);
actual = file_extname("/foo .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/foo .bar'");
free(actual);
actual = file_extname("/foo .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/foo .ext.bar'");
free(actual);
actual = file_extname("/foo..bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/foo..bar'");
free(actual);
actual = file_extname("/foo..ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/foo..ext.bar'");
free(actual);
actual = file_extname("/foo.ext .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/foo.ext .bar'");
free(actual);
actual = file_extname("/foo.ext .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/foo.ext .ext.bar'");
free(actual);
actual = file_extname("/foo::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/foo::$DATA'");
free(actual);
actual = file_extname("/foo.ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: '/foo.ext::$DATA'");
free(actual);
actual = file_extname("/foo ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/foo ::$DATA'");
free(actual);
actual = file_extname("/foo .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: '/foo .ext::$DATA'");
free(actual);
actual = file_extname("/foo.::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".::$DATA", actual, "Path: '/foo.::$DATA'");
free(actual);
actual = file_extname("/foo..ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: '/foo..ext::$DATA'");
free(actual);
actual = file_extname("/foo.ext ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ::$DATA", actual, "Path: '/foo.ext ::$DATA'");
free(actual);
actual = file_extname("/foo.ext .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: '/foo.ext .ext::$DATA'");
free(actual);
actual = file_extname("/foo::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/foo::$DATA.bar'");
free(actual);
actual = file_extname("/foo.ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/foo.ext::$DATA.bar'");
free(actual);
actual = file_extname("/foo ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/foo ::$DATA.bar'");
free(actual);
actual = file_extname("/foo .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/foo .ext::$DATA.bar'");
free(actual);
actual = file_extname("/foo.::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/foo.::$DATA.bar'");
free(actual);
actual = file_extname("/foo..ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/foo..ext::$DATA.bar'");
free(actual);
actual = file_extname("/foo.ext ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/foo.ext ::$DATA.bar'");
free(actual);
actual = file_extname("/foo.ext .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/foo.ext .ext::$DATA.bar'");
free(actual);
actual = file_extname(".foo");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '.foo'");
free(actual);
actual = file_extname(".foo.ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: '.foo.ext'");
free(actual);
actual = file_extname(".foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '.foo '");
free(actual);
actual = file_extname(".foo .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: '.foo .ext'");
free(actual);
actual = file_extname(".foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '.foo.'");
free(actual);
actual = file_extname(".foo..ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: '.foo..ext'");
free(actual);
actual = file_extname(".foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: '.foo.ext '");
free(actual);
actual = file_extname(".foo.ext .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: '.foo.ext .ext'");
free(actual);
actual = file_extname(".foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '.foo '");
free(actual);
actual = file_extname(".foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: '.foo.ext '");
free(actual);
actual = file_extname(".foo  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '.foo  '");
free(actual);
actual = file_extname(".foo .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: '.foo .ext '");
free(actual);
actual = file_extname(".foo. ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(". ", actual, "Path: '.foo. '");
free(actual);
actual = file_extname(".foo..ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: '.foo..ext '");
free(actual);
actual = file_extname(".foo.ext  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext  ", actual, "Path: '.foo.ext  '");
free(actual);
actual = file_extname(".foo.ext .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: '.foo.ext .ext '");
free(actual);
actual = file_extname(".foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '.foo.'");
free(actual);
actual = file_extname(".foo.ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '.foo.ext.'");
free(actual);
actual = file_extname(".foo .");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '.foo .'");
free(actual);
actual = file_extname(".foo .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '.foo .ext.'");
free(actual);
actual = file_extname(".foo..");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '.foo..'");
free(actual);
actual = file_extname(".foo..ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '.foo..ext.'");
free(actual);
actual = file_extname(".foo.ext .");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '.foo.ext .'");
free(actual);
actual = file_extname(".foo.ext .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '.foo.ext .ext.'");
free(actual);
actual = file_extname(".foo.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '.foo.bar'");
free(actual);
actual = file_extname(".foo.ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '.foo.ext.bar'");
free(actual);
actual = file_extname(".foo .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '.foo .bar'");
free(actual);
actual = file_extname(".foo .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '.foo .ext.bar'");
free(actual);
actual = file_extname(".foo..bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '.foo..bar'");
free(actual);
actual = file_extname(".foo..ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '.foo..ext.bar'");
free(actual);
actual = file_extname(".foo.ext .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '.foo.ext .bar'");
free(actual);
actual = file_extname(".foo.ext .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '.foo.ext .ext.bar'");
free(actual);
actual = file_extname(".foo::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '.foo::$DATA'");
free(actual);
actual = file_extname(".foo.ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: '.foo.ext::$DATA'");
free(actual);
actual = file_extname(".foo ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '.foo ::$DATA'");
free(actual);
actual = file_extname(".foo .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: '.foo .ext::$DATA'");
free(actual);
actual = file_extname(".foo.::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".::$DATA", actual, "Path: '.foo.::$DATA'");
free(actual);
actual = file_extname(".foo..ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: '.foo..ext::$DATA'");
free(actual);
actual = file_extname(".foo.ext ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ::$DATA", actual, "Path: '.foo.ext ::$DATA'");
free(actual);
actual = file_extname(".foo.ext .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: '.foo.ext .ext::$DATA'");
free(actual);
actual = file_extname(".foo::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '.foo::$DATA.bar'");
free(actual);
actual = file_extname(".foo.ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '.foo.ext::$DATA.bar'");
free(actual);
actual = file_extname(".foo ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '.foo ::$DATA.bar'");
free(actual);
actual = file_extname(".foo .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '.foo .ext::$DATA.bar'");
free(actual);
actual = file_extname(".foo.::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '.foo.::$DATA.bar'");
free(actual);
actual = file_extname(".foo..ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '.foo..ext::$DATA.bar'");
free(actual);
actual = file_extname(".foo.ext ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '.foo.ext ::$DATA.bar'");
free(actual);
actual = file_extname(".foo.ext .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '.foo.ext .ext::$DATA.bar'");
free(actual);
actual = file_extname("/.foo");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/.foo'");
free(actual);
actual = file_extname("/.foo.ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: '/.foo.ext'");
free(actual);
actual = file_extname("/.foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/.foo '");
free(actual);
actual = file_extname("/.foo .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: '/.foo .ext'");
free(actual);
actual = file_extname("/.foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/.foo.'");
free(actual);
actual = file_extname("/.foo..ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: '/.foo..ext'");
free(actual);
actual = file_extname("/.foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: '/.foo.ext '");
free(actual);
actual = file_extname("/.foo.ext .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: '/.foo.ext .ext'");
free(actual);
actual = file_extname("/.foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/.foo '");
free(actual);
actual = file_extname("/.foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: '/.foo.ext '");
free(actual);
actual = file_extname("/.foo  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/.foo  '");
free(actual);
actual = file_extname("/.foo .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: '/.foo .ext '");
free(actual);
actual = file_extname("/.foo. ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(". ", actual, "Path: '/.foo. '");
free(actual);
actual = file_extname("/.foo..ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: '/.foo..ext '");
free(actual);
actual = file_extname("/.foo.ext  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext  ", actual, "Path: '/.foo.ext  '");
free(actual);
actual = file_extname("/.foo.ext .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: '/.foo.ext .ext '");
free(actual);
actual = file_extname("/.foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/.foo.'");
free(actual);
actual = file_extname("/.foo.ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/.foo.ext.'");
free(actual);
actual = file_extname("/.foo .");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/.foo .'");
free(actual);
actual = file_extname("/.foo .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/.foo .ext.'");
free(actual);
actual = file_extname("/.foo..");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/.foo..'");
free(actual);
actual = file_extname("/.foo..ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/.foo..ext.'");
free(actual);
actual = file_extname("/.foo.ext .");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/.foo.ext .'");
free(actual);
actual = file_extname("/.foo.ext .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/.foo.ext .ext.'");
free(actual);
actual = file_extname("/.foo.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/.foo.bar'");
free(actual);
actual = file_extname("/.foo.ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/.foo.ext.bar'");
free(actual);
actual = file_extname("/.foo .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/.foo .bar'");
free(actual);
actual = file_extname("/.foo .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/.foo .ext.bar'");
free(actual);
actual = file_extname("/.foo..bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/.foo..bar'");
free(actual);
actual = file_extname("/.foo..ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/.foo..ext.bar'");
free(actual);
actual = file_extname("/.foo.ext .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/.foo.ext .bar'");
free(actual);
actual = file_extname("/.foo.ext .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/.foo.ext .ext.bar'");
free(actual);
actual = file_extname("/.foo::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/.foo::$DATA'");
free(actual);
actual = file_extname("/.foo.ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: '/.foo.ext::$DATA'");
free(actual);
actual = file_extname("/.foo ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/.foo ::$DATA'");
free(actual);
actual = file_extname("/.foo .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: '/.foo .ext::$DATA'");
free(actual);
actual = file_extname("/.foo.::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".::$DATA", actual, "Path: '/.foo.::$DATA'");
free(actual);
actual = file_extname("/.foo..ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: '/.foo..ext::$DATA'");
free(actual);
actual = file_extname("/.foo.ext ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ::$DATA", actual, "Path: '/.foo.ext ::$DATA'");
free(actual);
actual = file_extname("/.foo.ext .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: '/.foo.ext .ext::$DATA'");
free(actual);
actual = file_extname("/.foo::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/.foo::$DATA.bar'");
free(actual);
actual = file_extname("/.foo.ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/.foo.ext::$DATA.bar'");
free(actual);
actual = file_extname("/.foo ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/.foo ::$DATA.bar'");
free(actual);
actual = file_extname("/.foo .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/.foo .ext::$DATA.bar'");
free(actual);
actual = file_extname("/.foo.::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/.foo.::$DATA.bar'");
free(actual);
actual = file_extname("/.foo..ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/.foo..ext::$DATA.bar'");
free(actual);
actual = file_extname("/.foo.ext ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/.foo.ext ::$DATA.bar'");
free(actual);
actual = file_extname("/.foo.ext .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/.foo.ext .ext::$DATA.bar'");
free(actual);
actual = file_extname("bar/.foo");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'bar/.foo'");
free(actual);
actual = file_extname("bar/.foo.ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: 'bar/.foo.ext'");
free(actual);
actual = file_extname("bar/.foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'bar/.foo '");
free(actual);
actual = file_extname("bar/.foo .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: 'bar/.foo .ext'");
free(actual);
actual = file_extname("bar/.foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'bar/.foo.'");
free(actual);
actual = file_extname("bar/.foo..ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: 'bar/.foo..ext'");
free(actual);
actual = file_extname("bar/.foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: 'bar/.foo.ext '");
free(actual);
actual = file_extname("bar/.foo.ext .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: 'bar/.foo.ext .ext'");
free(actual);
actual = file_extname("bar/.foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'bar/.foo '");
free(actual);
actual = file_extname("bar/.foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: 'bar/.foo.ext '");
free(actual);
actual = file_extname("bar/.foo  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'bar/.foo  '");
free(actual);
actual = file_extname("bar/.foo .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: 'bar/.foo .ext '");
free(actual);
actual = file_extname("bar/.foo. ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(". ", actual, "Path: 'bar/.foo. '");
free(actual);
actual = file_extname("bar/.foo..ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: 'bar/.foo..ext '");
free(actual);
actual = file_extname("bar/.foo.ext  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext  ", actual, "Path: 'bar/.foo.ext  '");
free(actual);
actual = file_extname("bar/.foo.ext .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: 'bar/.foo.ext .ext '");
free(actual);
actual = file_extname("bar/.foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'bar/.foo.'");
free(actual);
actual = file_extname("bar/.foo.ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'bar/.foo.ext.'");
free(actual);
actual = file_extname("bar/.foo .");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'bar/.foo .'");
free(actual);
actual = file_extname("bar/.foo .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'bar/.foo .ext.'");
free(actual);
actual = file_extname("bar/.foo..");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'bar/.foo..'");
free(actual);
actual = file_extname("bar/.foo..ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'bar/.foo..ext.'");
free(actual);
actual = file_extname("bar/.foo.ext .");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'bar/.foo.ext .'");
free(actual);
actual = file_extname("bar/.foo.ext .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'bar/.foo.ext .ext.'");
free(actual);
actual = file_extname("bar/.foo.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'bar/.foo.bar'");
free(actual);
actual = file_extname("bar/.foo.ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'bar/.foo.ext.bar'");
free(actual);
actual = file_extname("bar/.foo .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'bar/.foo .bar'");
free(actual);
actual = file_extname("bar/.foo .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'bar/.foo .ext.bar'");
free(actual);
actual = file_extname("bar/.foo..bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'bar/.foo..bar'");
free(actual);
actual = file_extname("bar/.foo..ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'bar/.foo..ext.bar'");
free(actual);
actual = file_extname("bar/.foo.ext .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'bar/.foo.ext .bar'");
free(actual);
actual = file_extname("bar/.foo.ext .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'bar/.foo.ext .ext.bar'");
free(actual);
actual = file_extname("bar/.foo::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'bar/.foo::$DATA'");
free(actual);
actual = file_extname("bar/.foo.ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: 'bar/.foo.ext::$DATA'");
free(actual);
actual = file_extname("bar/.foo ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: 'bar/.foo ::$DATA'");
free(actual);
actual = file_extname("bar/.foo .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: 'bar/.foo .ext::$DATA'");
free(actual);
actual = file_extname("bar/.foo.::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".::$DATA", actual, "Path: 'bar/.foo.::$DATA'");
free(actual);
actual = file_extname("bar/.foo..ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: 'bar/.foo..ext::$DATA'");
free(actual);
actual = file_extname("bar/.foo.ext ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ::$DATA", actual, "Path: 'bar/.foo.ext ::$DATA'");
free(actual);
actual = file_extname("bar/.foo.ext .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: 'bar/.foo.ext .ext::$DATA'");
free(actual);
actual = file_extname("bar/.foo::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'bar/.foo::$DATA.bar'");
free(actual);
actual = file_extname("bar/.foo.ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'bar/.foo.ext::$DATA.bar'");
free(actual);
actual = file_extname("bar/.foo ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'bar/.foo ::$DATA.bar'");
free(actual);
actual = file_extname("bar/.foo .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'bar/.foo .ext::$DATA.bar'");
free(actual);
actual = file_extname("bar/.foo.::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'bar/.foo.::$DATA.bar'");
free(actual);
actual = file_extname("bar/.foo..ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'bar/.foo..ext::$DATA.bar'");
free(actual);
actual = file_extname("bar/.foo.ext ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'bar/.foo.ext ::$DATA.bar'");
free(actual);
actual = file_extname("bar/.foo.ext .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: 'bar/.foo.ext .ext::$DATA.bar'");
free(actual);
actual = file_extname("/bar/.foo");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/bar/.foo'");
free(actual);
actual = file_extname("/bar/.foo.ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: '/bar/.foo.ext'");
free(actual);
actual = file_extname("/bar/.foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/bar/.foo '");
free(actual);
actual = file_extname("/bar/.foo .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: '/bar/.foo .ext'");
free(actual);
actual = file_extname("/bar/.foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/bar/.foo.'");
free(actual);
actual = file_extname("/bar/.foo..ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: '/bar/.foo..ext'");
free(actual);
actual = file_extname("/bar/.foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: '/bar/.foo.ext '");
free(actual);
actual = file_extname("/bar/.foo.ext .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext", actual, "Path: '/bar/.foo.ext .ext'");
free(actual);
actual = file_extname("/bar/.foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/bar/.foo '");
free(actual);
actual = file_extname("/bar/.foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: '/bar/.foo.ext '");
free(actual);
actual = file_extname("/bar/.foo  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/bar/.foo  '");
free(actual);
actual = file_extname("/bar/.foo .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: '/bar/.foo .ext '");
free(actual);
actual = file_extname("/bar/.foo. ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(". ", actual, "Path: '/bar/.foo. '");
free(actual);
actual = file_extname("/bar/.foo..ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: '/bar/.foo..ext '");
free(actual);
actual = file_extname("/bar/.foo.ext  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext  ", actual, "Path: '/bar/.foo.ext  '");
free(actual);
actual = file_extname("/bar/.foo.ext .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ", actual, "Path: '/bar/.foo.ext .ext '");
free(actual);
actual = file_extname("/bar/.foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/bar/.foo.'");
free(actual);
actual = file_extname("/bar/.foo.ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/bar/.foo.ext.'");
free(actual);
actual = file_extname("/bar/.foo .");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/bar/.foo .'");
free(actual);
actual = file_extname("/bar/.foo .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/bar/.foo .ext.'");
free(actual);
actual = file_extname("/bar/.foo..");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/bar/.foo..'");
free(actual);
actual = file_extname("/bar/.foo..ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/bar/.foo..ext.'");
free(actual);
actual = file_extname("/bar/.foo.ext .");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/bar/.foo.ext .'");
free(actual);
actual = file_extname("/bar/.foo.ext .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/bar/.foo.ext .ext.'");
free(actual);
actual = file_extname("/bar/.foo.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/bar/.foo.bar'");
free(actual);
actual = file_extname("/bar/.foo.ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/bar/.foo.ext.bar'");
free(actual);
actual = file_extname("/bar/.foo .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/bar/.foo .bar'");
free(actual);
actual = file_extname("/bar/.foo .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/bar/.foo .ext.bar'");
free(actual);
actual = file_extname("/bar/.foo..bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/bar/.foo..bar'");
free(actual);
actual = file_extname("/bar/.foo..ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/bar/.foo..ext.bar'");
free(actual);
actual = file_extname("/bar/.foo.ext .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/bar/.foo.ext .bar'");
free(actual);
actual = file_extname("/bar/.foo.ext .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/bar/.foo.ext .ext.bar'");
free(actual);
actual = file_extname("/bar/.foo::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/bar/.foo::$DATA'");
free(actual);
actual = file_extname("/bar/.foo.ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: '/bar/.foo.ext::$DATA'");
free(actual);
actual = file_extname("/bar/.foo ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("", actual, "Path: '/bar/.foo ::$DATA'");
free(actual);
actual = file_extname("/bar/.foo .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: '/bar/.foo .ext::$DATA'");
free(actual);
actual = file_extname("/bar/.foo.::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".::$DATA", actual, "Path: '/bar/.foo.::$DATA'");
free(actual);
actual = file_extname("/bar/.foo..ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: '/bar/.foo..ext::$DATA'");
free(actual);
actual = file_extname("/bar/.foo.ext ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext ::$DATA", actual, "Path: '/bar/.foo.ext ::$DATA'");
free(actual);
actual = file_extname("/bar/.foo.ext .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".ext::$DATA", actual, "Path: '/bar/.foo.ext .ext::$DATA'");
free(actual);
actual = file_extname("/bar/.foo::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/bar/.foo::$DATA.bar'");
free(actual);
actual = file_extname("/bar/.foo.ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/bar/.foo.ext::$DATA.bar'");
free(actual);
actual = file_extname("/bar/.foo ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/bar/.foo ::$DATA.bar'");
free(actual);
actual = file_extname("/bar/.foo .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/bar/.foo .ext::$DATA.bar'");
free(actual);
actual = file_extname("/bar/.foo.::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/bar/.foo.::$DATA.bar'");
free(actual);
actual = file_extname("/bar/.foo..ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/bar/.foo..ext::$DATA.bar'");
free(actual);
actual = file_extname("/bar/.foo.ext ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/bar/.foo.ext ::$DATA.bar'");
free(actual);
actual = file_extname("/bar/.foo.ext .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".bar", actual, "Path: '/bar/.foo.ext .ext::$DATA.bar'");
free(actual);
}

void
test___file_basename(void)
{
char* actual = NULL;

actual = file_basename("foo");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo", actual, "Path: 'foo'");
free(actual);
actual = file_basename("foo.ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext", actual, "Path: 'foo.ext'");
free(actual);
actual = file_basename("foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo ", actual, "Path: 'foo '");
free(actual);
actual = file_basename("foo .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext", actual, "Path: 'foo .ext'");
free(actual);
actual = file_basename("foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.", actual, "Path: 'foo.'");
free(actual);
actual = file_basename("foo..ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext", actual, "Path: 'foo..ext'");
free(actual);
actual = file_basename("foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext ", actual, "Path: 'foo.ext '");
free(actual);
actual = file_basename("foo.ext .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext", actual, "Path: 'foo.ext .ext'");
free(actual);
actual = file_basename("foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo ", actual, "Path: 'foo '");
free(actual);
actual = file_basename("foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext ", actual, "Path: 'foo.ext '");
free(actual);
actual = file_basename("foo  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo  ", actual, "Path: 'foo  '");
free(actual);
actual = file_basename("foo .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext ", actual, "Path: 'foo .ext '");
free(actual);
actual = file_basename("foo. ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo. ", actual, "Path: 'foo. '");
free(actual);
actual = file_basename("foo..ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext ", actual, "Path: 'foo..ext '");
free(actual);
actual = file_basename("foo.ext  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext  ", actual, "Path: 'foo.ext  '");
free(actual);
actual = file_basename("foo.ext .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext ", actual, "Path: 'foo.ext .ext '");
free(actual);
actual = file_basename("foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.", actual, "Path: 'foo.'");
free(actual);
actual = file_basename("foo.ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext.", actual, "Path: 'foo.ext.'");
free(actual);
actual = file_basename("foo .");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .", actual, "Path: 'foo .'");
free(actual);
actual = file_basename("foo .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext.", actual, "Path: 'foo .ext.'");
free(actual);
actual = file_basename("foo..");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..", actual, "Path: 'foo..'");
free(actual);
actual = file_basename("foo..ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext.", actual, "Path: 'foo..ext.'");
free(actual);
actual = file_basename("foo.ext .");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .", actual, "Path: 'foo.ext .'");
free(actual);
actual = file_basename("foo.ext .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext.", actual, "Path: 'foo.ext .ext.'");
free(actual);
actual = file_basename("foo.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.bar", actual, "Path: 'foo.bar'");
free(actual);
actual = file_basename("foo.ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext.bar", actual, "Path: 'foo.ext.bar'");
free(actual);
actual = file_basename("foo .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .bar", actual, "Path: 'foo .bar'");
free(actual);
actual = file_basename("foo .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext.bar", actual, "Path: 'foo .ext.bar'");
free(actual);
actual = file_basename("foo..bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..bar", actual, "Path: 'foo..bar'");
free(actual);
actual = file_basename("foo..ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext.bar", actual, "Path: 'foo..ext.bar'");
free(actual);
actual = file_basename("foo.ext .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .bar", actual, "Path: 'foo.ext .bar'");
free(actual);
actual = file_basename("foo.ext .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext.bar", actual, "Path: 'foo.ext .ext.bar'");
free(actual);
actual = file_basename("foo::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo::$DATA", actual, "Path: 'foo::$DATA'");
free(actual);
actual = file_basename("foo.ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext::$DATA", actual, "Path: 'foo.ext::$DATA'");
free(actual);
actual = file_basename("foo ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo ::$DATA", actual, "Path: 'foo ::$DATA'");
free(actual);
actual = file_basename("foo .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext::$DATA", actual, "Path: 'foo .ext::$DATA'");
free(actual);
actual = file_basename("foo.::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.::$DATA", actual, "Path: 'foo.::$DATA'");
free(actual);
actual = file_basename("foo..ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext::$DATA", actual, "Path: 'foo..ext::$DATA'");
free(actual);
actual = file_basename("foo.ext ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext ::$DATA", actual, "Path: 'foo.ext ::$DATA'");
free(actual);
actual = file_basename("foo.ext .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext::$DATA", actual, "Path: 'foo.ext .ext::$DATA'");
free(actual);
actual = file_basename("foo::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo::$DATA.bar", actual, "Path: 'foo::$DATA.bar'");
free(actual);
actual = file_basename("foo.ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext::$DATA.bar", actual, "Path: 'foo.ext::$DATA.bar'");
free(actual);
actual = file_basename("foo ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo ::$DATA.bar", actual, "Path: 'foo ::$DATA.bar'");
free(actual);
actual = file_basename("foo .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext::$DATA.bar", actual, "Path: 'foo .ext::$DATA.bar'");
free(actual);
actual = file_basename("foo.::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.::$DATA.bar", actual, "Path: 'foo.::$DATA.bar'");
free(actual);
actual = file_basename("foo..ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext::$DATA.bar", actual, "Path: 'foo..ext::$DATA.bar'");
free(actual);
actual = file_basename("foo.ext ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext ::$DATA.bar", actual, "Path: 'foo.ext ::$DATA.bar'");
free(actual);
actual = file_basename("foo.ext .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext::$DATA.bar", actual, "Path: 'foo.ext .ext::$DATA.bar'");
free(actual);
actual = file_basename("//foo");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo", actual, "Path: '//foo'");
free(actual);
actual = file_basename("//foo.ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext", actual, "Path: '//foo.ext'");
free(actual);
actual = file_basename("//foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo ", actual, "Path: '//foo '");
free(actual);
actual = file_basename("//foo .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext", actual, "Path: '//foo .ext'");
free(actual);
actual = file_basename("//foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.", actual, "Path: '//foo.'");
free(actual);
actual = file_basename("//foo..ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext", actual, "Path: '//foo..ext'");
free(actual);
actual = file_basename("//foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext ", actual, "Path: '//foo.ext '");
free(actual);
actual = file_basename("//foo.ext .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext", actual, "Path: '//foo.ext .ext'");
free(actual);
actual = file_basename("//foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo ", actual, "Path: '//foo '");
free(actual);
actual = file_basename("//foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext ", actual, "Path: '//foo.ext '");
free(actual);
actual = file_basename("//foo  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo  ", actual, "Path: '//foo  '");
free(actual);
actual = file_basename("//foo .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext ", actual, "Path: '//foo .ext '");
free(actual);
actual = file_basename("//foo. ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo. ", actual, "Path: '//foo. '");
free(actual);
actual = file_basename("//foo..ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext ", actual, "Path: '//foo..ext '");
free(actual);
actual = file_basename("//foo.ext  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext  ", actual, "Path: '//foo.ext  '");
free(actual);
actual = file_basename("//foo.ext .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext ", actual, "Path: '//foo.ext .ext '");
free(actual);
actual = file_basename("//foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.", actual, "Path: '//foo.'");
free(actual);
actual = file_basename("//foo.ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext.", actual, "Path: '//foo.ext.'");
free(actual);
actual = file_basename("//foo .");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .", actual, "Path: '//foo .'");
free(actual);
actual = file_basename("//foo .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext.", actual, "Path: '//foo .ext.'");
free(actual);
actual = file_basename("//foo..");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..", actual, "Path: '//foo..'");
free(actual);
actual = file_basename("//foo..ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext.", actual, "Path: '//foo..ext.'");
free(actual);
actual = file_basename("//foo.ext .");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .", actual, "Path: '//foo.ext .'");
free(actual);
actual = file_basename("//foo.ext .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext.", actual, "Path: '//foo.ext .ext.'");
free(actual);
actual = file_basename("//foo.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.bar", actual, "Path: '//foo.bar'");
free(actual);
actual = file_basename("//foo.ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext.bar", actual, "Path: '//foo.ext.bar'");
free(actual);
actual = file_basename("//foo .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .bar", actual, "Path: '//foo .bar'");
free(actual);
actual = file_basename("//foo .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext.bar", actual, "Path: '//foo .ext.bar'");
free(actual);
actual = file_basename("//foo..bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..bar", actual, "Path: '//foo..bar'");
free(actual);
actual = file_basename("//foo..ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext.bar", actual, "Path: '//foo..ext.bar'");
free(actual);
actual = file_basename("//foo.ext .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .bar", actual, "Path: '//foo.ext .bar'");
free(actual);
actual = file_basename("//foo.ext .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext.bar", actual, "Path: '//foo.ext .ext.bar'");
free(actual);
actual = file_basename("//foo::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo::$DATA", actual, "Path: '//foo::$DATA'");
free(actual);
actual = file_basename("//foo.ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext::$DATA", actual, "Path: '//foo.ext::$DATA'");
free(actual);
actual = file_basename("//foo ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo ::$DATA", actual, "Path: '//foo ::$DATA'");
free(actual);
actual = file_basename("//foo .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext::$DATA", actual, "Path: '//foo .ext::$DATA'");
free(actual);
actual = file_basename("//foo.::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.::$DATA", actual, "Path: '//foo.::$DATA'");
free(actual);
actual = file_basename("//foo..ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext::$DATA", actual, "Path: '//foo..ext::$DATA'");
free(actual);
actual = file_basename("//foo.ext ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext ::$DATA", actual, "Path: '//foo.ext ::$DATA'");
free(actual);
actual = file_basename("//foo.ext .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext::$DATA", actual, "Path: '//foo.ext .ext::$DATA'");
free(actual);
actual = file_basename("//foo::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo::$DATA.bar", actual, "Path: '//foo::$DATA.bar'");
free(actual);
actual = file_basename("//foo.ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext::$DATA.bar", actual, "Path: '//foo.ext::$DATA.bar'");
free(actual);
actual = file_basename("//foo ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo ::$DATA.bar", actual, "Path: '//foo ::$DATA.bar'");
free(actual);
actual = file_basename("//foo .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext::$DATA.bar", actual, "Path: '//foo .ext::$DATA.bar'");
free(actual);
actual = file_basename("//foo.::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.::$DATA.bar", actual, "Path: '//foo.::$DATA.bar'");
free(actual);
actual = file_basename("//foo..ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext::$DATA.bar", actual, "Path: '//foo..ext::$DATA.bar'");
free(actual);
actual = file_basename("//foo.ext ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext ::$DATA.bar", actual, "Path: '//foo.ext ::$DATA.bar'");
free(actual);
actual = file_basename("//foo.ext .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext::$DATA.bar", actual, "Path: '//foo.ext .ext::$DATA.bar'");
free(actual);
actual = file_basename("/foo");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo", actual, "Path: '/foo'");
free(actual);
actual = file_basename("/foo.ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext", actual, "Path: '/foo.ext'");
free(actual);
actual = file_basename("/foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo ", actual, "Path: '/foo '");
free(actual);
actual = file_basename("/foo .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext", actual, "Path: '/foo .ext'");
free(actual);
actual = file_basename("/foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.", actual, "Path: '/foo.'");
free(actual);
actual = file_basename("/foo..ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext", actual, "Path: '/foo..ext'");
free(actual);
actual = file_basename("/foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext ", actual, "Path: '/foo.ext '");
free(actual);
actual = file_basename("/foo.ext .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext", actual, "Path: '/foo.ext .ext'");
free(actual);
actual = file_basename("/foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo ", actual, "Path: '/foo '");
free(actual);
actual = file_basename("/foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext ", actual, "Path: '/foo.ext '");
free(actual);
actual = file_basename("/foo  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo  ", actual, "Path: '/foo  '");
free(actual);
actual = file_basename("/foo .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext ", actual, "Path: '/foo .ext '");
free(actual);
actual = file_basename("/foo. ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo. ", actual, "Path: '/foo. '");
free(actual);
actual = file_basename("/foo..ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext ", actual, "Path: '/foo..ext '");
free(actual);
actual = file_basename("/foo.ext  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext  ", actual, "Path: '/foo.ext  '");
free(actual);
actual = file_basename("/foo.ext .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext ", actual, "Path: '/foo.ext .ext '");
free(actual);
actual = file_basename("/foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.", actual, "Path: '/foo.'");
free(actual);
actual = file_basename("/foo.ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext.", actual, "Path: '/foo.ext.'");
free(actual);
actual = file_basename("/foo .");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .", actual, "Path: '/foo .'");
free(actual);
actual = file_basename("/foo .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext.", actual, "Path: '/foo .ext.'");
free(actual);
actual = file_basename("/foo..");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..", actual, "Path: '/foo..'");
free(actual);
actual = file_basename("/foo..ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext.", actual, "Path: '/foo..ext.'");
free(actual);
actual = file_basename("/foo.ext .");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .", actual, "Path: '/foo.ext .'");
free(actual);
actual = file_basename("/foo.ext .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext.", actual, "Path: '/foo.ext .ext.'");
free(actual);
actual = file_basename("/foo.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.bar", actual, "Path: '/foo.bar'");
free(actual);
actual = file_basename("/foo.ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext.bar", actual, "Path: '/foo.ext.bar'");
free(actual);
actual = file_basename("/foo .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .bar", actual, "Path: '/foo .bar'");
free(actual);
actual = file_basename("/foo .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext.bar", actual, "Path: '/foo .ext.bar'");
free(actual);
actual = file_basename("/foo..bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..bar", actual, "Path: '/foo..bar'");
free(actual);
actual = file_basename("/foo..ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext.bar", actual, "Path: '/foo..ext.bar'");
free(actual);
actual = file_basename("/foo.ext .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .bar", actual, "Path: '/foo.ext .bar'");
free(actual);
actual = file_basename("/foo.ext .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext.bar", actual, "Path: '/foo.ext .ext.bar'");
free(actual);
actual = file_basename("/foo::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo::$DATA", actual, "Path: '/foo::$DATA'");
free(actual);
actual = file_basename("/foo.ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext::$DATA", actual, "Path: '/foo.ext::$DATA'");
free(actual);
actual = file_basename("/foo ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo ::$DATA", actual, "Path: '/foo ::$DATA'");
free(actual);
actual = file_basename("/foo .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext::$DATA", actual, "Path: '/foo .ext::$DATA'");
free(actual);
actual = file_basename("/foo.::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.::$DATA", actual, "Path: '/foo.::$DATA'");
free(actual);
actual = file_basename("/foo..ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext::$DATA", actual, "Path: '/foo..ext::$DATA'");
free(actual);
actual = file_basename("/foo.ext ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext ::$DATA", actual, "Path: '/foo.ext ::$DATA'");
free(actual);
actual = file_basename("/foo.ext .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext::$DATA", actual, "Path: '/foo.ext .ext::$DATA'");
free(actual);
actual = file_basename("/foo::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo::$DATA.bar", actual, "Path: '/foo::$DATA.bar'");
free(actual);
actual = file_basename("/foo.ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext::$DATA.bar", actual, "Path: '/foo.ext::$DATA.bar'");
free(actual);
actual = file_basename("/foo ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo ::$DATA.bar", actual, "Path: '/foo ::$DATA.bar'");
free(actual);
actual = file_basename("/foo .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo .ext::$DATA.bar", actual, "Path: '/foo .ext::$DATA.bar'");
free(actual);
actual = file_basename("/foo.::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.::$DATA.bar", actual, "Path: '/foo.::$DATA.bar'");
free(actual);
actual = file_basename("/foo..ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo..ext::$DATA.bar", actual, "Path: '/foo..ext::$DATA.bar'");
free(actual);
actual = file_basename("/foo.ext ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext ::$DATA.bar", actual, "Path: '/foo.ext ::$DATA.bar'");
free(actual);
actual = file_basename("/foo.ext .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE("foo.ext .ext::$DATA.bar", actual, "Path: '/foo.ext .ext::$DATA.bar'");
free(actual);
actual = file_basename(".foo");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo", actual, "Path: '.foo'");
free(actual);
actual = file_basename(".foo.ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext", actual, "Path: '.foo.ext'");
free(actual);
actual = file_basename(".foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ", actual, "Path: '.foo '");
free(actual);
actual = file_basename(".foo .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext", actual, "Path: '.foo .ext'");
free(actual);
actual = file_basename(".foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.", actual, "Path: '.foo.'");
free(actual);
actual = file_basename(".foo..ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext", actual, "Path: '.foo..ext'");
free(actual);
actual = file_basename(".foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ", actual, "Path: '.foo.ext '");
free(actual);
actual = file_basename(".foo.ext .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext", actual, "Path: '.foo.ext .ext'");
free(actual);
actual = file_basename(".foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ", actual, "Path: '.foo '");
free(actual);
actual = file_basename(".foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ", actual, "Path: '.foo.ext '");
free(actual);
actual = file_basename(".foo  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo  ", actual, "Path: '.foo  '");
free(actual);
actual = file_basename(".foo .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext ", actual, "Path: '.foo .ext '");
free(actual);
actual = file_basename(".foo. ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo. ", actual, "Path: '.foo. '");
free(actual);
actual = file_basename(".foo..ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext ", actual, "Path: '.foo..ext '");
free(actual);
actual = file_basename(".foo.ext  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext  ", actual, "Path: '.foo.ext  '");
free(actual);
actual = file_basename(".foo.ext .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext ", actual, "Path: '.foo.ext .ext '");
free(actual);
actual = file_basename(".foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.", actual, "Path: '.foo.'");
free(actual);
actual = file_basename(".foo.ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext.", actual, "Path: '.foo.ext.'");
free(actual);
actual = file_basename(".foo .");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .", actual, "Path: '.foo .'");
free(actual);
actual = file_basename(".foo .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext.", actual, "Path: '.foo .ext.'");
free(actual);
actual = file_basename(".foo..");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..", actual, "Path: '.foo..'");
free(actual);
actual = file_basename(".foo..ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext.", actual, "Path: '.foo..ext.'");
free(actual);
actual = file_basename(".foo.ext .");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .", actual, "Path: '.foo.ext .'");
free(actual);
actual = file_basename(".foo.ext .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext.", actual, "Path: '.foo.ext .ext.'");
free(actual);
actual = file_basename(".foo.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.bar", actual, "Path: '.foo.bar'");
free(actual);
actual = file_basename(".foo.ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext.bar", actual, "Path: '.foo.ext.bar'");
free(actual);
actual = file_basename(".foo .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .bar", actual, "Path: '.foo .bar'");
free(actual);
actual = file_basename(".foo .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext.bar", actual, "Path: '.foo .ext.bar'");
free(actual);
actual = file_basename(".foo..bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..bar", actual, "Path: '.foo..bar'");
free(actual);
actual = file_basename(".foo..ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext.bar", actual, "Path: '.foo..ext.bar'");
free(actual);
actual = file_basename(".foo.ext .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .bar", actual, "Path: '.foo.ext .bar'");
free(actual);
actual = file_basename(".foo.ext .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext.bar", actual, "Path: '.foo.ext .ext.bar'");
free(actual);
actual = file_basename(".foo::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo::$DATA", actual, "Path: '.foo::$DATA'");
free(actual);
actual = file_basename(".foo.ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext::$DATA", actual, "Path: '.foo.ext::$DATA'");
free(actual);
actual = file_basename(".foo ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ::$DATA", actual, "Path: '.foo ::$DATA'");
free(actual);
actual = file_basename(".foo .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext::$DATA", actual, "Path: '.foo .ext::$DATA'");
free(actual);
actual = file_basename(".foo.::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.::$DATA", actual, "Path: '.foo.::$DATA'");
free(actual);
actual = file_basename(".foo..ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext::$DATA", actual, "Path: '.foo..ext::$DATA'");
free(actual);
actual = file_basename(".foo.ext ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ::$DATA", actual, "Path: '.foo.ext ::$DATA'");
free(actual);
actual = file_basename(".foo.ext .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext::$DATA", actual, "Path: '.foo.ext .ext::$DATA'");
free(actual);
actual = file_basename(".foo::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo::$DATA.bar", actual, "Path: '.foo::$DATA.bar'");
free(actual);
actual = file_basename(".foo.ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext::$DATA.bar", actual, "Path: '.foo.ext::$DATA.bar'");
free(actual);
actual = file_basename(".foo ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ::$DATA.bar", actual, "Path: '.foo ::$DATA.bar'");
free(actual);
actual = file_basename(".foo .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext::$DATA.bar", actual, "Path: '.foo .ext::$DATA.bar'");
free(actual);
actual = file_basename(".foo.::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.::$DATA.bar", actual, "Path: '.foo.::$DATA.bar'");
free(actual);
actual = file_basename(".foo..ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext::$DATA.bar", actual, "Path: '.foo..ext::$DATA.bar'");
free(actual);
actual = file_basename(".foo.ext ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ::$DATA.bar", actual, "Path: '.foo.ext ::$DATA.bar'");
free(actual);
actual = file_basename(".foo.ext .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext::$DATA.bar", actual, "Path: '.foo.ext .ext::$DATA.bar'");
free(actual);
actual = file_basename("/.foo");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo", actual, "Path: '/.foo'");
free(actual);
actual = file_basename("/.foo.ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext", actual, "Path: '/.foo.ext'");
free(actual);
actual = file_basename("/.foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ", actual, "Path: '/.foo '");
free(actual);
actual = file_basename("/.foo .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext", actual, "Path: '/.foo .ext'");
free(actual);
actual = file_basename("/.foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.", actual, "Path: '/.foo.'");
free(actual);
actual = file_basename("/.foo..ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext", actual, "Path: '/.foo..ext'");
free(actual);
actual = file_basename("/.foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ", actual, "Path: '/.foo.ext '");
free(actual);
actual = file_basename("/.foo.ext .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext", actual, "Path: '/.foo.ext .ext'");
free(actual);
actual = file_basename("/.foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ", actual, "Path: '/.foo '");
free(actual);
actual = file_basename("/.foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ", actual, "Path: '/.foo.ext '");
free(actual);
actual = file_basename("/.foo  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo  ", actual, "Path: '/.foo  '");
free(actual);
actual = file_basename("/.foo .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext ", actual, "Path: '/.foo .ext '");
free(actual);
actual = file_basename("/.foo. ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo. ", actual, "Path: '/.foo. '");
free(actual);
actual = file_basename("/.foo..ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext ", actual, "Path: '/.foo..ext '");
free(actual);
actual = file_basename("/.foo.ext  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext  ", actual, "Path: '/.foo.ext  '");
free(actual);
actual = file_basename("/.foo.ext .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext ", actual, "Path: '/.foo.ext .ext '");
free(actual);
actual = file_basename("/.foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.", actual, "Path: '/.foo.'");
free(actual);
actual = file_basename("/.foo.ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext.", actual, "Path: '/.foo.ext.'");
free(actual);
actual = file_basename("/.foo .");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .", actual, "Path: '/.foo .'");
free(actual);
actual = file_basename("/.foo .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext.", actual, "Path: '/.foo .ext.'");
free(actual);
actual = file_basename("/.foo..");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..", actual, "Path: '/.foo..'");
free(actual);
actual = file_basename("/.foo..ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext.", actual, "Path: '/.foo..ext.'");
free(actual);
actual = file_basename("/.foo.ext .");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .", actual, "Path: '/.foo.ext .'");
free(actual);
actual = file_basename("/.foo.ext .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext.", actual, "Path: '/.foo.ext .ext.'");
free(actual);
actual = file_basename("/.foo.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.bar", actual, "Path: '/.foo.bar'");
free(actual);
actual = file_basename("/.foo.ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext.bar", actual, "Path: '/.foo.ext.bar'");
free(actual);
actual = file_basename("/.foo .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .bar", actual, "Path: '/.foo .bar'");
free(actual);
actual = file_basename("/.foo .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext.bar", actual, "Path: '/.foo .ext.bar'");
free(actual);
actual = file_basename("/.foo..bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..bar", actual, "Path: '/.foo..bar'");
free(actual);
actual = file_basename("/.foo..ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext.bar", actual, "Path: '/.foo..ext.bar'");
free(actual);
actual = file_basename("/.foo.ext .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .bar", actual, "Path: '/.foo.ext .bar'");
free(actual);
actual = file_basename("/.foo.ext .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext.bar", actual, "Path: '/.foo.ext .ext.bar'");
free(actual);
actual = file_basename("/.foo::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo::$DATA", actual, "Path: '/.foo::$DATA'");
free(actual);
actual = file_basename("/.foo.ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext::$DATA", actual, "Path: '/.foo.ext::$DATA'");
free(actual);
actual = file_basename("/.foo ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ::$DATA", actual, "Path: '/.foo ::$DATA'");
free(actual);
actual = file_basename("/.foo .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext::$DATA", actual, "Path: '/.foo .ext::$DATA'");
free(actual);
actual = file_basename("/.foo.::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.::$DATA", actual, "Path: '/.foo.::$DATA'");
free(actual);
actual = file_basename("/.foo..ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext::$DATA", actual, "Path: '/.foo..ext::$DATA'");
free(actual);
actual = file_basename("/.foo.ext ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ::$DATA", actual, "Path: '/.foo.ext ::$DATA'");
free(actual);
actual = file_basename("/.foo.ext .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext::$DATA", actual, "Path: '/.foo.ext .ext::$DATA'");
free(actual);
actual = file_basename("/.foo::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo::$DATA.bar", actual, "Path: '/.foo::$DATA.bar'");
free(actual);
actual = file_basename("/.foo.ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext::$DATA.bar", actual, "Path: '/.foo.ext::$DATA.bar'");
free(actual);
actual = file_basename("/.foo ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ::$DATA.bar", actual, "Path: '/.foo ::$DATA.bar'");
free(actual);
actual = file_basename("/.foo .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext::$DATA.bar", actual, "Path: '/.foo .ext::$DATA.bar'");
free(actual);
actual = file_basename("/.foo.::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.::$DATA.bar", actual, "Path: '/.foo.::$DATA.bar'");
free(actual);
actual = file_basename("/.foo..ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext::$DATA.bar", actual, "Path: '/.foo..ext::$DATA.bar'");
free(actual);
actual = file_basename("/.foo.ext ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ::$DATA.bar", actual, "Path: '/.foo.ext ::$DATA.bar'");
free(actual);
actual = file_basename("/.foo.ext .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext::$DATA.bar", actual, "Path: '/.foo.ext .ext::$DATA.bar'");
free(actual);
actual = file_basename("bar/.foo");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo", actual, "Path: 'bar/.foo'");
free(actual);
actual = file_basename("bar/.foo.ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext", actual, "Path: 'bar/.foo.ext'");
free(actual);
actual = file_basename("bar/.foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ", actual, "Path: 'bar/.foo '");
free(actual);
actual = file_basename("bar/.foo .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext", actual, "Path: 'bar/.foo .ext'");
free(actual);
actual = file_basename("bar/.foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.", actual, "Path: 'bar/.foo.'");
free(actual);
actual = file_basename("bar/.foo..ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext", actual, "Path: 'bar/.foo..ext'");
free(actual);
actual = file_basename("bar/.foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ", actual, "Path: 'bar/.foo.ext '");
free(actual);
actual = file_basename("bar/.foo.ext .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext", actual, "Path: 'bar/.foo.ext .ext'");
free(actual);
actual = file_basename("bar/.foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ", actual, "Path: 'bar/.foo '");
free(actual);
actual = file_basename("bar/.foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ", actual, "Path: 'bar/.foo.ext '");
free(actual);
actual = file_basename("bar/.foo  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo  ", actual, "Path: 'bar/.foo  '");
free(actual);
actual = file_basename("bar/.foo .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext ", actual, "Path: 'bar/.foo .ext '");
free(actual);
actual = file_basename("bar/.foo. ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo. ", actual, "Path: 'bar/.foo. '");
free(actual);
actual = file_basename("bar/.foo..ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext ", actual, "Path: 'bar/.foo..ext '");
free(actual);
actual = file_basename("bar/.foo.ext  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext  ", actual, "Path: 'bar/.foo.ext  '");
free(actual);
actual = file_basename("bar/.foo.ext .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext ", actual, "Path: 'bar/.foo.ext .ext '");
free(actual);
actual = file_basename("bar/.foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.", actual, "Path: 'bar/.foo.'");
free(actual);
actual = file_basename("bar/.foo.ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext.", actual, "Path: 'bar/.foo.ext.'");
free(actual);
actual = file_basename("bar/.foo .");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .", actual, "Path: 'bar/.foo .'");
free(actual);
actual = file_basename("bar/.foo .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext.", actual, "Path: 'bar/.foo .ext.'");
free(actual);
actual = file_basename("bar/.foo..");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..", actual, "Path: 'bar/.foo..'");
free(actual);
actual = file_basename("bar/.foo..ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext.", actual, "Path: 'bar/.foo..ext.'");
free(actual);
actual = file_basename("bar/.foo.ext .");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .", actual, "Path: 'bar/.foo.ext .'");
free(actual);
actual = file_basename("bar/.foo.ext .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext.", actual, "Path: 'bar/.foo.ext .ext.'");
free(actual);
actual = file_basename("bar/.foo.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.bar", actual, "Path: 'bar/.foo.bar'");
free(actual);
actual = file_basename("bar/.foo.ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext.bar", actual, "Path: 'bar/.foo.ext.bar'");
free(actual);
actual = file_basename("bar/.foo .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .bar", actual, "Path: 'bar/.foo .bar'");
free(actual);
actual = file_basename("bar/.foo .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext.bar", actual, "Path: 'bar/.foo .ext.bar'");
free(actual);
actual = file_basename("bar/.foo..bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..bar", actual, "Path: 'bar/.foo..bar'");
free(actual);
actual = file_basename("bar/.foo..ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext.bar", actual, "Path: 'bar/.foo..ext.bar'");
free(actual);
actual = file_basename("bar/.foo.ext .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .bar", actual, "Path: 'bar/.foo.ext .bar'");
free(actual);
actual = file_basename("bar/.foo.ext .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext.bar", actual, "Path: 'bar/.foo.ext .ext.bar'");
free(actual);
actual = file_basename("bar/.foo::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo::$DATA", actual, "Path: 'bar/.foo::$DATA'");
free(actual);
actual = file_basename("bar/.foo.ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext::$DATA", actual, "Path: 'bar/.foo.ext::$DATA'");
free(actual);
actual = file_basename("bar/.foo ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ::$DATA", actual, "Path: 'bar/.foo ::$DATA'");
free(actual);
actual = file_basename("bar/.foo .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext::$DATA", actual, "Path: 'bar/.foo .ext::$DATA'");
free(actual);
actual = file_basename("bar/.foo.::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.::$DATA", actual, "Path: 'bar/.foo.::$DATA'");
free(actual);
actual = file_basename("bar/.foo..ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext::$DATA", actual, "Path: 'bar/.foo..ext::$DATA'");
free(actual);
actual = file_basename("bar/.foo.ext ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ::$DATA", actual, "Path: 'bar/.foo.ext ::$DATA'");
free(actual);
actual = file_basename("bar/.foo.ext .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext::$DATA", actual, "Path: 'bar/.foo.ext .ext::$DATA'");
free(actual);
actual = file_basename("bar/.foo::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo::$DATA.bar", actual, "Path: 'bar/.foo::$DATA.bar'");
free(actual);
actual = file_basename("bar/.foo.ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext::$DATA.bar", actual, "Path: 'bar/.foo.ext::$DATA.bar'");
free(actual);
actual = file_basename("bar/.foo ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ::$DATA.bar", actual, "Path: 'bar/.foo ::$DATA.bar'");
free(actual);
actual = file_basename("bar/.foo .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext::$DATA.bar", actual, "Path: 'bar/.foo .ext::$DATA.bar'");
free(actual);
actual = file_basename("bar/.foo.::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.::$DATA.bar", actual, "Path: 'bar/.foo.::$DATA.bar'");
free(actual);
actual = file_basename("bar/.foo..ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext::$DATA.bar", actual, "Path: 'bar/.foo..ext::$DATA.bar'");
free(actual);
actual = file_basename("bar/.foo.ext ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ::$DATA.bar", actual, "Path: 'bar/.foo.ext ::$DATA.bar'");
free(actual);
actual = file_basename("bar/.foo.ext .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext::$DATA.bar", actual, "Path: 'bar/.foo.ext .ext::$DATA.bar'");
free(actual);
actual = file_basename("/bar/.foo");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo", actual, "Path: '/bar/.foo'");
free(actual);
actual = file_basename("/bar/.foo.ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext", actual, "Path: '/bar/.foo.ext'");
free(actual);
actual = file_basename("/bar/.foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ", actual, "Path: '/bar/.foo '");
free(actual);
actual = file_basename("/bar/.foo .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext", actual, "Path: '/bar/.foo .ext'");
free(actual);
actual = file_basename("/bar/.foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.", actual, "Path: '/bar/.foo.'");
free(actual);
actual = file_basename("/bar/.foo..ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext", actual, "Path: '/bar/.foo..ext'");
free(actual);
actual = file_basename("/bar/.foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ", actual, "Path: '/bar/.foo.ext '");
free(actual);
actual = file_basename("/bar/.foo.ext .ext");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext", actual, "Path: '/bar/.foo.ext .ext'");
free(actual);
actual = file_basename("/bar/.foo ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ", actual, "Path: '/bar/.foo '");
free(actual);
actual = file_basename("/bar/.foo.ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ", actual, "Path: '/bar/.foo.ext '");
free(actual);
actual = file_basename("/bar/.foo  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo  ", actual, "Path: '/bar/.foo  '");
free(actual);
actual = file_basename("/bar/.foo .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext ", actual, "Path: '/bar/.foo .ext '");
free(actual);
actual = file_basename("/bar/.foo. ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo. ", actual, "Path: '/bar/.foo. '");
free(actual);
actual = file_basename("/bar/.foo..ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext ", actual, "Path: '/bar/.foo..ext '");
free(actual);
actual = file_basename("/bar/.foo.ext  ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext  ", actual, "Path: '/bar/.foo.ext  '");
free(actual);
actual = file_basename("/bar/.foo.ext .ext ");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext ", actual, "Path: '/bar/.foo.ext .ext '");
free(actual);
actual = file_basename("/bar/.foo.");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.", actual, "Path: '/bar/.foo.'");
free(actual);
actual = file_basename("/bar/.foo.ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext.", actual, "Path: '/bar/.foo.ext.'");
free(actual);
actual = file_basename("/bar/.foo .");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .", actual, "Path: '/bar/.foo .'");
free(actual);
actual = file_basename("/bar/.foo .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext.", actual, "Path: '/bar/.foo .ext.'");
free(actual);
actual = file_basename("/bar/.foo..");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..", actual, "Path: '/bar/.foo..'");
free(actual);
actual = file_basename("/bar/.foo..ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext.", actual, "Path: '/bar/.foo..ext.'");
free(actual);
actual = file_basename("/bar/.foo.ext .");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .", actual, "Path: '/bar/.foo.ext .'");
free(actual);
actual = file_basename("/bar/.foo.ext .ext.");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext.", actual, "Path: '/bar/.foo.ext .ext.'");
free(actual);
actual = file_basename("/bar/.foo.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.bar", actual, "Path: '/bar/.foo.bar'");
free(actual);
actual = file_basename("/bar/.foo.ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext.bar", actual, "Path: '/bar/.foo.ext.bar'");
free(actual);
actual = file_basename("/bar/.foo .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .bar", actual, "Path: '/bar/.foo .bar'");
free(actual);
actual = file_basename("/bar/.foo .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext.bar", actual, "Path: '/bar/.foo .ext.bar'");
free(actual);
actual = file_basename("/bar/.foo..bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..bar", actual, "Path: '/bar/.foo..bar'");
free(actual);
actual = file_basename("/bar/.foo..ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext.bar", actual, "Path: '/bar/.foo..ext.bar'");
free(actual);
actual = file_basename("/bar/.foo.ext .bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .bar", actual, "Path: '/bar/.foo.ext .bar'");
free(actual);
actual = file_basename("/bar/.foo.ext .ext.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext.bar", actual, "Path: '/bar/.foo.ext .ext.bar'");
free(actual);
actual = file_basename("/bar/.foo::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo::$DATA", actual, "Path: '/bar/.foo::$DATA'");
free(actual);
actual = file_basename("/bar/.foo.ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext::$DATA", actual, "Path: '/bar/.foo.ext::$DATA'");
free(actual);
actual = file_basename("/bar/.foo ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ::$DATA", actual, "Path: '/bar/.foo ::$DATA'");
free(actual);
actual = file_basename("/bar/.foo .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext::$DATA", actual, "Path: '/bar/.foo .ext::$DATA'");
free(actual);
actual = file_basename("/bar/.foo.::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.::$DATA", actual, "Path: '/bar/.foo.::$DATA'");
free(actual);
actual = file_basename("/bar/.foo..ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext::$DATA", actual, "Path: '/bar/.foo..ext::$DATA'");
free(actual);
actual = file_basename("/bar/.foo.ext ::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ::$DATA", actual, "Path: '/bar/.foo.ext ::$DATA'");
free(actual);
actual = file_basename("/bar/.foo.ext .ext::$DATA");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext::$DATA", actual, "Path: '/bar/.foo.ext .ext::$DATA'");
free(actual);
actual = file_basename("/bar/.foo::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo::$DATA.bar", actual, "Path: '/bar/.foo::$DATA.bar'");
free(actual);
actual = file_basename("/bar/.foo.ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext::$DATA.bar", actual, "Path: '/bar/.foo.ext::$DATA.bar'");
free(actual);
actual = file_basename("/bar/.foo ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo ::$DATA.bar", actual, "Path: '/bar/.foo ::$DATA.bar'");
free(actual);
actual = file_basename("/bar/.foo .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo .ext::$DATA.bar", actual, "Path: '/bar/.foo .ext::$DATA.bar'");
free(actual);
actual = file_basename("/bar/.foo.::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.::$DATA.bar", actual, "Path: '/bar/.foo.::$DATA.bar'");
free(actual);
actual = file_basename("/bar/.foo..ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo..ext::$DATA.bar", actual, "Path: '/bar/.foo..ext::$DATA.bar'");
free(actual);
actual = file_basename("/bar/.foo.ext ::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext ::$DATA.bar", actual, "Path: '/bar/.foo.ext ::$DATA.bar'");
free(actual);
actual = file_basename("/bar/.foo.ext .ext::$DATA.bar");
TEST_ASSERT_EQUAL_STRING_MESSAGE(".foo.ext .ext::$DATA.bar", actual, "Path: '/bar/.foo.ext .ext::$DATA.bar'");
free(actual);
}

