Ruby-like C: src/rfile.c File Reference
rfile.c File Reference
File containing functions like those found in Ruby's File class.
#include <assert.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <sys/stat.h>
#include "rfile.h"
#include "rstring.h"
#include "err_codes.h"
#include "bstrlib.h"
Functions
int rfile_exist (const rstring *fname)
Tells whether a file exists or not (i.e., stat is successful).
int rfile_is_directory (const rstring *fname)
Tells whether the named directory exists.
int rfile_is_file (const rstring *fname)
Tells whether the named file exists and is a regular file.
rstring * rfile_basename (const rstring *fname)
Return the basename of a file.
rstring * rfile_dirname (const rstring *fname)
Return the dirname of a file.
rstring * rfile_extname (const rstring *fname)
Return the extension of a file.
rstring * rfile_join (rstring_array *rary)
Returns a new path by joining the strings using the RFILE_SEPARATOR.
Detailed Description
File containing functions like those found in Ruby's File class.
Author
Ryan Moore
See also
https://ruby-doc.org/core-2.5.0/File.html
Definition in file rfile.c.
Function Documentation
rfile_basename()
rstring* rfile_basename (const rstring * fname)
Return the basename of a file.
Parameters
fname An rstring with the file name.
Return values
rstring* A valid rstring containing the basename of the file.
NULL The input rstring is invalid or there was an error.
Warning
The caller must free the result.
Todo:
Ruby's also takes an optional second param for extname to strip.
Definition at line 176 of file rfile.c.
References rstring_bad, rstring_length(), and rstring_new().
 {
   if (rstring_bad(fname)) { return NULL; }
   int i                = 0;
   int i_last_fs        = 0;
   int i_basename_start = 0;
   int char_at = 0;
   int slen         = rstring_length(fname);
   if (slen == RERROR) { return NULL; }
   int basename_len = 0;
   rstring* basename = NULL;
   /* If we are passed an empty string.... */
   if (slen == 0) {
     basename = rstring_new("");
     if (rstring_bad(basename)) { return NULL; }
     return basename;
   }
   i = index_before_first_trailing_file_separator(fname);
   if (i < 0) {
     /* This can only happen for names like "////" */
     char_at = rstring_char_at(fname, 0);
     if (char_at == RERROR || char_at != RFILE_SEPARATOR) {
       return NULL;
     }
     basename = rstring_new(RFILE_SEPARATOR_STR);
     if (rstring_bad(basename)) { return NULL; }
   }
   else {
     /* The current index points to the char just before the first of
        trailing RFILE_SEPARATOR chars if there are any, so the trailing
        RFILE_SEPARATORs begin at i + 1. */
     i_last_fs = i + 1;
     for (i = i_last_fs - 1; i >= 0; --i) {
       char_at = rstring_char_at(fname, i);
       if (char_at == RFILE_SEPARATOR) {
         break;
       }
     }
     i_basename_start = i + 1;
     basename_len     = i_last_fs - i_basename_start;
     basename = rstring_slice(fname, i_basename_start, basename_len);
     if (rstring_bad(basename)) { return NULL; }
   }
   return basename;
 }
rfile_dirname()
rstring* rfile_dirname (const rstring * fname)
Return the dirname of a file.
Returns all components of the filename given in file_name except the last one (after first stripping trailing separators).
Parameters
fname An rstring with the file name.
Return values
rstring* A valid rstring containing the directory of the file.
NULL The input rstring is invalid or there was an error.
Warning
The caller must free the result.
Definition at line 248 of file rfile.c.
References rstring_bad, rstring_length(), and rstring_new().
 {
   if (rstring_bad(fname)) { return NULL; }
   int i = 0;
   int char_at = 0;
   int slen = rstring_length(fname);
   if (slen == RERROR) { return NULL; }
   rstring* dirname = NULL;
   if (slen == 0) {
     dirname = rstring_new("");
     if (rstring_bad(dirname)) { return NULL; }
     return dirname;
   }
   i = index_of_last_file_separator(fname);
   char_at = rstring_char_at(fname, 0);
   if (char_at == RERROR) { return NULL; }
   if (i < 0 && char_at == RFILE_SEPARATOR) {
     /* Filenames like: "/////" */
     dirname = rstring_new(RFILE_SEPARATOR_STR);
     if (rstring_bad(dirname)) { return NULL; }
   }
   else if (i < 0) {
     /* Filenames like: "apple" */
     dirname = rstring_new(".");
     if (rstring_bad(dirname)) { return NULL; }
   }
   else {
     /* There was a basename.  Now we need to make sure that there
        aren't a bunch of fs chars right in a row. */
     i = index_of_last_file_separator_from_pos(fname, i);
     if (i <= 0) {
       /* This could happen for filenames like: "/////apple" or "/apple" */
       dirname = rstring_new(RFILE_SEPARATOR_STR);
       if (rstring_bad(dirname)) { return NULL; }
     }
     else {
       int i_before_last_fs = i - 1;
       dirname = rstring_slice(fname, 0, i_before_last_fs + 1);
       if (rstring_bad(dirname)) { return NULL; }
     }
   }
   return dirname;
 }
rfile_exist()
int rfile_exist (const rstring * fname)
Tells whether a file exists or not (i.e., stat is successful).
Parameters
fname An rstring with the filename to check.
Return values
RTRUE The file exists
RFALSE The file does not exist
RERROR fname is invalid or there was an error.
Definition at line 74 of file rfile.c.
References rstring_bad.
 {
   if (rstring_bad(fname)) { return RERROR; }
   int ret_val = 0;
   char* cfname = bstr2cstr(fname, '?');
   if (cfname == NULL) { return RERROR; }
   struct stat st;
   ret_val = stat(cfname, &st);
   free(cfname);
   if (ret_val < 0) {
     return RFALSE;
   }
   else {
     return RTRUE;
   }
 }
rfile_extname()
rstring* rfile_extname (const rstring * fname)
Return the extension of a file.
Parameters
fname An rstring with the file name.
Return values
rstring* A valid rstring containing the extension of the file.
NULL The input rstring is invalid or there was an error.
Warning
The caller must free the result.
Definition at line 313 of file rfile.c.
References rfile_basename(), rstring_bad, rstring_free(), rstring_length(), rstring_new(), and rstring_slice().
 {
   if (rstring_bad(fname)) { return NULL; }
   int basename_len = 0;
   int last_dot = 0;
   rstring* basename = NULL;
   rstring* extname  = NULL;
   basename     = rfile_basename(fname);
   if (rstring_bad(basename)) { return NULL; }
   basename_len = rstring_length(basename);
   if (basename_len == RERROR) { return NULL; }
   last_dot = bstrrchr((const_bstring)basename, '.');
   if (/* No '.' was found */
       (last_dot == BSTR_ERR) ||
       /* The last dot was the first char: ".profile" */
       (last_dot == 0) ||
       /* If the dot was the last thing in the fname: "foo." */
       (last_dot == basename_len - 1)) {
     extname = rstring_new("");
     if (rstring_bad(extname)) { return NULL; }
   }
   else {
     extname = rstring_slice(basename, last_dot, basename_len);
     if (rstring_bad(extname)) { return NULL; }
   }
   rstring_free(basename);
   return extname;
 }
rfile_is_directory()
int rfile_is_directory (const rstring * fname)
Tells whether the named directory exists.
Parameters
fname An rstring with the dirname to check.
Return values
RTRUE The dir exists
RFALSE The dir does not exist
RERROR The input rstring is invalid or there was an error.
Todo:
Ruby also returns true if dir is a symlink that points at a directory.
Definition at line 107 of file rfile.c.
References rstring_bad.
 {
   if (rstring_bad(fname)) { return RERROR; }
   int ret_val = 0;
   char* cfname = bstr2cstr(fname, '?');
   if (cfname == NULL) { return RERROR; }
   struct stat st;
   ret_val = stat(cfname, &st);
   bcstrfree(cfname);
   if (ret_val < 0 || !S_ISDIR(st.st_mode)) {
     return RFALSE;
   }
   else {
     return RTRUE;
   }
 }
rfile_is_file()
int rfile_is_file (const rstring * fname)
Tells whether the named file exists and is a regular file.
Parameters
fname An rstring with the dirname to check.
Return values
RTRUE The file exists
RFALSE The file does not exist
RERROR The input rstring is invalid or there was an error.
Todo:
Ruby also returns true if file is a symlink that points at a file.
Definition at line 141 of file rfile.c.
References rstring_bad.
 {
   if (rstring_bad(fname)) { return RERROR; }
   int ret_val = 0;
   char* cfname = bstr2cstr(fname, '?');
   if (cfname == NULL) { return RERROR; }
   struct stat st;
   ret_val = stat(cfname, &st);
   bcstrfree(cfname);
   if (ret_val < 0 || !S_ISREG(st.st_mode)) {
     return RFALSE;
   }
   else {
     return RTRUE;
   }
 }
rfile_join()
rstring* rfile_join (rstring_array * rary)
Returns a new path by joining the strings using the RFILE_SEPARATOR.
Parameters
rary An rstring_array with the rstrings to join.
Return values
rstring* A valid rstring with the input strings all joined up.
NULL The input rstring_array is invalid or there was an error.
Note
Ruby has some weird behavior here where it sometimes keeps double // and sometimes it doesn't. It doesn't in cases where there is more than one slash in a single one of the input strings. Regardless, the function is for building paths so in that spirit, we don't want those double separators anyways. Soooo, it differs from Ruby in these cases.
Warning
The caller must free the result.
Todo:
the no_doubles path will use a bit more memory than it actually needs if some of the double // are removed.
Definition at line 368 of file rfile.c.
References rstring_array_bad.
 {
   if (rstring_array_bad(rary)) { return NULL; }
   int i = 0;
   int j = 0;
   int len = 0;
   int char_at = 0;
   /* Check if any of the rstrings are null */
   for (i = 0; i < rary->qty; ++i) {
     if (rstring_array_get(rary, i) == NULL) { return NULL; }
   }
   rstring* path = NULL;
   rstring* sep = NULL;
   int c = 0;
   int c_minus_1 = 0;
   sep = rstring_new(RFILE_SEPARATOR_STR);
   if (rstring_bad(sep)) { return NULL; }
   /* Clean up path if early exit from here down. */
   path = rstring_array_join(rary, sep);
   if (rstring_bad(path)) { return NULL; }
   rstring_free(sep);
   /* If it's empty, there are no doubles. */
   len = rstring_length(path);
   if (len == RERROR) { rstring_free(path); return NULL; }
   if (len == 0) { return path; }
   /* Remove doubles of file sep. */
   /* Clean up no_doubles if early exit from here down. */
   char* no_doubles = malloc(sizeof(char) * ((len + 1)));
   if (no_doubles == NULL) { rstring_free(path); return NULL; }
   j = 0;
   char_at = rstring_char_at(path, 0);
   if (char_at == RERROR) { rstring_free(path); free(no_doubles); return NULL; }
   no_doubles[j++] = char_at;
   for (i = 1; i < len; ++i) {
     c = rstring_char_at(path, i);
     c_minus_1 = rstring_char_at(path, i - 1);
     if (c == RERROR || c_minus_1 == RERROR) {
       rstring_free(path); free(no_doubles); return NULL;
     }
     if (c != RFILE_SEPARATOR || c_minus_1 != RFILE_SEPARATOR) {
       no_doubles[j++] = c;
     }
   }
   no_doubles[j] = '\0';
   rstring_free(path);
   /* Rewrite the path */
   path = rstring_new(no_doubles);
   if (rstring_bad(path)) { free(no_doubles); return NULL; }
   free(no_doubles);
   return path;
 }