Ruby-like C: src/rlib.h File Reference
rlib.h File Reference
File containing functions like those found in Ruby's String class.
#include <assert.h>
#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <stdarg.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
Data Structures
struct bstrList
struct tagbstring
struct charField
struct bStream
struct genBstrList
Macros
#define RLIB_VERSION "v0.2.0"
#define SUCCESS 0
#define ARG_ERR 2
#define FILE_ERR 3
#define KSEQ_ERR 5
#define MEM_ERR 6
#define STD_ERR 1
#define THREAD_ERR 4
#define OPT_ERR 7
#define FILE_ERR_MSG "could not open '%s' for %s"
#define KSEQ_ERR_MSG "could not init kseq on '%s'"
#define MEM_ERR_MSG "memory error while allocating"
#define STD_ERR_MSG "an error occured"
#define PANIC_IF(iostream, test, err_type, msg, ...)
#define PANIC_UNLESS(iostream, test, err_type, msg, ...)
#define PANIC_MEM(iostream, var)
#define PANIC_UNLESS_FILE_CAN_BE_READ(iostream, fname)
#define PANIC_IF_FILE_CAN_BE_READ(iostream, fname)
#define BSTR_ERR (-1)
#define BSTR_OK (0)
#define BSTR_BS_BUFF_LENGTH_GET (0)
#define BSTR_VER_MAJOR 1
#define BSTR_VER_MINOR 0
#define BSTR_VER_UPDATE 0
#define cstr2bstr bfromcstr
#define bstrchr(b, c) bstrchrp ((b), (c), 0)
#define bstrrchr(b, c) bstrrchrp ((b), (c), blength(b)-1)
#define bvformata(ret, b, fmt, lastarg)
#define blengthe(b, e) (((b) == (void *)0 || (b)->slen < 0) ? (int)(e) : ((b)->slen))
#define blength(b) (blengthe ((b), 0))
#define bdataofse(b, o, e) (((b) == (void *)0 || (b)->data == (void*)0) ? (char *)(e) : ((char *)(b)->data) + (o))
#define bdataofs(b, o) (bdataofse ((b), (o), (void *)0))
#define bdatae(b, e) (bdataofse (b, 0, e))
#define bdata(b) (bdataofs (b, 0))
#define bchare(b, p, e) ((((unsigned)(p)) < (unsigned)blength(b)) ? ((b)->data[(p)]) : (e))
#define bchar(b, p) bchare ((b), (p), '\0')
#define bsStaticMlen(q, m) {(m), (int) sizeof(q)-1, (unsigned char *) ("" q "")}
#define bsStatic(q) bsStaticMlen(q,-__LINE__)
#define bsStaticBlkParms(q) ((void *)("" q "")), ((int) sizeof(q)-1)
#define bcatStatic(b, s) ((bcatblk)((b), bsStaticBlkParms(s)))
#define bfromStatic(s) ((blk2bstr)(bsStaticBlkParms(s)))
#define bassignStatic(b, s) ((bassignblk)((b), bsStaticBlkParms(s)))
#define binsertStatic(b, p, s, f) ((binsertblk)((b), (p), bsStaticBlkParms(s), (f)))
#define bjoinStatic(b, s) ((bjoinblk)((b), bsStaticBlkParms(s)))
#define biseqStatic(b, s) ((biseqblk)((b), bsStaticBlkParms(s)))
#define bisstemeqStatic(b, s) ((bisstemeqblk)((b), bsStaticBlkParms(s)))
#define biseqcaselessStatic(b, s) ((biseqcaselessblk)((b), bsStaticBlkParms(s)))
#define bisstemeqcaselessStatic(b, s) ((bisstemeqcaselessblk)((b), bsStaticBlkParms(s)))
#define cstr2tbstr btfromcstr
#define btfromcstr(t, s)
#define blk2tbstr(t, s, l)
#define btfromblk(t, s, l) blk2tbstr(t,s,l)
#define bmid2tbstr(t, b, p, l)
#define btfromblkltrimws(t, s, l)
#define btfromblkrtrimws(t, s, l)
#define btfromblktrimws(t, s, l)
#define bwriteprotect(t) { if ((t).mlen >= 0) (t).mlen = -1; }
#define bwriteallow(t) { if ((t).mlen == -1) (t).mlen = (t).slen + ((t).slen == 0); }
#define biswriteprotected(t) ((t).mlen <= 0)
#define bstr__alloc(x) malloc (x)
#define bstr__free(p) free (p)
#define bstr__realloc(p, x) realloc ((p), (x))
#define bstr__memcpy(d, s, l) memcpy ((d), (s), (l))
#define bstr__memmove(d, s, l) memmove ((d), (s), (l))
#define bstr__memset(d, c, l) memset ((d), (c), (l))
#define bstr__memcmp(d, c, l) memcmp ((d), (c), (l))
#define bstr__memchr(s, c, l) memchr ((s), (c), (l))
#define bBlockCopy(D, S, L) { if ((L) > 0) bstr__memmove ((D),(S),(L)); }
#define upcase(c) (toupper ((unsigned char) c))
#define downcase(c) (tolower ((unsigned char) c))
#define wspace(c) (isspace ((unsigned char) c))
#define LONG_LOG_BITS_QTY (3)
#define LONG_BITS_QTY (1 << LONG_LOG_BITS_QTY)
#define LONG_TYPE unsigned char
#define CFCLEN ((1 << CHAR_BIT) / LONG_BITS_QTY)
#define testInCharField(cf, c)
#define setInCharField(cf, idx)
#define INITIAL_STATIC_FIND_INDEX_COUNT 32
#define BS_BUFF_SZ (1024)
#define BSSSC_BUFF_LEN (256)
#define exvsnprintf(r, b, n, f, a) {r = vsnprintf (b,n,f,a);}
#define START_VSNBUFF (16)
#define RERROR BSTR_ERR
#define ROKAY BSTR_OK
#define RTRUE 1
#define RFALSE 0
#define rstring_bad(rstr) (rstr == NULL || rstr->data == NULL || rstr->mlen < rstr->slen || rstr->slen < 0 || rstr->mlen <= 0)
These conditions must hold for the rstring to be valid. See the btolower function for this.
#define rstring_array_bad(rary) (rary == NULL || rary->entry == NULL || rary->mlen < rary->qty || rary->qty < 0 || rary->mlen <= 0)
Check that an rstring_array is valid.
#define rstring_data(rstr) (bdata((bstring)rstr))
Get the ->data portion of the rstring (i.e., the char* part).
#define rstring_format(fmt, ...) ((rstring*)bformat(fmt, __VA_ARGS__))
This is like Ruby's "apple %s" % "pie" % operator.
#define RFILE_SEPARATOR '/'
#define RFILE_SEPARATOR_STR "/"
#define S_ISDIR(mode) (((mode) & S_IFMT) == S_IFDIR)
#define S_ISREG(mode) (((mode) & S_IFMT) == S_IFREG)
Typedefs
typedef struct tagbstring * bstring
typedef const struct tagbstring * const_bstring
typedef int(* bNgetc) (void *parm)
typedef size_t(* bNread) (void *buff, size_t elsize, size_t nelem, void *parm)
typedef int(* instr_fnptr) (const_bstring s1, int pos, const_bstring s2)
typedef struct tagbstring rstring
typedef struct bstrList rstring_array
Functions
bstring bfromcstr (const char *str)
bstring bfromcstr_check_length (const char *str)
Like bfromcstr but checks that the strlen is not >= INT_MAX.
bstring bfromcstralloc (int mlen, const char *str)
bstring bfromcstrrangealloc (int minl, int maxl, const char *str)
bstring blk2bstr (const void *blk, int len)
char * bstr2cstr (const_bstring s, char z)
int bcstrfree (char *s)
bstring bstrcpy (const_bstring b1)
int bassign (bstring a, const_bstring b)
int bassignmidstr (bstring a, const_bstring b, int left, int len)
int bassigncstr (bstring a, const char *str)
int bassignblk (bstring a, const void *s, int len)
int bdestroy (bstring b)
int balloc (bstring s, int len)
int ballocmin (bstring b, int len)
bstring bmidstr (const_bstring b, int left, int len)
int bconcat (bstring b0, const_bstring b1)
int bconchar (bstring b0, char c)
int bcatcstr (bstring b, const char *s)
int bcatblk (bstring b, const void *s, int len)
int binsert (bstring s1, int pos, const_bstring s2, unsigned char fill)
int binsertblk (bstring s1, int pos, const void *s2, int len, unsigned char fill)
int binsertch (bstring s1, int pos, int len, unsigned char fill)
int breplace (bstring b1, int pos, int len, const_bstring b2, unsigned char fill)
int bdelete (bstring s1, int pos, int len)
int bsetstr (bstring b0, int pos, const_bstring b1, unsigned char fill)
int btrunc (bstring b, int n)
int bstricmp (const_bstring b0, const_bstring b1)
int bstrnicmp (const_bstring b0, const_bstring b1, int n)
int biseqcaseless (const_bstring b0, const_bstring b1)
int biseqcaselessblk (const_bstring b, const void *blk, int len)
int bisstemeqcaselessblk (const_bstring b0, const void *blk, int len)
int biseq (const_bstring b0, const_bstring b1)
int biseqblk (const_bstring b, const void *blk, int len)
int bisstemeqblk (const_bstring b0, const void *blk, int len)
int biseqcstr (const_bstring b, const char *s)
int biseqcstrcaseless (const_bstring b, const char *s)
int bstrcmp (const_bstring b0, const_bstring b1)
int bstrncmp (const_bstring b0, const_bstring b1, int n)
int binstr (const_bstring s1, int pos, const_bstring s2)
int binstrr (const_bstring s1, int pos, const_bstring s2)
int binstrcaseless (const_bstring s1, int pos, const_bstring s2)
int binstrrcaseless (const_bstring s1, int pos, const_bstring s2)
int bstrchrp (const_bstring b, int c, int pos)
int bstrrchrp (const_bstring b, int c, int pos)
int binchr (const_bstring b0, int pos, const_bstring b1)
int binchrr (const_bstring b0, int pos, const_bstring b1)
int bninchr (const_bstring b0, int pos, const_bstring b1)
int bninchrr (const_bstring b0, int pos, const_bstring b1)
int bfindreplace (bstring b, const_bstring find, const_bstring repl, int pos)
int bfindreplacecaseless (bstring b, const_bstring find, const_bstring repl, int pos)
struct bstrList * bstrListCreate (void)
int bstrListDestroy (struct bstrList *sl)
int bstrListAlloc (struct bstrList *sl, int msz)
int bstrListAllocMin (struct bstrList *sl, int msz)
struct bstrList * bsplit (const_bstring str, unsigned char splitChar)
struct bstrList * bsplits (const_bstring str, const_bstring splitStr)
struct bstrList * bsplitstr (const_bstring str, const_bstring splitStr)
bstring bjoin (const struct bstrList *bl, const_bstring sep)
bstring bjoinblk (const struct bstrList *bl, const void *s, int len)
int bsplitcb (const_bstring str, unsigned char splitChar, int pos, int(*cb)(void *parm, int ofs, int len), void *parm)
int bsplitscb (const_bstring str, const_bstring splitStr, int pos, int(*cb)(void *parm, int ofs, int len), void *parm)
int bsplitstrcb (const_bstring str, const_bstring splitStr, int pos, int(*cb)(void *parm, int ofs, int len), void *parm)
int bpattern (bstring b, int len)
int btoupper (bstring b)
int btolower (bstring b)
int bltrimws (bstring b)
int brtrimws (bstring b)
int btrimws (bstring b)
bstring bformat (const char *fmt,...)
int bformata (bstring b, const char *fmt,...)
int bassignformat (bstring b, const char *fmt,...)
int bvcformata (bstring b, int count, const char *fmt, va_list arglist)
bstring bgets (bNgetc getcPtr, void *parm, char terminator)
bstring bread (bNread readPtr, void *parm)
int bgetsa (bstring b, bNgetc getcPtr, void *parm, char terminator)
int bassigngets (bstring b, bNgetc getcPtr, void *parm, char terminator)
int breada (bstring b, bNread readPtr, void *parm)
struct bStream * bsopen (bNread readPtr, void *parm)
void * bsclose (struct bStream *s)
int bsbufflength (struct bStream *s, int sz)
int bsreadln (bstring b, struct bStream *s, char terminator)
int bsreadlns (bstring r, struct bStream *s, const_bstring term)
int bsread (bstring b, struct bStream *s, int n)
int bsreadlna (bstring b, struct bStream *s, char terminator)
int bsreadlnsa (bstring r, struct bStream *s, const_bstring term)
int bsreada (bstring b, struct bStream *s, int n)
int bsunread (struct bStream *s, const_bstring b)
int bspeek (bstring r, const struct bStream *s)
int bssplitscb (struct bStream *s, const_bstring splitStr, int(*cb)(void *parm, int ofs, const_bstring entry), void *parm)
int bssplitstrcb (struct bStream *s, const_bstring splitStr, int(*cb)(void *parm, int ofs, const_bstring entry), void *parm)
int bseof (const struct bStream *s)
rstring * rstring_new (const char *cstr)
Make a new rstring from c string.
rstring * rstring_copy (const rstring *rstr)
Copies the rstring.
int rstring_free (rstring *rstr)
Free the rstring.
rstring * rstring_chomp (const rstring *rstr)
Make a new string with final trailing record separator removed.
rstring * rstring_downcase (const rstring *rstr)
Return a copy of rstr with everything lowercase.
rstring * rstring_gsub (const rstring *rstr, const rstring *pattern, const rstring *replacement)
Return a copy of rstr with all occurrences of pattern substituted for the value of replacement.
rstring * rstring_gsub_cstr (const rstring *rstr, const char *pattern, const char *replacement)
Wraps rstring_gsub() but takes char* for pattern and replacement.
rstring * rstring_lstrip (const rstring *rstr)
Returns a copy of rstr with leading whitespace removed.
rstring * rstring_reverse (const rstring *rstr)
Returns a new rstring with the characters from rstr in reverse order.
rstring * rstring_rstrip (const rstring *rstr)
Returns a copy of rstr with trailing whitespace removed.
rstring * rstring_slice1 (const rstring *rstr, int index)
Gives the char at index but as an rstring.
rstring * rstring_slice (const rstring *rstr, int index, int length)
Return a substring starting at index of a given length (clamped by the end of rstr).
rstring * rstring_strip (const rstring *rstr)
Returns a copy of rstr with leading and trailing whitespace removed.
rstring * rstring_upcase (const rstring *rstr)
Return a copy of rstr with everything uppercase.
int rstring_eql (const rstring *rstr1, const rstring *rstr2)
Two strings are equal if they have the same length and content.
int rstring_eql_cstr (const rstring *rstr, const char *cstr)
Two strings are equal if they have the same length and content.
int rstring_include (const rstring *rstr, const rstring *substring)
Tells whether rstr contains the other rstring.
int rstring_include_cstr (const rstring *rstr, const char *substring)
Wraps rstring_include() but takes char* for substring.
int rstring_index (const rstring *rstr, const rstring *substring)
Tells the first occurence of substring in rstr.
int rstring_index_cstr (const rstring *rstr, const char *substring)
Wraps rstring_index() but takes char* for substring.
int rstring_index_offset (const rstring *rstr, const rstring *substring, int offset)
Tells the first occurence (starting at offset) of substring in rstr.
int rstring_index_offset_cstr (const rstring *rstr, const char *substring, int start_pos)
Wraps rstring_index_offset() but takes char* for substring.
int rstring_length (const rstring *rstr)
Returns the length of the rstring.
int rstring_char_at (const rstring *rstr, int idx)
Return the char at given position.
rstring_array * rstring_array_new ()
int rstring_array_free (rstring_array *rary)
int rstring_array_push_cstr (rstring_array *rary, char *cstr)
int rstring_array_push_rstr (rstring_array *rary, rstring *rstr)
rstring * rstring_array_get (rstring_array *rary, int index)
rstring * rstring_array_join (rstring_array *rstrings, const rstring *sep)
rstring * rstring_array_join_cstr (rstring_array *rstrings, const char *sep)
Wraps rstring_array_join() but takes char* for sep.
rstring_array * rstring_split (rstring *rstr, const rstring *sep)
rstring_array * rstring_split_cstr (rstring *rstr, const char *sep)
Wraps rstring_split() but takes char* for sep.
int rfile_exist (const rstring *fname)
Tells whether a file exists or not (i.e., stat is successful).
int rfile_is_directory (const rstring *fname)
Tells whether the named directory exists.
int rfile_is_file (const rstring *fname)
Tells whether the named file exists and is a regular file.
rstring * rfile_basename (const rstring *fname)
Return the basename of a file.
rstring * rfile_basename2 (const rstring *fname, const rstring *extname)
Return the basename of a file, with the extname stripped off.
rstring * rfile_basename2_cstr (const rstring *fname, const char *extname)
Return the basename of a file, with the extname stripped off. It's like rfile_basename2() but takes a char* for the extname.
rstring * rfile_dirname (const rstring *fname)
Return the dirname of a file.
rstring * rfile_extname (const rstring *fname)
Return the extension of a file.
rstring * rfile_join (rstring_array *rary)
Returns a new path by joining the strings using the RFILE_SEPARATOR.
Detailed Description
File containing functions like those found in Ruby's String class.
Author
Ryan Moore
See also
https://ruby-doc.org/core-2.5.0/String.html
Definition in file rlib.h.
Macro Definition Documentation
blk2tbstr
#define blk2tbstr (t, s, l)
Value:
{            \
    (t).data = (unsigned char *) (s); \
    (t).slen = l;                     \
    (t).mlen = -1;                    \
}
Definition at line 375 of file rlib.h.
bmid2tbstr
#define bmid2tbstr (t, b, p, l)
Value:
{                                                \
    const_bstring bstrtmp_s = (b);                                           \
    if (bstrtmp_s && bstrtmp_s->data && bstrtmp_s->slen >= 0) {              \
        int bstrtmp_left = (p);                                              \
        int bstrtmp_len  = (l);                                              \
        if (bstrtmp_left < 0) {                                              \
            bstrtmp_len += bstrtmp_left;                                     \
            bstrtmp_left = 0;                                                \
        }                                                                    \
        if (bstrtmp_len > bstrtmp_s->slen - bstrtmp_left)                    \
            bstrtmp_len = bstrtmp_s->slen - bstrtmp_left;                    \
        if (bstrtmp_len <= 0) {                                              \
            (t).data = (unsigned char *)"";                                  \
            (t).slen = 0;                                                    \
        } else {                                                             \
            (t).data = bstrtmp_s->data + bstrtmp_left;                       \
            (t).slen = bstrtmp_len;                                          \
        }                                                                    \
    } else {                                                                 \
        (t).data = (unsigned char *)"";                                      \
        (t).slen = 0;                                                        \
    }                                                                        \
    (t).mlen = -__LINE__;                                                    \
}
Definition at line 381 of file rlib.h.
btfromblkltrimws
#define btfromblkltrimws (t, s, l)
Value:
{                                            \
    int bstrtmp_idx = 0, bstrtmp_len = (l);                                  \
    unsigned char * bstrtmp_s = (s);                                         \
    if (bstrtmp_s && bstrtmp_len >= 0) {                                     \
        for (; bstrtmp_idx < bstrtmp_len; bstrtmp_idx++) {                   \
            if (!isspace (bstrtmp_s[bstrtmp_idx])) break;                    \
        }                                                                    \
    }                                                                        \
    (t).data = bstrtmp_s + bstrtmp_idx;                                      \
    (t).slen = bstrtmp_len - bstrtmp_idx;                                    \
    (t).mlen = -__LINE__;                                                    \
}
Definition at line 405 of file rlib.h.
btfromblkrtrimws
#define btfromblkrtrimws (t, s, l)
Value:
{                                            \
    int bstrtmp_len = (l) - 1;                                               \
    unsigned char * bstrtmp_s = (s);                                         \
    if (bstrtmp_s && bstrtmp_len >= 0) {                                     \
        for (; bstrtmp_len >= 0; bstrtmp_len--) {                            \
            if (!isspace (bstrtmp_s[bstrtmp_len])) break;                    \
        }                                                                    \
    }                                                                        \
    (t).data = bstrtmp_s;                                                    \
    (t).slen = bstrtmp_len + 1;                                              \
    (t).mlen = -__LINE__;                                                    \
}
Definition at line 417 of file rlib.h.
btfromblktrimws
#define btfromblktrimws (t, s, l)
Value:
{                                             \
    int bstrtmp_idx = 0, bstrtmp_len = (l) - 1;                              \
    unsigned char * bstrtmp_s = (s);                                         \
    if (bstrtmp_s && bstrtmp_len >= 0) {                                     \
        for (; bstrtmp_idx <= bstrtmp_len; bstrtmp_idx++) {                  \
            if (!isspace (bstrtmp_s[bstrtmp_idx])) break;                    \
        }                                                                    \
        for (; bstrtmp_len >= bstrtmp_idx; bstrtmp_len--) {                  \
            if (!isspace (bstrtmp_s[bstrtmp_len])) break;                    \
        }                                                                    \
    }                                                                        \
    (t).data = bstrtmp_s + bstrtmp_idx;                                      \
    (t).slen = bstrtmp_len + 1 - bstrtmp_idx;                                \
    (t).mlen = -__LINE__;                                                    \
}
Definition at line 429 of file rlib.h.
btfromcstr
#define btfromcstr (t, s)
Value:
{                                            \
    (t).data = (unsigned char *) (s);                                \
    (t).slen = ((t).data) ? ((int) (strlen) ((char *)(t).data)) : 0; \
    (t).mlen = -1;                                                   \
}
Definition at line 370 of file rlib.h.
bvformata
#define bvformata (ret, b, fmt, lastarg)
Value:
{ \
bstring bstrtmp_b = (b); \
const char * bstrtmp_fmt = (fmt); \
int bstrtmp_r = BSTR_ERR, bstrtmp_sz = 16; \
  for (;;) { \
    va_list bstrtmp_arglist; \
    va_start (bstrtmp_arglist, lastarg); \
    bstrtmp_r = bvcformata (bstrtmp_b, bstrtmp_sz, bstrtmp_fmt, bstrtmp_arglist); \
    va_end (bstrtmp_arglist); \
    if (bstrtmp_r >= 0) { /* Everything went ok */ \
      bstrtmp_r = BSTR_OK; \
      break; \
    } else if (-bstrtmp_r <= bstrtmp_sz) { /* A real error? */ \
      bstrtmp_r = BSTR_ERR; \
      break; \
    } \
    bstrtmp_sz = -bstrtmp_r; /* Doubled or target size */ \
  } \
  ret = bstrtmp_r; \
}
Definition at line 279 of file rlib.h.
PANIC_IF
#define PANIC_IF (iostream, test, err_type, msg, ...)
Value:
do {                                                  \
    if (test) {                                         \
      fprintf(iostream,                                 \
              "FATAL -- %s:%d -- " msg "\n",            \
              __FILE__,                                 \
              __LINE__,                                 \
              ##__VA_ARGS__);                           \
      exit(err_type);                                   \
    }                                                   \
  } while (0)
Definition at line 68 of file rlib.h.
PANIC_IF_FILE_CAN_BE_READ
#define PANIC_IF_FILE_CAN_BE_READ (iostream, fname)
Value:
do {                                                                  \
    int err_codes_fd = open(fname, O_RDONLY);                           \
    PANIC_UNLESS(iostream,                                              \
                 err_codes_fd == -1,                                    \
                 STD_ERR,                                               \
                 "The file '%s' already exists",                        \
                 fname);                                                \
    if (err_codes_fd != -1) {                                           \
      PANIC_UNLESS(iostream,                                            \
                   close(err_codes_fd) == 0,                            \
                   errno,                                               \
                   "Could not close fd (%d) associated with file "      \
                   "'%s': %s",                                          \
                   err_codes_fd,                                        \
                   fname,                                               \
                   strerror(errno));                                    \
    }                                                                   \
  } while (0)
Definition at line 122 of file rlib.h.
PANIC_MEM
#define PANIC_MEM (iostream, var)
Value:
do {                                                          \
    if (var == NULL) {                                          \
      fprintf(iostream,                                         \
              "FATAL -- %s:%d -- " MEM_ERR_MSG " " #var " \n",  \
              __FILE__,                                         \
              __LINE__);                                        \
      exit(MEM_ERR);                                            \
    }                                                           \
  } while (0)
Definition at line 92 of file rlib.h.
PANIC_UNLESS
#define PANIC_UNLESS (iostream, test, err_type, msg, ...)
Value:
do {                                                          \
    if (!(test)) {                                              \
      fprintf(iostream,                                         \
              "FATAL -- %s:%d -- " msg "\n",                    \
              __FILE__,                                         \
              __LINE__,                                         \
              ##__VA_ARGS__);                                   \
      exit(err_type);                                           \
    }                                                           \
  } while (0)
Definition at line 80 of file rlib.h.
PANIC_UNLESS_FILE_CAN_BE_READ
#define PANIC_UNLESS_FILE_CAN_BE_READ (iostream, fname)
Value:
do {                                                                  \
    int err_codes_fd = open(fname, O_RDONLY);                           \
    PANIC_IF(iostream,                                                  \
             err_codes_fd == -1,                                        \
             errno,                                                     \
             "Could not read file '%s': %s",                            \
             fname,                                                     \
             strerror(errno));                                          \
    PANIC_UNLESS(iostream,                                              \
                 close(err_codes_fd) == 0,                              \
                 errno,                                                 \
                 "Could not close fd (%d) associated with file "        \
                 "'%s': %s",                                            \
                 err_codes_fd,                                          \
                 fname,                                                 \
                 strerror(errno));                                      \
  } while (0)
Definition at line 103 of file rlib.h.
rstring_data
#define rstring_data (rstr) (bdata((bstring)rstr))
Get the ->data portion of the rstring (i.e., the char* part).
Parameters
rstr We will get the data of this rstring.
Return values
char* The char* part of the rstring.
NULL The rstring is NULL.
Definition at line 3635 of file rlib.h.
rstring_format
#define rstring_format (fmt, ...) ((rstring*)bformat(fmt, __VA_ARGS__))
This is like Ruby's "apple %s" % "pie" % operator.
... initialization code ...
rstring* rstr = rstring_new("pies");
rstring* new_rstr = rstring_format("%d apple %s", 3, rstring_data(rstr));
... cleanup code ...
Parameters
fmt This is a char* format string.
... A variable number of args to put into the fmt string.
Return values
rstring* A new rstring holding the formatted string.
Note
This one doesn't take rstrings like all the rest, rather char* or ints, or floats or whatever.
Warning
If the BSTRLIB_NOVSNP macro has been set when bstrlib has been compiled the bformat function is not present. This will NOT be checked.
Todo:
Ideally, you could put rstrings straight in to plases where you have the s character and it would JustWork.
Definition at line 3659 of file rlib.h.
setInCharField
#define setInCharField (cf, idx)
Value:
{ \
  unsigned int c = (unsigned int) (idx); \
  (cf)->content[c >> LONG_LOG_BITS_QTY] |= \
    (LONG_TYPE) (1ul << (c & (LONG_BITS_QTY-1))); \
}
Definition at line 1821 of file rlib.h.
testInCharField
#define testInCharField (cf, c)
Value:
((cf)->content[(c) >> LONG_LOG_BITS_QTY] & \
                             (((long)1) << ((c) & (LONG_BITS_QTY-1))))
Definition at line 1819 of file rlib.h.
Function Documentation
bfromcstr_check_length()
bstring bfromcstr_check_length (const char * str)
Like bfromcstr but checks that the strlen is not >= INT_MAX.
Returns
the bstring or NULL if there were errors or the string length is longer than INT_MAX.
Author
mooreryan
Date
2018-05-27
Definition at line 662 of file rlib.h.
{
   bstring b;
   int i;
   size_t j;
   if (str == NULL) return NULL;
   j = (strnlen) (str, INT_MAX);
   if (j == INT_MAX) return NULL;
   i = snapUpSize ((int) (j + (2 - (j != 0))));
   if (i <= (int) j) return NULL;
   b = (bstring) bstr__alloc (sizeof (struct tagbstring));
   if (NULL == b) return NULL;
   b->slen = (int) j;
   if (NULL == (b->data = (unsigned char *) bstr__alloc (b->mlen = i))) {
     bstr__free (b);
     return NULL;
   }
   bstr__memcpy (b->data, str, j+1);
   return b;
 }
rfile_basename()
rstring * rfile_basename (const rstring * fname)
Return the basename of a file.
Parameters
fname An rstring with the file name.
Return values
rstring* A valid rstring containing the basename of the file.
NULL The input rstring is invalid or there was an error.
Warning
The caller must free the result.
Definition at line 4720 of file rlib.h.
References rstring_bad, and rstring_length().
 {
   if (rstring_bad(fname)) { return NULL; }
   int i                = 0;
   int i_last_fs        = 0;
   int i_basename_start = 0;
   int char_at = 0;
   int slen         = rstring_length(fname);
   if (slen == RERROR) { return NULL; }
   int basename_len = 0;
   rstring* basename = NULL;
   /* If we are passed an empty string.... */
   if (slen == 0) {
     basename = rstring_new("");
     if (rstring_bad(basename)) { return NULL; }
     return basename;
   }
   i = index_before_first_trailing_file_separator(fname);
   if (i < 0) {
     /* This can only happen for names like "////" */
     char_at = rstring_char_at(fname, 0);
     if (char_at == RERROR || char_at != RFILE_SEPARATOR) {
       return NULL;
     }
     basename = rstring_new(RFILE_SEPARATOR_STR);
     if (rstring_bad(basename)) { return NULL; }
   }
   else {
     /* The current index points to the char just before the first of
        trailing RFILE_SEPARATOR chars if there are any, so the trailing
        RFILE_SEPARATORs begin at i + 1. */
     i_last_fs = i + 1;
     for (i = i_last_fs - 1; i >= 0; --i) {
       char_at = rstring_char_at(fname, i);
       if (char_at == RFILE_SEPARATOR) {
         break;
       }
     }
     i_basename_start = i + 1;
     basename_len     = i_last_fs - i_basename_start;
     basename = rstring_slice(fname, i_basename_start, basename_len);
     if (rstring_bad(basename)) { return NULL; }
   }
   return basename;
 }
rfile_basename2()
rstring * rfile_basename2 (const rstring * fname, const rstring * extname)
Return the basename of a file, with the extname stripped off.
Parameters
fname An rstring with the file name.
extname An rstring with the extension to strip off.
Return values
rstring* A valid rstring containing the basename of the file, without the extension.
NULL The input rstring is invalid or there was an error.
Warning
The caller must free the result.
Definition at line 4790 of file rlib.h.
References rfile_basename(), rstring_bad, and rstring_eql_cstr().
 {
   if (rstring_bad(fname)) { return NULL; }
   if (rstring_bad(extname)) { return NULL; }
   rstring* basename = rfile_basename(fname);
   if (rstring_bad(basename)) { return NULL; }
   int retval = 0;
   int i = 0;
   int j = 0;
   char extchar = 0;
   char basechar = 0;
   /* If it is empty, just return the basename */
   retval = rstring_eql_cstr(extname, "");
   if (retval == RTRUE) {
     return basename;
   }
   else if (retval == RERROR) {
     rstring_free(basename);
     return NULL;
   }
   /* Now we need to strip off the extname */
   int basename_len = rstring_length(basename);
   if (basename_len == RERROR) { free(basename); return NULL; }
   int extname_len = rstring_length(extname);
   if (extname_len == RERROR) { free(basename); return NULL; }
   /* First, check if the ext is actually present. */
   for (i = 0; i < extname_len; ++i) {
     /* The corresponding index in the basename */
     j = basename_len - extname_len + i;
     extchar = rstring_char_at(extname, i);
     if (extchar == RERROR) { rstring_free(basename); return NULL; }
     basechar = rstring_char_at(basename, j);
     if (basechar == RERROR) { rstring_free(basename); return NULL; }
     if (extchar != basechar) {
       /* The extname is not present in the fname */
       return basename;
     }
   }
   /* If we've gotten here, then you can strip off extname. */
   rstring* new_basename = rstring_slice(basename,
                                         0,
                                         basename_len - extname_len);
   if (rstring_bad(new_basename)) { rstring_free(basename); return NULL; }
   rstring_free(basename);
   return new_basename;
 }
rfile_basename2_cstr()
rstring * rfile_basename2_cstr (const rstring * fname, const char * extname)
Return the basename of a file, with the extname stripped off. It's like rfile_basename2() but takes a char* for the extname.
Parameters
fname An rstring with the file name.
extname A char* with the extension to strip off.
Return values
rstring* A valid rstring containing the basename of the file, without the extension.
NULL The input rstring is invalid or there was an error.
Warning
The caller must free the result.
Definition at line 4861 of file rlib.h.
References rfile_basename2(), rstring_bad, rstring_free(), and rstring_new().
 {
   if (rstring_bad(fname)) { return NULL; }
   if (extname == NULL) { return NULL; }
   rstring* ext = rstring_new(extname);
   if (rstring_bad(ext)) { return NULL; }
   rstring* base = rfile_basename2(fname, ext);
   if (rstring_bad(base)) { return NULL; }
   rstring_free(ext);
   return base;
 }
rfile_dirname()
rstring * rfile_dirname (const rstring * fname)
Return the dirname of a file.
Returns all components of the filename given in file_name except the last one (after first stripping trailing separators).
Parameters
fname An rstring with the file name.
Return values
rstring* A valid rstring containing the directory of the file.
NULL The input rstring is invalid or there was an error.
Warning
The caller must free the result.
Definition at line 4890 of file rlib.h.
References rstring_bad, and rstring_length().
 {
   if (rstring_bad(fname)) { return NULL; }
   int i = 0;
   int char_at = 0;
   int slen = rstring_length(fname);
   if (slen == RERROR) { return NULL; }
   rstring* dirname = NULL;
   if (slen == 0) {
     dirname = rstring_new("");
     if (rstring_bad(dirname)) { return NULL; }
     return dirname;
   }
   i = index_of_last_file_separator(fname);
   char_at = rstring_char_at(fname, 0);
   if (char_at == RERROR) { return NULL; }
   if (i < 0 && char_at == RFILE_SEPARATOR) {
     /* Filenames like: "/////" */
     dirname = rstring_new(RFILE_SEPARATOR_STR);
     if (rstring_bad(dirname)) { return NULL; }
   }
   else if (i < 0) {
     /* Filenames like: "apple" */
     dirname = rstring_new(".");
     if (rstring_bad(dirname)) { return NULL; }
   }
   else {
     /* There was a basename.  Now we need to make sure that there
        aren't a bunch of fs chars right in a row. */
     i = index_of_last_file_separator_from_pos(fname, i);
     if (i <= 0) {
       /* This could happen for filenames like: "/////apple" or "/apple" */
       dirname = rstring_new(RFILE_SEPARATOR_STR);
       if (rstring_bad(dirname)) { return NULL; }
     }
     else {
       int i_before_last_fs = i - 1;
       dirname = rstring_slice(fname, 0, i_before_last_fs + 1);
       if (rstring_bad(dirname)) { return NULL; }
     }
   }
   return dirname;
 }
rfile_exist()
int rfile_exist (const rstring * fname)
Tells whether a file exists or not (i.e., stat is successful).
Parameters
fname An rstring with the filename to check.
Return values
RTRUE The file exists
RFALSE The file does not exist
RERROR fname is invalid or there was an error.
Definition at line 4620 of file rlib.h.
References rstring_bad.
 {
   if (rstring_bad(fname)) { return RERROR; }
   int ret_val = 0;
   char* cfname = bstr2cstr(fname, '?');
   if (cfname == NULL) { return RERROR; }
   struct stat st;
   ret_val = stat(cfname, &st);
   free(cfname);
   if (ret_val < 0) {
     return RFALSE;
   }
   else {
     return RTRUE;
   }
 }
rfile_extname()
rstring * rfile_extname (const rstring * fname)
Return the extension of a file.
Parameters
fname An rstring with the file name.
Return values
rstring* A valid rstring containing the extension of the file.
NULL The input rstring is invalid or there was an error.
Warning
The caller must free the result.
Definition at line 4955 of file rlib.h.
References rfile_basename(), rstring_bad, and rstring_length().
 {
   if (rstring_bad(fname)) { return NULL; }
   int basename_len = 0;
   int last_dot = 0;
   rstring* basename = NULL;
   rstring* extname  = NULL;
   basename     = rfile_basename(fname);
   if (rstring_bad(basename)) { return NULL; }
   basename_len = rstring_length(basename);
   if (basename_len == RERROR) { return NULL; }
   last_dot = bstrrchr((const_bstring)basename, '.');
   if (/* No '.' was found */
       (last_dot == BSTR_ERR) ||
       /* The last dot was the first char: ".profile" */
       (last_dot == 0) ||
       /* If the dot was the last thing in the fname: "foo." */
       (last_dot == basename_len - 1)) {
     extname = rstring_new("");
     if (rstring_bad(extname)) { return NULL; }
   }
   else {
     extname = rstring_slice(basename, last_dot, basename_len);
     if (rstring_bad(extname)) { return NULL; }
   }
   rstring_free(basename);
   return extname;
 }
rfile_is_directory()
int rfile_is_directory (const rstring * fname)
Tells whether the named directory exists.
Parameters
fname An rstring with the dirname to check.
Return values
RTRUE The dir exists
RFALSE The dir does not exist
RERROR The input rstring is invalid or there was an error.
Todo:
Ruby also returns true if dir is a symlink that points at a directory.
Definition at line 4653 of file rlib.h.
References rstring_bad.
 {
   if (rstring_bad(fname)) { return RERROR; }
   int ret_val = 0;
   char* cfname = bstr2cstr(fname, '?');
   if (cfname == NULL) { return RERROR; }
   struct stat st;
   ret_val = stat(cfname, &st);
   bcstrfree(cfname);
   if (ret_val < 0 || !S_ISDIR(st.st_mode)) {
     return RFALSE;
   }
   else {
     return RTRUE;
   }
 }
rfile_is_file()
int rfile_is_file (const rstring * fname)
Tells whether the named file exists and is a regular file.
Parameters
fname An rstring with the dirname to check.
Return values
RTRUE The file exists
RFALSE The file does not exist
RERROR The input rstring is invalid or there was an error.
Todo:
Ruby also returns true if file is a symlink that points at a file.
Definition at line 4687 of file rlib.h.
References rstring_bad.
 {
   if (rstring_bad(fname)) { return RERROR; }
   int ret_val = 0;
   char* cfname = bstr2cstr(fname, '?');
   if (cfname == NULL) { return RERROR; }
   struct stat st;
   ret_val = stat(cfname, &st);
   bcstrfree(cfname);
   if (ret_val < 0 || !S_ISREG(st.st_mode)) {
     return RFALSE;
   }
   else {
     return RTRUE;
   }
 }
rfile_join()
rstring * rfile_join (rstring_array * rary)
Returns a new path by joining the strings using the RFILE_SEPARATOR.
Parameters
rary An rstring_array with the rstrings to join.
Return values
rstring* A valid rstring with the input strings all joined up.
NULL The input rstring_array is invalid or there was an error.
Note
Ruby has some weird behavior here where it sometimes keeps double // and sometimes it doesn't. It doesn't in cases where there is more than one slash in a single one of the input strings. Regardless, the function is for building paths so in that spirit, we don't want those double separators anyways. Soooo, it differs from Ruby in these cases.
Warning
The caller must free the result.
Todo:
the no_doubles path will use a bit more memory than it actually needs if some of the double // are removed.
Definition at line 5010 of file rlib.h.
References rstring_array_bad.
 {
   if (rstring_array_bad(rary)) { return NULL; }
   int i = 0;
   int j = 0;
   int len = 0;
   int char_at = 0;
   /* Check if any of the rstrings are null */
   for (i = 0; i < rary->qty; ++i) {
     if (rstring_array_get(rary, i) == NULL) { return NULL; }
   }
   rstring* path = NULL;
   rstring* sep = NULL;
   int c = 0;
   int c_minus_1 = 0;
   sep = rstring_new(RFILE_SEPARATOR_STR);
   if (rstring_bad(sep)) { return NULL; }
   /* Clean up path if early exit from here down. */
   path = rstring_array_join(rary, sep);
   if (rstring_bad(path)) { return NULL; }
   rstring_free(sep);
   /* If it's empty, there are no doubles. */
   len = rstring_length(path);
   if (len == RERROR) { rstring_free(path); return NULL; }
   if (len == 0) { return path; }
   /* Remove doubles of file sep. */
   /* Clean up no_doubles if early exit from here down. */
   char* no_doubles = malloc(sizeof(char) * ((len + 1)));
   if (no_doubles == NULL) { rstring_free(path); return NULL; }
   j = 0;
   char_at = rstring_char_at(path, 0);
   if (char_at == RERROR) { rstring_free(path); free(no_doubles); return NULL; }
   no_doubles[j++] = char_at;
   for (i = 1; i < len; ++i) {
     c = rstring_char_at(path, i);
     c_minus_1 = rstring_char_at(path, i - 1);
     if (c == RERROR || c_minus_1 == RERROR) {
       rstring_free(path); free(no_doubles); return NULL;
     }
     if (c != RFILE_SEPARATOR || c_minus_1 != RFILE_SEPARATOR) {
       no_doubles[j++] = c;
     }
   }
   no_doubles[j] = '\0';
   rstring_free(path);
   /* Rewrite the path */
   path = rstring_new(no_doubles);
   if (rstring_bad(path)) { free(no_doubles); return NULL; }
   free(no_doubles);
   return path;
 }
rstring_char_at()
int rstring_char_at (const rstring * rstr, int idx)
Return the char at given position.
Parameters
rstr Not modified.
index Get the char at this index in rstr.
Return values
char The idx'th character of the rstring.
RERROR If The input rstring is invalid or there was an error.
Definition at line 4390 of file rlib.h.
References rstring_bad.
 {
   if (rstring_bad(rstr)) { return RERROR; }
   return bchare(rstr, idx, RERROR);
 }
rstring_chomp()
rstring * rstring_chomp (const rstring * rstr)
Make a new string with final trailing record separator removed.
Will remove \n, \r, and \r\n. If there are multiple line separators at the end of the string, only the last one will be removed.
Parameters
rstr An rstring. (Not modified.)
Return values
rstring* A valid rstring without the last record separator.
NULL The input rstring is invalid or there was an error.
Warning
The caller must free the result.
Definition at line 3782 of file rlib.h.
References rstring_bad, and rstring_length().
 {
   if (rstring_bad(rstr)) { return NULL; }
   int len = rstring_length(rstr);
   if (len == RERROR) { return NULL; }
   int c_last = rstring_char_at(rstr, len - 1);
   if (c_last == RERROR) { return NULL; }
   if (c_last == '\r') {
     return rstring_slice(rstr, 0, len-1);
   }
   else if (c_last == '\n' && rstring_char_at(rstr, len - 2) == '\r') {
     return rstring_slice(rstr, 0, len-2);
   }
   else if (c_last == '\n') {
     return rstring_slice(rstr, 0, len-1);
   }
   else {
     return rstring_copy(rstr);
   }
 }
rstring_copy()
rstring * rstring_copy (const rstring * rstr)
Copies the rstring.
Parameters
rstr The rstring to copy. (Not modified.)
Return values
rstring* A valid rstring copy.
NULL The input rstring is invalid or there was an error.
Warning
The caller must free the result.
Definition at line 3748 of file rlib.h.
References rstring_bad.
 {
   if (rstring_bad(rstr)) { return NULL; }
   return (rstring*)bstrcpy((const_bstring)rstr);
 }
rstring_downcase()
rstring * rstring_downcase (const rstring * rstr)
Return a copy of rstr with everything lowercase.
Parameters
rstr The rstring to downcase. (Not modified.)
Return values
rstring* A valid rstring copy of rstr with all chars lowercase.
NULL The input rstring is invalid or there was an error.
Warning
The caller must free the result.
Definition at line 3817 of file rlib.h.
References rstring_bad, and rstring_length().
 {
   if (rstring_bad(rstr)) { return NULL; }
   int len = rstring_length(rstr);
   if (len == RERROR) { return NULL; }
   if (len == 0) { return rstring_new(""); }
   rstring* new_rstr = rstring_copy(rstr);
   if (new_rstr == NULL) { return NULL; }
   int val = btolower(new_rstr);
   if (val == RERROR) { return NULL; }
   return new_rstr;
 }
rstring_eql()
int rstring_eql (const rstring * rstr1, const rstring * rstr2)
Two strings are equal if they have the same length and content.
Parameters
rstr1 Not modified.
rstr2 Not modified.
Return values
RTRUE The rstrings are equal.
RFALSE The rstrings are not equal.
RERROR The rstr1 or rstr2 is invalid or there was an error.
Note
This differs from ruby in that you can't just check for true or false, you must check for 1 or 0 as RERROR signals an error.
Definition at line 4163 of file rlib.h.
References rstring_bad.
 {
   if (rstring_bad(rstr1)) { return RERROR; }
   if (rstring_bad(rstr2)) { return RERROR; }
   int val = biseq((const_bstring)rstr1, (const_bstring)rstr2);
   if (val == 1) {
     return RTRUE;
   }
   else if (val == 0) {
     return RFALSE;
   }
   else {
     return RERROR;
   }
 }
rstring_eql_cstr()
int rstring_eql_cstr (const rstring * rstr, const char * cstr)
Two strings are equal if they have the same length and content.
Parameters
rstr Not modified.
cstr Not modified.
Return values
RTRUE The strings are equal.
RFALSE The strings are not equal.
RERROR The rstr or cstring is invalid or there was an error.
Note
This differs from ruby in that you can't just check for true or false, you must check for 1 or 0 as RERROR signals an error.
Definition at line 4194 of file rlib.h.
References rstring_bad.
 {
   if (rstring_bad(rstr)) { return RERROR; }
   if (cstr == NULL) { return RERROR; }
   int val = biseqcstr((const_bstring)rstr, cstr);
   if (val == 1) {
     return RTRUE;
   }
   else if (val == 0) {
     return RFALSE;
   }
   else {
     return RERROR;
   }
 }
rstring_free()
int rstring_free (rstring * rstr)
Free the rstring.
Parameters
rstr An rstring to free.
Return values
RERROR If there was an error.
ROKAY If there were no errors.
Definition at line 3764 of file rlib.h.
 {
   return bdestroy((bstring)rstr);
 }
rstring_gsub()
rstring * rstring_gsub (const rstring * rstr, const rstring * pattern, const rstring * replacement)
Return a copy of rstr with all occurrences of pattern substituted for the value of replacement.
rstring* rstr = rstring_new("aabaAb");
rstring* pattern = rstring_new("a");
rstring* replacement = rstring_new("aa");
rstring* expected = rstring_new("aaaabaaAb")
rstring* actual = rstring_gsub(rstr, pattern, replacement);
assert(rstring_eql(expected, actual) == RTRUE);
... code to free variables here ...
Parameters
rstr The rstring for replacing.
pattern The rstring pattern to search for.
replacement The rstring to replace with.
Return values
rstring* A valid rstring with the appropriate replacements.
NULL Any of the args are invalid or if there were errors.
Note
It differs from ruby in that pattern must have length > 0 (i.e., be a non-empty string. Things get pretty weird in Ruby when the pattern is an empty string....
Definition at line 3862 of file rlib.h.
References rstring_bad, and rstring_copy().
 {
   if (rstring_bad(rstr)) { return NULL; }
   if (rstring_bad(pattern)) { return NULL; }
   if (rstring_bad(replacement)) { return NULL; }
   rstring* copy = rstring_copy(rstr);
   if (rstring_bad(copy)) { return NULL; }
   int start_pos = 0;
   int val = bfindreplace((bstring)copy,
                          (const_bstring)pattern,
                          (const_bstring)replacement,
                          start_pos);
   if (val == BSTR_ERR) { rstring_free(copy); return NULL; }
   return copy;
 }
rstring_include()
int rstring_include (const rstring * rstr, const rstring * substring)
Tells whether rstr contains the other rstring.
Parameters
rstr The rstring to search in.
substring The rstring to search for.
Return values
RTRUE The substring is present.
RFALSE The substring is not present.
RERROR Either input rstring is invalid.
Definition at line 4223 of file rlib.h.
References rstring_bad.
 {
   if (rstring_bad(rstr)) { return RERROR; }
   if (rstring_bad(substring)) { return RERROR; }
   int start_pos = 0;
   int val = binstr(rstr, start_pos, substring);
   if (val == BSTR_ERR) {
     /* It wasn't found. */
     return RFALSE;
   }
   else {
     return RTRUE;
   }
 }
rstring_index()
int rstring_index (const rstring * rstr, const rstring * substring)
Tells the first occurence of substring in rstr.
Parameters
rstr The rstring to search in.
substring The rstring to search for.
Return values
index The index of the first occurence of substring in rstr.
RERROR Either input rstrings are invalid or the substring was not found.
Todo:
Need a better way to handle errors as not found and error would be the same thing for this function.
Definition at line 4272 of file rlib.h.
References rstring_bad.
 {
   if (rstring_bad(rstr)) { return RERROR; }
   if (rstring_bad(substring)) { return RERROR; }
   int start_pos = 0;
   int val = binstr(rstr, start_pos, substring);
   if (val == BSTR_ERR) {
     /* It wasn't found. */
     return RERROR;
   }
   else {
     return val;
   }
 }
rstring_index_offset()
int rstring_index_offset (const rstring * rstr, const rstring * substring, int offset)
Tells the first occurence (starting at offset) of substring in rstr.
Parameters
rstr The rstring to search in.
substring The rstring to search for.
offset The index in rstr to start the search from.
Return values
index The index of the first occurence (>= index) of substring in rstr.
RERROR Either input rstrings are invalid or the substring was not found in the string after the offset/index.
Todo:
Need a better way to handle errors as not found and error would be the same thing for this function.
Definition at line 4322 of file rlib.h.
References rstring_bad.
 {
   if (rstring_bad(rstr)) { return RERROR; }
   if (rstring_bad(substring)) { return RERROR; }
   int val = binstr(rstr, offset, substring);
   if (val == BSTR_ERR) {
     /* It wasn't found. */
     return RERROR;
   }
   else {
     return val;
   }
 }
rstring_length()
int rstring_length (const rstring * rstr)
Returns the length of the rstring.
Parameters
rstr Not modified.
Return values
length The length of the rstring.
RERROR The input rstring is invalid or there was an error.
Definition at line 4367 of file rlib.h.
References rstring_bad.
 {
   if (rstring_bad(rstr)) { return RERROR; }
   return blengthe(rstr, RERROR);
 }
rstring_lstrip()
rstring * rstring_lstrip (const rstring * rstr)
Returns a copy of rstr with leading whitespace removed.
Parameters
rstr The rstring to strip.
Return values
rstring* A valid copy of rstr with leading whitespace stripped.
NULL The input rstring is invalid or there was an error.
Warning
The caller must free the result.
Todo:
Lots of code duplication with strip(), lstrip(), and rstrip().
Definition at line 4030 of file rlib.h.
References rstring_bad, and rstring_length().
 {
   if (rstring_bad(rstr)) { return NULL; }
   int len = rstring_length(rstr);
   if (len == RERROR) { return NULL; }
   if (len == 0) { return rstring_new(""); }
   rstring* copy = rstring_copy(rstr);
   if (rstring_bad(copy)) { return NULL; }
   int val = bltrimws(copy);
   if (val == BSTR_ERR) { rstring_free(copy); return NULL; }
   return copy;
 }
rstring_new()
rstring * rstring_new (const char * cstr)
Make a new rstring from c string.
Parameters
cstr Char array to convert to rstring. (Not modified.)
Return values
rstring* A valid rstring.
NULL The cstr is NULL, the length of cstr >= INT_MAX, or there were errors creating the rstring.
Warning
The caller must free the result.
Definition at line 3726 of file rlib.h.
References bfromcstr_check_length(), and rstring_bad.
 {
   if (cstr == NULL) { return NULL; }
   rstring* rstr = (rstring*)bfromcstr_check_length(cstr);
   if (rstring_bad(rstr)) { return NULL; }
   return rstr;
 }
rstring_reverse()
rstring * rstring_reverse (const rstring * rstr)
Returns a new rstring with the characters from rstr in reverse order.
Parameters
rstr The rstring for reversing.
Return values
rstring* A valid rstring copy of rstr with chars reversed.
NULL The input rstring was invalid or there was an error.
Warning
The caller must free the result.
Definition at line 4059 of file rlib.h.
References rstring_bad, and rstring_copy().
 {
   if (rstring_bad(rstr)) { return NULL; }
   rstring* copy = rstring_copy(rstr);
   if (rstring_bad(copy)) { return NULL; }
   /* From bstraux.c */
   int i, n, m;
   unsigned char t;
   n = copy->slen;
   if (2 <= n) {
     m = ((unsigned)n) >> 1;
     n--;
     for (i=0; i < m; i++) {
       t = copy->data[n - i];
       copy->data[n - i] = copy->data[i];
       copy->data[i] = t;
     }
   }
   return copy;
 }
rstring_rstrip()
rstring * rstring_rstrip (const rstring * rstr)
Returns a copy of rstr with trailing whitespace removed.
Parameters
rstr The rstring to strip.
Return values
rstring* A valid copy of rstr with trailing whitespace stripped.
NULL The input rstring is invalid or there was an error.
Warning
The caller must free the result.
Todo:
Lots of code duplication with strip(), lstrip(), and rstrip().
Definition at line 4097 of file rlib.h.
References rstring_bad, and rstring_length().
 {
   if (rstring_bad(rstr)) { return NULL; }
   int len = rstring_length(rstr);
   if (len == RERROR) { return NULL; }
   if (len == 0) { return rstring_new(""); }
   rstring* copy = rstring_copy(rstr);
   if (rstring_bad(copy)) { return NULL; }
   int val = brtrimws(copy);
   if (val == BSTR_ERR) { rstring_free(copy); return NULL; }
   return copy;
 }
rstring_slice()
rstring * rstring_slice (const rstring * rstr, int index, int length)
Return a substring starting at index of a given length (clamped by the end of rstr).
Parameters
rstr The rstring that we want to substring. (Not modified.)
index The starting index of the substring.
length The length of the substring.
Return values
rstring* A valid rstring containing the specified substring.
NULL The input rstring is invalid or there was an error.
Note
There is a bit of weird behavior if the index is the length of the rstring, an empty string will be returned rather than NULL, which is the behavior of rstring_slice1. It is this way to match the Ruby behavior.
Warning
The caller must free the result.
Definition at line 3960 of file rlib.h.
References rstring_bad, and rstring_length().
 {
   if (rstring_bad(rstr)) { return NULL; }
   int len = rstring_length(rstr);
   if (len == RERROR) { return NULL; }
   int idx = index;
   /* Special weird ruby case. */
   if (index == len) {
     return rstring_new("");
   }
   /* Negative indices count back from the end. */
   if (index < 0) {
     idx = len - idx - 1;
   }
   if (idx > len || length < 0) {
     return NULL;
   }
   return (rstring*)bmidstr((bstring)rstr, index, length);
 }
rstring_slice1()
rstring * rstring_slice1 (const rstring * rstr, int index)
Gives the char at index but as an rstring.
Parameters
rstr The rstring that we want to substring. (Not modified.)
index The starting index of the substring.
Return values
NULL The rstring is invalid, the index < 0 or >= rstr length, or there was an error.
Returns
A single character rstring or NULL if there were errors.
Warning
The caller must free the result.
Definition at line 3934 of file rlib.h.
References rstring_bad, and rstring_length().
 {
   if (rstring_bad(rstr)) { return NULL; }
   if (index < 0 || index >= rstring_length(rstr)) {
     return NULL;
   }
   return bmidstr(rstr, index, 1);
 }
rstring_strip()
rstring * rstring_strip (const rstring * rstr)
Returns a copy of rstr with leading and trailing whitespace removed.
Parameters
rstr The rstring to strip.
Return values
rstring* A valid copy of rstr with whitespace stripped.
NULL The input rstring is invalid or there was an error.
Warning
The caller must free the result.
Todo:
Lots of code duplication with strip(), lstrip(), and rstrip().
Definition at line 3999 of file rlib.h.
References rstring_bad, and rstring_length().
 {
   if (rstring_bad(rstr)) { return NULL; }
   int len = rstring_length(rstr);
   if (len == RERROR) { return NULL; }
   if (len == 0) { return rstring_new(""); }
   rstring* copy = rstring_copy(rstr);
   if (rstring_bad(copy)) { return NULL; }
   int val = btrimws(copy);
   if (val == BSTR_ERR) { rstring_free(copy); return NULL; }
   return copy;
 }
rstring_upcase()
rstring * rstring_upcase (const rstring * rstr)
Return a copy of rstr with everything uppercase.
Parameters
rstr The rstring to upcase. (Not modified.)
Return values
rstring* A valid rstring copy of rstr with all chars uppercase.
NULL The input rstring is invalid or there was an error.
Warning
The caller must free the result.
Definition at line 4128 of file rlib.h.
References rstring_bad, and rstring_length().
 {
   if (rstring_bad(rstr)) { return NULL; }
   int len = rstring_length(rstr);
   if (len == RERROR) { return NULL; }
   if (len == 0) { return rstring_new(""); }
   rstring* new_rstr = rstring_copy(rstr);
   if (new_rstr == NULL) { return NULL; }
   int val = btoupper(new_rstr);
   if (val == RERROR) { return NULL; }
   return new_rstr;
 }