Ruby-like C: src/rstring.c File Reference
rstring.c File Reference
File containing functions like those found in Ruby's String class.
#include <assert.h>
#include <stdarg.h>
#include <limits.h>
#include "bstrlib.h"
#include "rstring.h"
#include "rlib.h"
Functions
rstring * rstring_new (const char *cstr)
Make a new rstring from c string.
rstring * rstring_copy (const rstring *rstr)
Copies the rstring.
int rstring_free (rstring *rstr)
Free the rstring.
rstring * rstring_chomp (const rstring *rstr)
Make a new string with final trailing record separator removed.
rstring * rstring_downcase (const rstring *rstr)
Return a copy of rstr with everything lowercase.
rstring * rstring_slice1 (const rstring *rstr, int index)
Gives the char at index but as an rstring.
rstring * rstring_slice (const rstring *rstr, int index, int length)
Return a substring starting at index of a given length (clamped by the end of rstr).
rstring * rstring_upcase (const rstring *rstr)
Return a copy of rstr with everything uppercase.
int rstring_eql (const rstring *rstr1, const rstring *rstr2)
Two strings are equal if they have the same length and content.
int rstring_length (const rstring *rstr)
Returns the length of the rstring.
int rstring_char_at (const rstring *rstr, int idx)
Return the char at given position.
rstring_array * rstring_array_new ()
int rstring_array_push_rstr (rstring_array *rary, rstring *rstr)
int rstring_array_push_cstr (rstring_array *rary, char *cstr)
rstring * rstring_array_get (rstring_array *rary, int index)
int rstring_array_free (rstring_array *rary)
rstring * rstring_array_join (rstring_array *rstrings, const rstring *sep)
rstring_array * rstring_split (rstring *rstr, const rstring *sep)
Detailed Description
File containing functions like those found in Ruby's String class.
Author
Ryan Moore
See also
https://ruby-doc.org/core-2.5.0/String.html
Definition in file rstring.c.
Function Documentation
rstring_char_at()
int rstring_char_at (const rstring * rstr, int idx)
Return the char at given position.
Parameters
rstr Not modified.
index Get the char at this index in rstr.
Return values
char The idx'th character of the rstring.
RERROR If The input rstring is invalid or there was an error.
Definition at line 300 of file rstring.c.
 {
   if (rstring_bad(rstr)) { return RERROR; }
   return bchare(rstr, idx, RERROR);
 }
rstring_chomp()
rstring* rstring_chomp (const rstring * rstr)
Make a new string with final trailing record separator removed.
Will remove \n, \r, and \r\n. If there are multiple line separators at the end of the string, only the last one will be removed.
Parameters
rstr An rstring. (Not modified.)
Return values
rstring* A valid rstring without the last record separator.
NULL The input rstring is invalid or there was an error.
Warning
The caller must free the result.
Definition at line 84 of file rstring.c.
References rstring_char_at(), rstring_copy(), rstring_length(), and rstring_slice().
 {
   if (rstring_bad(rstr)) { return NULL; }
   int len = rstring_length(rstr);
   if (len == RERROR) { return NULL; }
   int c_last = rstring_char_at(rstr, len - 1);
   if (c_last == RERROR) { return NULL; }
   if (c_last == '\r') {
     return rstring_slice(rstr, 0, len-1);
   }
   else if (c_last == '\n' && rstring_char_at(rstr, len - 2) == '\r') {
     return rstring_slice(rstr, 0, len-2);
   }
   else if (c_last == '\n') {
     return rstring_slice(rstr, 0, len-1);
   }
   else {
     return rstring_copy(rstr);
   }
 }
rstring_copy()
rstring* rstring_copy (const rstring * rstr)
Copies the rstring.
Parameters
rstr The rstring to copy. (Not modified.)
Return values
rstring* A valid rstring copy.
NULL The input rstring is invalid or there was an error.
Warning
The caller must free the result.
Definition at line 50 of file rstring.c.
 {
   if (rstring_bad(rstr)) { return NULL; }
   return (rstring*)bstrcpy((const_bstring)rstr);
 }
rstring_downcase()
rstring* rstring_downcase (const rstring * rstr)
Return a copy of rstr with everything lowercase.
Parameters
rstr The rstring to downcase. (Not modified.)
Return values
rstring* A valid rstring copy of rstr with all chars lowercase.
NULL The input rstring is invalid or there was an error.
Warning
The caller must free the result.
Definition at line 119 of file rstring.c.
References rstring_copy(), rstring_length(), and rstring_new().
 {
   if (rstring_bad(rstr)) { return NULL; }
   int len = rstring_length(rstr);
   if (len == RERROR) { return NULL; }
   if (len == 0) { return rstring_new(""); }
   rstring* new_rstr = rstring_copy(rstr);
   if (new_rstr == NULL) { return NULL; }
   int val = btolower(new_rstr);
   if (val == RERROR) { return NULL; }
   return new_rstr;
 }
rstring_eql()
int rstring_eql (const rstring * rstr1, const rstring * rstr2)
Two strings are equal if they have the same length and content.
Parameters
rstr1 Not modified.
rstr2 Not modified.
Return values
RTRUE The rstrings are equal.
RFALSE The rstrings are not equal.
RERROR The rstr1 or rstr2 is invalid or there was an error.
Note
This differs from ruby in that you can't just check for true or false, you must check for 1 or 0 as RERROR signals an error.
Definition at line 250 of file rstring.c.
 {
   if (rstring_bad(rstr1)) { return RERROR; }
   if (rstring_bad(rstr2)) { return RERROR; }
   int val = biseq((const_bstring)rstr1, (const_bstring)rstr2);
   if (val == 1) {
     return RTRUE;
   }
   else if (val == 0) {
     return RFALSE;
   }
   else {
     return RERROR;
   }
 }
rstring_free()
int rstring_free (rstring * rstr)
Free the rstring.
Parameters
rstr An rstring to free.
Return values
RERROR If there was an error.
ROKAY If there were no errors.
Definition at line 66 of file rstring.c.
 {
   return bdestroy((bstring)rstr);
 }
rstring_length()
int rstring_length (const rstring * rstr)
Returns the length of the rstring.
Parameters
rstr Not modified.
Return values
length The length of the rstring.
RERROR The input rstring is invalid or there was an error.
Definition at line 277 of file rstring.c.
 {
   if (rstring_bad(rstr)) { return RERROR; }
   return blengthe(rstr, RERROR);
 }
rstring_new()
rstring* rstring_new (const char * cstr)
Make a new rstring from c string.
Parameters
cstr Char array to convert to rstring. (Not modified.)
Return values
rstring* A valid rstring.
NULL The cstr is NULL, the length of cstr >= INT_MAX, or there were errors creating the rstring.
Warning
The caller must free the result.
Definition at line 28 of file rstring.c.
 {
   if (cstr == NULL) { return NULL; }
   rstring* rstr = (rstring*)bfromcstr_check_length(cstr);
   if (rstring_bad(rstr)) { return NULL; }
   return rstr;
 }
rstring_slice()
rstring* rstring_slice (const rstring * rstr, int index, int length)
Return a substring starting at index of a given length (clamped by the end of rstr).
Parameters
rstr The rstring that we want to substring. (Not modified.)
index The starting index of the substring.
length The length of the substring.
Return values
rstring* A valid rstring containing the specified substring.
NULL The input rstring is invalid or there was an error.
Note
There is a bit of weird behavior if the index is the length of the rstring, an empty string will be returned rather than NULL, which is the behavior of rstring_slice1. It is this way to match the Ruby behavior.
Warning
The caller must free the result.
Definition at line 177 of file rstring.c.
References rstring_length(), and rstring_new().
 {
   if (rstring_bad(rstr)) { return NULL; }
   int len = rstring_length(rstr);
   if (len == RERROR) { return NULL; }
   int idx = index;
   /* Special weird ruby case. */
   if (index == len) {
     return rstring_new("");
   }
   /* Negative indices count back from the end. */
   if (index < 0) {
     idx = len - idx - 1;
   }
   if (idx > len || length < 0) {
     return NULL;
   }
   return (rstring*)bmidstr((bstring)rstr, index, length);
 }
rstring_slice1()
rstring* rstring_slice1 (const rstring * rstr, int index)
Gives the char at index but as an rstring.
Parameters
rstr The rstring that we want to substring. (Not modified.)
index The starting index of the substring.
Return values
NULL The rstring is invalid, the index < 0 or >= rstr length, or there was an error.
Returns
A single character rstring or NULL if there were errors.
Warning
The caller must free the result.
Definition at line 151 of file rstring.c.
References rstring_length().
 {
   if (rstring_bad(rstr)) { return NULL; }
   if (index < 0 || index >= rstring_length(rstr)) {
     return NULL;
   }
   return bmidstr(rstr, index, 1);
 }
rstring_upcase()
rstring* rstring_upcase (const rstring * rstr)
Return a copy of rstr with everything uppercase.
Parameters
rstr The rstring to upcase. (Not modified.)
Return values
rstring* A valid rstring copy of rstr with all chars uppercase.
NULL The input rstring is invalid or there was an error.
Warning
The caller must free the result.
Definition at line 215 of file rstring.c.
References rstring_copy(), rstring_length(), and rstring_new().
 {
   if (rstring_bad(rstr)) { return NULL; }
   int len = rstring_length(rstr);
   if (len == RERROR) { return NULL; }
   if (len == 0) { return rstring_new(""); }
   rstring* new_rstr = rstring_copy(rstr);
   if (new_rstr == NULL) { return NULL; }
   int val = btoupper(new_rstr);
   if (val == RERROR) { return NULL; }
   return new_rstr;
 }