Ruby-like C: src/rstring.h File Reference
rstring.h File Reference
Header file for rstring.c.
#include "rlib.h"
Macros
#define rstring_bad(rstr) (rstr == NULL || rstr->data == NULL || rstr->mlen < rstr->slen || rstr->slen < 0 || rstr->mlen <= 0)
These conditions must hold for the rstring to be valid. See the btolower function for this.
#define rstring_array_bad(rary) (rary == NULL || rary->entry == NULL || rary->mlen < rary->qty || rary->qty < 0 || rary->mlen <= 0)
Check that an rstring_array is valid.
#define rstring_data(rstr) ((rstring*)bdata((bstring)rstr))
Get the ->data portion of the rstring (i.e., the char* part).
#define rstring_format(fmt, ...) ((rstring*)bformat(fmt, __VA_ARGS__))
This is like Ruby's "apple %s" % "pie" % operator.
Typedefs
typedef struct tagbstring rstring
typedef struct bstrList rstring_array
Functions
rstring * rstring_new (const char *cstr)
Make a new rstring from c string.
rstring * rstring_copy (const rstring *rstr)
Copies the rstring.
int rstring_free (rstring *rstr)
Free the rstring.
rstring * rstring_chomp (const rstring *rstr)
Make a new string with final trailing record separator removed.
rstring * rstring_downcase (const rstring *rstr)
Return a copy of rstr with everything lowercase.
rstring * rstring_gsub (const rstring *rstr, const rstring *pattern, const rstring *replacement)
Return a copy of rstr withh all occurrences of pattern substituted for the value of replacement.
rstring * rstring_lstrip (const rstring *rstr)
Returns a copy of rstr with leading whitespace removed.
rstring * rstring_reverse (const rstring *rstr)
Returns a new rstring with the characters from rstr in reverse order.
rstring * rstring_rstrip (const rstring *rstr)
Returns a copy of rstr with trailing whitespace removed.
rstring * rstring_slice1 (const rstring *rstr, int index)
Gives the char at index but as an rstring.
rstring * rstring_slice (const rstring *rstr, int index, int length)
Return a substring starting at index of a given length (clamped by the end of rstr).
rstring * rstring_strip (const rstring *rstr)
Returns a copy of rstr with leading and trailing whitespace removed.
rstring * rstring_upcase (const rstring *rstr)
Return a copy of rstr with everything uppercase.
int rstring_eql (const rstring *rstr1, const rstring *rstr2)
Two strings are equal if they have the same length and content.
int rstring_eql_cstr (const rstring *rstr, const char *cstr)
Two strings are equal if they have the same length and content.
int rstring_include (const rstring *rstr, const rstring *substring)
Tells whether rstr contains the other rstring.
int rstring_index (const rstring *rstr, const rstring *substring)
Tells the first occurence of substring in rstr.
int rstring_index_offset (const rstring *rstr, const rstring *substring, int start_pos)
Tells the first occurence (starting at offset) of substring in rstr.
int rstring_length (const rstring *rstr)
Returns the length of the rstring.
int rstring_char_at (const rstring *rstr, int idx)
Return the char at given position.
rstring_array * rstring_array_new ()
int rstring_array_free (rstring_array *rary)
int rstring_array_push_cstr (rstring_array *rary, char *cstr)
int rstring_array_push_rstr (rstring_array *rary, rstring *rstr)
rstring * rstring_array_get (rstring_array *rary, int index)
rstring * rstring_array_join (rstring_array *rstrings, const rstring *sep)
rstring_array * rstring_split (rstring *rstr, const rstring *sep)
Detailed Description
Header file for rstring.c.
Author
Ryan Moore
See also
https://ruby-doc.org/core-2.5.0/String.html
Definition in file rstring.h.
Macro Definition Documentation
rstring_data
#define rstring_data (rstr) ((rstring*)bdata((bstring)rstr))
Get the ->data portion of the rstring (i.e., the char* part).
Parameters
rstr We will get the data of this rstring.
Return values
char* The char* part of the rstring.
NULL The rstring is NULL.
Definition at line 37 of file rstring.h.
rstring_format
#define rstring_format (fmt, ...) ((rstring*)bformat(fmt, __VA_ARGS__))
This is like Ruby's "apple %s" % "pie" % operator.
... initialization code ...
rstring* rstr = rstring_new("pies");
rstring* new_rstr = rstring_format("%d apple %s", 3, rstring_data(rstr));
... cleanup code ...
Parameters
fmt This is a char* format string.
... A variable number of args to put into the fmt string.
Return values
rstring* A new rstring holding the formatted string.
Note
This one doesn't take rstrings like all the rest, rather char* or ints, or floats or whatever.
Warning
If the BSTRLIB_NOVSNP macro has been set when bstrlib has been compiled the bformat function is not present. This will NOT be checked.
Todo:
Ideally, you could put rstrings straight in to plases where you have the s character and it would JustWork.
Definition at line 61 of file rstring.h.
Function Documentation
rstring_char_at()
int rstring_char_at (const rstring * rstr, int idx)
Return the char at given position.
Parameters
rstr Not modified.
index Get the char at this index in rstr.
Return values
char The idx'th character of the rstring.
RERROR If The input rstring is invalid or there was an error.
Definition at line 596 of file rstring.c.
References rstring_bad.
 {
   if (rstring_bad(rstr)) { return RERROR; }
   return bchare(rstr, idx, RERROR);
 }
rstring_chomp()
rstring* rstring_chomp (const rstring * rstr)
Make a new string with final trailing record separator removed.
Will remove \n, \r, and \r\n. If there are multiple line separators at the end of the string, only the last one will be removed.
Parameters
rstr An rstring. (Not modified.)
Return values
rstring* A valid rstring without the last record separator.
NULL The input rstring is invalid or there was an error.
Warning
The caller must free the result.
Definition at line 84 of file rstring.c.
References rstring_bad, rstring_char_at(), rstring_copy(), rstring_length(), and rstring_slice().
 {
   if (rstring_bad(rstr)) { return NULL; }
   int len = rstring_length(rstr);
   if (len == RERROR) { return NULL; }
   int c_last = rstring_char_at(rstr, len - 1);
   if (c_last == RERROR) { return NULL; }
   if (c_last == '\r') {
     return rstring_slice(rstr, 0, len-1);
   }
   else if (c_last == '\n' && rstring_char_at(rstr, len - 2) == '\r') {
     return rstring_slice(rstr, 0, len-2);
   }
   else if (c_last == '\n') {
     return rstring_slice(rstr, 0, len-1);
   }
   else {
     return rstring_copy(rstr);
   }
 }
rstring_copy()
rstring* rstring_copy (const rstring * rstr)
Copies the rstring.
Parameters
rstr The rstring to copy. (Not modified.)
Return values
rstring* A valid rstring copy.
NULL The input rstring is invalid or there was an error.
Warning
The caller must free the result.
Definition at line 50 of file rstring.c.
References rstring_bad.
 {
   if (rstring_bad(rstr)) { return NULL; }
   return (rstring*)bstrcpy((const_bstring)rstr);
 }
rstring_downcase()
rstring* rstring_downcase (const rstring * rstr)
Return a copy of rstr with everything lowercase.
Parameters
rstr The rstring to downcase. (Not modified.)
Return values
rstring* A valid rstring copy of rstr with all chars lowercase.
NULL The input rstring is invalid or there was an error.
Warning
The caller must free the result.
Definition at line 119 of file rstring.c.
References rstring_bad, rstring_copy(), rstring_length(), and rstring_new().
 {
   if (rstring_bad(rstr)) { return NULL; }
   int len = rstring_length(rstr);
   if (len == RERROR) { return NULL; }
   if (len == 0) { return rstring_new(""); }
   rstring* new_rstr = rstring_copy(rstr);
   if (new_rstr == NULL) { return NULL; }
   int val = btolower(new_rstr);
   if (val == RERROR) { return NULL; }
   return new_rstr;
 }
rstring_eql()
int rstring_eql (const rstring * rstr1, const rstring * rstr2)
Two strings are equal if they have the same length and content.
Parameters
rstr1 Not modified.
rstr2 Not modified.
Return values
RTRUE The rstrings are equal.
RFALSE The rstrings are not equal.
RERROR The rstr1 or rstr2 is invalid or there was an error.
Note
This differs from ruby in that you can't just check for true or false, you must check for 1 or 0 as RERROR signals an error.
Definition at line 429 of file rstring.c.
References rstring_bad.
 {
   if (rstring_bad(rstr1)) { return RERROR; }
   if (rstring_bad(rstr2)) { return RERROR; }
   int val = biseq((const_bstring)rstr1, (const_bstring)rstr2);
   if (val == 1) {
     return RTRUE;
   }
   else if (val == 0) {
     return RFALSE;
   }
   else {
     return RERROR;
   }
 }
rstring_eql_cstr()
int rstring_eql_cstr (const rstring * rstr, const char * cstr)
Two strings are equal if they have the same length and content.
Parameters
rstr Not modified.
cstr Not modified.
Return values
RTRUE The strings are equal.
RFALSE The strings are not equal.
RERROR The rstr or cstring is invalid or there was an error.
Note
This differs from ruby in that you can't just check for true or false, you must check for 1 or 0 as RERROR signals an error.
Definition at line 460 of file rstring.c.
References rstring_bad.
 {
   if (rstring_bad(rstr)) { return RERROR; }
   if (cstr == NULL) { return RERROR; }
   int val = biseqcstr((const_bstring)rstr, cstr);
   if (val == 1) {
     return RTRUE;
   }
   else if (val == 0) {
     return RFALSE;
   }
   else {
     return RERROR;
   }
 }
rstring_free()
int rstring_free (rstring * rstr)
Free the rstring.
Parameters
rstr An rstring to free.
Return values
RERROR If there was an error.
ROKAY If there were no errors.
Definition at line 66 of file rstring.c.
 {
   return bdestroy((bstring)rstr);
 }
rstring_gsub()
rstring* rstring_gsub (const rstring * rstr, const rstring * pattern, const rstring * replacement)
Return a copy of rstr withh all occurrences of pattern substituted for the value of replacement.
rstring* rstr = rstring_new("aabaAb");
rstring* pattern = rstring_new("a");
rstring* replacement = rstring_new("aa");
rstring* expected = rstring_new("aaaabaaAb")
rstring* actual = rstring_gsub(rstr, pattern, replacement);
assert(rstring_eql(expected, actual) == RTRUE);
... code to free variables here ...
Parameters
rstr The rstring for replacing.
pattern The rstring pattern to search for.
replacement The rstring to replace with.
Return values
rstring* A valid rstring with the appropriate replacements.
NULL Any of the args are invalid or if there were errors.
Note
It differs from ruby in that pattern must have length > 0 (i.e., be a non-empty string. Things get pretty weird in Ruby when the pattern is an empty string....
Definition at line 164 of file rstring.c.
References rstring_bad, rstring_copy(), and rstring_free().
 {
   if (rstring_bad(rstr)) { return NULL; }
   if (rstring_bad(pattern)) { return NULL; }
   if (rstring_bad(replacement)) { return NULL; }
   rstring* copy = rstring_copy(rstr);
   if (rstring_bad(copy)) { return NULL; }
   int start_pos = 0;
   int val = bfindreplace((bstring)copy,
                          (const_bstring)pattern,
                          (const_bstring)replacement,
                          start_pos);
   if (val == BSTR_ERR) { rstring_free(copy); return NULL; }
   return copy;
 }
rstring_include()
int rstring_include (const rstring * rstr, const rstring * substring)
Tells whether rstr contains the other rstring.
Parameters
rstr The rstring to search in.
substring The rstring to search for.
Return values
RTRUE The substring is present.
RFALSE The substring is not present.
RERROR Either input rstring is invalid.
Definition at line 489 of file rstring.c.
References rstring_bad.
 {
   if (rstring_bad(rstr)) { return RERROR; }
   if (rstring_bad(substring)) { return RERROR; }
   int start_pos = 0;
   int val = binstr(rstr, start_pos, substring);
   if (val == BSTR_ERR) {
     /* It wasn't found. */
     return RFALSE;
   }
   else {
     return RTRUE;
   }
 }
rstring_index()
int rstring_index (const rstring * rstr, const rstring * substring)
Tells the first occurence of substring in rstr.
Parameters
rstr The rstring to search in.
substring The rstring to search for.
Return values
index The index of the first occurence of substring in rstr.
RERROR Either input rstrings are invalid or the substring was not found.
Todo:
Need a better way to handle errors as not found and error would be the same thing for this function.
Definition at line 518 of file rstring.c.
References rstring_bad.
 {
   if (rstring_bad(rstr)) { return RERROR; }
   if (rstring_bad(substring)) { return RERROR; }
   int start_pos = 0;
   int val = binstr(rstr, start_pos, substring);
   if (val == BSTR_ERR) {
     /* It wasn't found. */
     return RERROR;
   }
   else {
     return val;
   }
 }
rstring_index_offset()
int rstring_index_offset (const rstring * rstr, const rstring * substring, int offset)
Tells the first occurence (starting at offset) of substring in rstr.
Parameters
rstr The rstring to search in.
substring The rstring to search for.
offset The index in rstr to start the search from.
Return values
index The index of the first occurence (>= index) of substring in rstr.
RERROR Either input rstrings are invalid or the substring was not found in the string after the offset/index.
Todo:
Need a better way to handle errors as not found and error would be the same thing for this function.
Definition at line 548 of file rstring.c.
References rstring_bad.
 {
   if (rstring_bad(rstr)) { return RERROR; }
   if (rstring_bad(substring)) { return RERROR; }
   int val = binstr(rstr, offset, substring);
   if (val == BSTR_ERR) {
     /* It wasn't found. */
     return RERROR;
   }
   else {
     return val;
   }
 }
rstring_length()
int rstring_length (const rstring * rstr)
Returns the length of the rstring.
Parameters
rstr Not modified.
Return values
length The length of the rstring.
RERROR The input rstring is invalid or there was an error.
Definition at line 573 of file rstring.c.
References rstring_bad.
 {
   if (rstring_bad(rstr)) { return RERROR; }
   return blengthe(rstr, RERROR);
 }
rstring_lstrip()
rstring* rstring_lstrip (const rstring * rstr)
Returns a copy of rstr with leading whitespace removed.
Parameters
rstr The rstring to strip.
Return values
rstring* A valid copy of rstr with leading whitespace stripped.
NULL The input rstring is invalid or there was an error.
Warning
The caller must free the result.
Todo:
Lots of code duplication with strip(), lstrip(), and rstrip().
Definition at line 296 of file rstring.c.
References rstring_bad, rstring_copy(), rstring_free(), rstring_length(), and rstring_new().
 {
   if (rstring_bad(rstr)) { return NULL; }
   int len = rstring_length(rstr);
   if (len == RERROR) { return NULL; }
   if (len == 0) { return rstring_new(""); }
   rstring* copy = rstring_copy(rstr);
   if (rstring_bad(copy)) { return NULL; }
   int val = bltrimws(copy);
   if (val == BSTR_ERR) { rstring_free(copy); return NULL; }
   return copy;
 }
rstring_new()
rstring* rstring_new (const char * cstr)
Make a new rstring from c string.
Parameters
cstr Char array to convert to rstring. (Not modified.)
Return values
rstring* A valid rstring.
NULL The cstr is NULL, the length of cstr >= INT_MAX, or there were errors creating the rstring.
Warning
The caller must free the result.
Definition at line 28 of file rstring.c.
References rstring_bad.
 {
   if (cstr == NULL) { return NULL; }
   rstring* rstr = (rstring*)bfromcstr_check_length(cstr);
   if (rstring_bad(rstr)) { return NULL; }
   return rstr;
 }
rstring_reverse()
rstring* rstring_reverse (const rstring * rstr)
Returns a new rstring with the characters from rstr in reverse order.
Parameters
rstr The rstring for reversing.
Return values
rstring* A valid rstring copy of rstr with chars reversed.
NULL The input rstring was invalid or there was an error.
Warning
The caller must free the result.
Definition at line 325 of file rstring.c.
References rstring_bad, and rstring_copy().
 {
   if (rstring_bad(rstr)) { return NULL; }
   rstring* copy = rstring_copy(rstr);
   if (rstring_bad(copy)) { return NULL; }
   /* From bstraux.c */
   int i, n, m;
   unsigned char t;
   n = copy->slen;
   if (2 <= n) {
     m = ((unsigned)n) >> 1;
     n--;
     for (i=0; i < m; i++) {
       t = copy->data[n - i];
       copy->data[n - i] = copy->data[i];
       copy->data[i] = t;
     }
   }
   return copy;
 }
rstring_rstrip()
rstring* rstring_rstrip (const rstring * rstr)
Returns a copy of rstr with trailing whitespace removed.
Parameters
rstr The rstring to strip.
Return values
rstring* A valid copy of rstr with trailing whitespace stripped.
NULL The input rstring is invalid or there was an error.
Warning
The caller must free the result.
Todo:
Lots of code duplication with strip(), lstrip(), and rstrip().
Definition at line 363 of file rstring.c.
References rstring_bad, rstring_copy(), rstring_free(), rstring_length(), and rstring_new().
 {
   if (rstring_bad(rstr)) { return NULL; }
   int len = rstring_length(rstr);
   if (len == RERROR) { return NULL; }
   if (len == 0) { return rstring_new(""); }
   rstring* copy = rstring_copy(rstr);
   if (rstring_bad(copy)) { return NULL; }
   int val = brtrimws(copy);
   if (val == BSTR_ERR) { rstring_free(copy); return NULL; }
   return copy;
 }
rstring_slice()
rstring* rstring_slice (const rstring * rstr, int index, int length)
Return a substring starting at index of a given length (clamped by the end of rstr).
Parameters
rstr The rstring that we want to substring. (Not modified.)
index The starting index of the substring.
length The length of the substring.
Return values
rstring* A valid rstring containing the specified substring.
NULL The input rstring is invalid or there was an error.
Note
There is a bit of weird behavior if the index is the length of the rstring, an empty string will be returned rather than NULL, which is the behavior of rstring_slice1. It is this way to match the Ruby behavior.
Warning
The caller must free the result.
Definition at line 226 of file rstring.c.
References rstring_bad, rstring_length(), and rstring_new().
 {
   if (rstring_bad(rstr)) { return NULL; }
   int len = rstring_length(rstr);
   if (len == RERROR) { return NULL; }
   int idx = index;
   /* Special weird ruby case. */
   if (index == len) {
     return rstring_new("");
   }
   /* Negative indices count back from the end. */
   if (index < 0) {
     idx = len - idx - 1;
   }
   if (idx > len || length < 0) {
     return NULL;
   }
   return (rstring*)bmidstr((bstring)rstr, index, length);
 }
rstring_slice1()
rstring* rstring_slice1 (const rstring * rstr, int index)
Gives the char at index but as an rstring.
Parameters
rstr The rstring that we want to substring. (Not modified.)
index The starting index of the substring.
Return values
NULL The rstring is invalid, the index < 0 or >= rstr length, or there was an error.
Returns
A single character rstring or NULL if there were errors.
Warning
The caller must free the result.
Definition at line 200 of file rstring.c.
References rstring_bad, and rstring_length().
 {
   if (rstring_bad(rstr)) { return NULL; }
   if (index < 0 || index >= rstring_length(rstr)) {
     return NULL;
   }
   return bmidstr(rstr, index, 1);
 }
rstring_strip()
rstring* rstring_strip (const rstring * rstr)
Returns a copy of rstr with leading and trailing whitespace removed.
Parameters
rstr The rstring to strip.
Return values
rstring* A valid copy of rstr with whitespace stripped.
NULL The input rstring is invalid or there was an error.
Warning
The caller must free the result.
Todo:
Lots of code duplication with strip(), lstrip(), and rstrip().
Definition at line 265 of file rstring.c.
References rstring_bad, rstring_copy(), rstring_free(), rstring_length(), and rstring_new().
 {
   if (rstring_bad(rstr)) { return NULL; }
   int len = rstring_length(rstr);
   if (len == RERROR) { return NULL; }
   if (len == 0) { return rstring_new(""); }
   rstring* copy = rstring_copy(rstr);
   if (rstring_bad(copy)) { return NULL; }
   int val = btrimws(copy);
   if (val == BSTR_ERR) { rstring_free(copy); return NULL; }
   return copy;
 }
rstring_upcase()
rstring* rstring_upcase (const rstring * rstr)
Return a copy of rstr with everything uppercase.
Parameters
rstr The rstring to upcase. (Not modified.)
Return values
rstring* A valid rstring copy of rstr with all chars uppercase.
NULL The input rstring is invalid or there was an error.
Warning
The caller must free the result.
Definition at line 394 of file rstring.c.
References rstring_bad, rstring_copy(), rstring_length(), and rstring_new().
 {
   if (rstring_bad(rstr)) { return NULL; }
   int len = rstring_length(rstr);
   if (len == RERROR) { return NULL; }
   if (len == 0) { return rstring_new(""); }
   rstring* new_rstr = rstring_copy(rstr);
   if (new_rstr == NULL) { return NULL; }
   int val = btoupper(new_rstr);
   if (val == RERROR) { return NULL; }
   return new_rstr;
 }