/** @mainpage README
 *
 * @section intro_sec Introduction
 *
A library of functions that behave more or less like their Ruby counterparts.

The unit tests have all their expected outputs generated by calls to the Ruby methods that the C functions are based on so that whatever value you'd get in Ruby you should also get with these C functions.

 Uses the [Better String Library](https://github.com/websnarf/bstrlib) internally.

 *
 * @section info_sec More info
 *
 * These are the API docs.  For more info see https://github.com/mooreryan/ruby_like_c
 *
 */


#ifndef _RLIB_H
#define _RLIB_H

#define RERROR BSTR_ERR
#define ROKAY BSTR_OK
#define RTRUE 1
#define RFALSE 0

#endif // _RLIB_H
